execution-jar=${classpath}
class=com.netease.vc.data.common.Hive2Kafka
conf.spark.source.query="select user_id as userId,'OM3827_2HEVENT_PART2_CALLBACK_METRIC' as metricId from vc.ads_vc_om_3827_a_d where dt = '${azkaban.flow.current.date}' limit 1"
params= --topic vc_user_callback_topic --servers vcharacter-kafka-prod3.gy.ntes:9092,vcharacter-kafka-prod1.gy.ntes:9092,vcharacter-kafka-prod2.gy.ntes:9092

dependencies=ads_vc_om_3827_a_d