#tango\u5E93
jdbc.driverClass=com.mysql.jdbc.Driver
#jdbc.url=jdbc:mysql://10.222.10.115:3331/lofter_tango?user=tango_test&password=qSW_1@gV3&verifyServerCertificate=false&useSSL=false&socketTimeout=30000&connectTimeout=5000
#jdbc.user=tango_test
#jdbc.password=qSW_1@gV3

#DDB-\u4E0D\u652F\u6301
#jdbc.url=jdbc:mysql://10.194.225.157:6000/public?user=public_test&password=eThNXWMVirg
#jdbc.user=public_test
#jdbc.password=eThNXWMVirg

#comic-statis\u5E93
#jdbc.url=jdbc:mysql://10.201.241.215:3331/lofter-aso?user=lofter_aso&password=hCXBNkBo{&verifyServerCertificate=false&useSSL=false&socketTimeout=30000&connectTimeout=5000
#\u8868\u540D
tableName=PaidContent_Activity
#\u5B9E\u4F53\u540D
domainObjectName=PaidContentActivity
#\u6A21\u578B\u5B9A\u4E49\uFF08\u53EF\u9009\uFF1APO,VO,Query,DTO\uFF09\uFF0C \u4E0D\u6307\u5B9A\u4E0D\u4F1A\u751F\u6210\u5BF9\u5E94\u6587\u4EF6
domain.base.definition=PO,VO,Query
#\u6570\u636E\u6E90\u540D\u79F0\uFF0C\u591A\u6570\u636E\u6E90\u65F6\u6307\u5B9Amapper\u4F1A\u52A0\u4E0A@Datasource\u6CE8\u89E3, \u4F8B\u5982\uFF1Acom.netease.lofter.tango.impl.config.DbConfig.DEFAULT_DATASOURCE
dataSourceName=com.netease.lofter.tango.impl.config.DbConfig.MAIN_DATASOURCE
#\u5B50\u5305\uFF0C\u591A\u6570\u636E\u6E90\u65F6\u5EFA\u8BAE\u5B50\u5305\u9694\u79BB\u5F00, \u4F8B\u5982\uFF1A".statis" (\u6240\u6709Statistic\u5E93\u4E0B\u7684\u5185\u5BB9\u90FD\u653E\u5230\u8FD9\u4E2A\u5305\u4E0B)
subPackage=.trade
#####################################\u4EE5\u4E0B\u65E0\u9700\u66F4\u6539#####################3################
#\u5DE5\u7A0B\u5B50\u6A21\u5757\u76EE\u5F55
client.targetProject=lofter-service-tango-api
service.targetProject=lofter-service-tango-impl
#\u65E0\u9700\u66F4\u6539
useActualColumnNames=true
#\u6A21\u578B\u8DEF\u5F84\u914D\u7F6E(domain.model.{type}.xxx)
#DTO\u914D\u7F6E
domain.model.dto.targetProject=${client.targetProject}/src/main/java
domain.model.dto.targetPackage=com.netease.lofter.tango.api.dto${subPackage}
#PO\u914D\u7F6E
domain.model.po.targetProject=${service.targetProject}/src/main/java
domain.model.po.targetPackage=com.netease.lofter.tango.impl.entity${subPackage}
#VO\u914D\u7F6E
domain.model.vo.targetProject=${service.targetProject}/src/main/java
domain.model.vo.targetPackage=com.netease.lofter.tango.impl.web.vo${subPackage}
#Query\u914D\u7F6E
domain.model.query.targetProject=${service.targetProject}/src/main/java
domain.model.query.targetPackage=com.netease.lofter.tango.impl.web.query${subPackage}
domain.model.query.superClass=com.netease.lofter.tango.impl.web.ro.BaseQuery
#client\u914D\u7F6E(domain.client.{type}.xxx)
#Mapper\u914D\u7F6E
domain.client.mapper.targetProject=${service.targetProject}/src/main/java
domain.client.mapper.targetPackage=com.netease.lofter.tango.impl.mapper${subPackage}
#Delegate\u914D\u7F6E
domain.client.delegate.targetProject=${service.targetProject}/src/main/java
domain.client.delegate.targetPackage=com.netease.lofter.tango.impl.delegate${subPackage}
#Service\u914D\u7F6E
domain.client.service.targetProject=${service.targetProject}/src/main/java
domain.client.service.targetPackage=com.netease.lofter.tango.impl.service${subPackage}
#Controller\u914D\u7F6E
domain.client.controller.targetProject=${service.targetProject}/src/main/java
domain.client.controller.targetPackage=com.netease.lofter.tango.impl.web.controller${subPackage}
#\u57FA\u7840\u4F9D\u8D56\u914D\u7F6E\u65E0\u9700\u6539\u52A8(domain.base.{className})
domain.base.PageDO=com.netease.lofter.tango.impl.entity.PageDO
domain.base.PageVO=com.netease.lofter.tango.impl.web.vo.PageVO
domain.base.BageQuery=com.netease.lofter.tango.impl.web.ro.BaseQuery
domain.base.mappers=com.netease.yaolu.commons.spring.mybatis.mapper.CommonMapper,com.netease.yaolu.commons.spring.mybatis.mapper.DeleteCommonMapper
domain.base.CommonDeleteDelegate=com.netease.lofter.tango.impl.delegate.common.CommonDeleteDelegate
domain.base.PageResult=com.netease.lofter.tango.impl.web.vo.PageResult
domain.base.Result=com.netease.lofter.tango.impl.web.vo.Result
domain.base.PrimaryKey=com.netease.lofter.tango.impl.web.vo.PrimiaryKey
domain.base.AssertUtils=com.netease.lofter.tango.impl.util.AssertUtils
domain.base.BeanUtils=com.netease.lofter.tango.impl.util.BeanUtils

