type=sparksql
hive.query.01=\
with device_fisrt_userid as ( \
    select dt, user_id, exp_id, bucket_id \
    from vc.dwd_ab_platform_exp_user_di \
    where dt between '${azkaban.flow.30.days.ago}' and '${azkaban.flow.1.days.ago}' and bucket_id not in (10,12) \
    group by 1,2,3,4 \
), \
pay_source_month as( \
    select dt,user_id,sum(order_price) as amount, count(distinct order_id) as order_cnt, \
        sum(if(item_id in (100005,100006,100007,100008,100009,100010,100011,100012) , order_price, 0)) as new_gift_package_amount, \
        count(if(item_id in (100005,100006,100007,100008,100009,100010,100011,100012) , order_id, null)) as new_gift_package_order_cnt, \
        sum(if(item_id in (100001,100002,100003,100004) , order_price, 0)) as old_gift_package_amount, \
        count(if(item_id in (100001,100002,100003,100004) , order_id, null)) as old_gift_package_order_cnt \
    from vc.dwd_vc_order_i_d \
    where dt between '${azkaban.flow.30.days.ago}' and '${azkaban.flow.1.days.ago}' and is_test_user = 'N' and order_status = 2 and order_price > 0 \
    group by dt,user_id \
), \
gmv_source_month as ( \
    select dt,user_id,sum(order_price) as amount \
    from vc.dwd_vc_order_i_d \
    where dt between '${azkaban.flow.30.days.ago}' and '${azkaban.flow.1.days.ago}' and is_test_user = 'N' and order_price > 0 \
    group by dt,user_id \
), \
talk_source_month as( \
    select dt,user_id,sum(talk_cnt) as chat_rounds \
    from vc.dws_vc_uc_talk_day_cnt_single_i_d \
    where dt between '${azkaban.flow.30.days.ago}' and '${azkaban.flow.1.days.ago}' \
    group by dt,user_id \
), \
active_source_month as( \
    select dt,device_udid,nvl(user_id ,abs(cast(hash(device_udid) as bigint))) as user_id \
    from vc.dwd_vc_user_active_i_d \
    where dt between '${azkaban.flow.30.days.ago}' and '${azkaban.flow.1.days.ago}' \
    group by dt,device_udid,user_id \
), \
user_dates as(  \
    SELECT DISTINCT dt, user_id \
    FROM active_source_month \
), \
event_source_month as ( \
    select a.dt,nvl(a.user_id ,abs(cast(hash(device_udid) as bigint))) as user_id \
    from ( \
        select dt,device_udid,user_id \
        from vc.dwd_vc_app_event_i_d \
        where dt between '${azkaban.flow.30.days.ago}' and '${azkaban.flow.1.days.ago}' and event_id = 'h1-1' \
        group by dt,device_udid,user_id \
    )a \
), \
talk_metric_source as( \
    select distinct bucket_id, base_date,user_id,period,chat_roundss as chat_rounds, if(chat_roundss >= 10,1,0) as chat_10_uv, if(chat_roundss >= 30,1,0) as chat_30_uv,chat_uv \
    from( \
        select a.bucket_id, a.dt as base_date,a.user_id,1 as chat_uv,sum(b.chat_rounds) as chat_roundss,0 as period \
        from device_fisrt_userid a \
        join( \
            select dt,user_id,chat_rounds \
            from talk_source_month \
        )b on a.user_id = b.user_id and b.dt = a.dt \
        group by a.bucket_id,a.dt,a.user_id \
    union all \
        select a.bucket_id,a.dt as base_date,a.user_id,1 as chat_uv,sum(b.chat_rounds) as chat_roundss,2 as period \
        from device_fisrt_userid a \
        join( \
            select dt,user_id,chat_rounds \
            from talk_source_month \
        )b on a.user_id = b.user_id and b.dt between a.dt and date_add(a.dt,2) \
        group by a.bucket_id,a.dt,a.user_id \
    union all  \
        select a.bucket_id,a.dt as base_date,a.user_id,1 as chat_uv,sum(b.chat_rounds) as chat_roundss,6 as period \
        from device_fisrt_userid a \
        join( \
            select dt,user_id,chat_rounds \
            from talk_source_month \
        )b on a.user_id = b.user_id and b.dt between a.dt and date_add(a.dt,6) \
        group by a.bucket_id,a.dt,a.user_id \
    union all  \
        select a.bucket_id,a.dt as base_date,a.user_id,1 as chat_uv,sum(b.chat_rounds) as chat_roundss,13 as period \
        from device_fisrt_userid a   \
        join( \
            select dt,user_id,chat_rounds \
            from talk_source_month \
        )b on a.user_id = b.user_id and b.dt between a.dt and date_add(a.dt,13) \
        group by a.bucket_id,a.dt,a.user_id \
    union all  \
        select a.bucket_id,a.dt as base_date,a.user_id,1 as chat_uv,sum(b.chat_rounds) as chat_roundss,29 as period \
        from device_fisrt_userid a   \
        join( \
            select dt,user_id,chat_rounds \
            from talk_source_month \
        )b on a.user_id = b.user_id and b.dt between a.dt and date_add(a.dt,29) \
        group by a.bucket_id,a.dt,a.user_id \
    ) \
    where date_add(base_date,period) <= '${azkaban.flow.1.days.ago}' \
), \
pay_metric_source as( \
    select distinct bucket_id,base_date,period,user_id,pay_uv,pay_money,order_cnt,new_gift_package_pay_uv, \
    new_gift_package_amount,new_gift_package_order_cnt,old_gift_package_pay_uv,old_gift_package_amount, \
    old_gift_package_order_cnt \
    from( \
        select a.bucket_id,a.dt as base_date,a.user_id,0 as period,1 as pay_uv,sum(b.amount) as pay_money, \
            sum(order_cnt) order_cnt, \
            max(if(new_gift_package_amount > 0, 1, 0)) as new_gift_package_pay_uv, \
            sum(new_gift_package_amount) new_gift_package_amount, \
            sum(new_gift_package_order_cnt) new_gift_package_order_cnt, \
            max(if(old_gift_package_amount > 0, 1, 0)) as old_gift_package_pay_uv, \
            sum(old_gift_package_amount) old_gift_package_amount, \
            sum(old_gift_package_order_cnt) old_gift_package_order_cnt \
        from device_fisrt_userid a \
        join( \
            select * \
            from pay_source_month \
        )b on a.user_id = b.user_id and b.dt = a.dt \
        group by a.bucket_id,a.dt,a.user_id \
    union all \
        select a.bucket_id,a.dt as base_date,a.user_id,2 as period,1 as pay_uv,sum(b.amount) as pay_money, \
            sum(order_cnt) order_cnt, \
            max(if(new_gift_package_amount > 0, 1, 0)) as new_gift_package_pay_uv, \
            sum(new_gift_package_amount) new_gift_package_amount, \
            sum(new_gift_package_order_cnt) new_gift_package_order_cnt, \
            max(if(old_gift_package_amount > 0, 1, 0)) as old_gift_package_pay_uv, \
            sum(old_gift_package_amount) old_gift_package_amount, \
            sum(old_gift_package_order_cnt) old_gift_package_order_cnt \
        from device_fisrt_userid a \
        join( \
            select * \
            from pay_source_month \
        )b on a.user_id = b.user_id and b.dt between a.dt and date_add(a.dt,2) \
        group by a.bucket_id,a.dt,a.user_id \
    union all \
        select a.bucket_id,a.dt as base_date,a.user_id,6 as period,1 as pay_uv,sum(b.amount) as pay_money, \
            sum(order_cnt) order_cnt, \
            max(if(new_gift_package_amount > 0, 1, 0)) as new_gift_package_pay_uv, \
            sum(new_gift_package_amount) new_gift_package_amount, \
            sum(new_gift_package_order_cnt) new_gift_package_order_cnt, \
            max(if(old_gift_package_amount > 0, 1, 0)) as old_gift_package_pay_uv, \
            sum(old_gift_package_amount) old_gift_package_amount, \
            sum(old_gift_package_order_cnt) old_gift_package_order_cnt \
        from device_fisrt_userid a \
        join( \
            select * \
            from pay_source_month \
        )b on a.user_id = b.user_id and b.dt between a.dt and date_add(a.dt,6) \
        group by a.bucket_id,a.dt,a.user_id \
    union all  \
        select a.bucket_id,a.dt as base_date,a.user_id,13 as period,1 as pay_uv,sum(b.amount) as pay_money, \
          sum(order_cnt) order_cnt, \
          max(if(new_gift_package_amount > 0, 1, 0)) as new_gift_package_pay_uv, \
          sum(new_gift_package_amount) new_gift_package_amount, \
          sum(new_gift_package_order_cnt) new_gift_package_order_cnt, \
          max(if(old_gift_package_amount > 0, 1, 0)) as old_gift_package_pay_uv, \
          sum(old_gift_package_amount) old_gift_package_amount, \
          sum(old_gift_package_order_cnt) old_gift_package_order_cnt \
        from device_fisrt_userid a \
        join( \
            select * \
            from pay_source_month \
        )b on a.user_id = b.user_id and b.dt between a.dt and date_add(a.dt,13) \
        group by a.bucket_id,a.dt,a.user_id \
    union all  \
        select a.bucket_id,a.dt as base_date,a.user_id,29 as period,1 as pay_uv,sum(b.amount) as pay_money, \
          sum(order_cnt) order_cnt, \
          max(if(new_gift_package_amount > 0, 1, 0)) as new_gift_package_pay_uv, \
          sum(new_gift_package_amount) new_gift_package_amount, \
          sum(new_gift_package_order_cnt) new_gift_package_order_cnt, \
          max(if(old_gift_package_amount > 0, 1, 0)) as old_gift_package_pay_uv, \
          sum(old_gift_package_amount) old_gift_package_amount, \
          sum(old_gift_package_order_cnt) old_gift_package_order_cnt \
        from device_fisrt_userid a \
        join( \
            select * \
            from pay_source_month \
        )b on a.user_id = b.user_id and b.dt between a.dt and date_add(a.dt,29) \
        group by a.bucket_id,a.dt,a.user_id \
    ) \
    where date_add(base_date,period) <= '${azkaban.flow.1.days.ago}' \
), \
gmv_metric_source as( \
    select distinct bucket_id,base_date,period,user_id,gmv \
    from( \
        select a.bucket_id,a.dt as base_date,a.user_id,0 as period,sum(b.amount) as gmv \
        from device_fisrt_userid a \
        join( \
            select dt,user_id,amount \
            from gmv_source_month \
        )b on a.user_id = b.user_id and b.dt = a.dt \
        group by a.bucket_id,a.dt,a.user_id \
    union all \
        select a.bucket_id,a.dt as base_date,a.user_id,2 as period,sum(b.amount) as gmv \
        from device_fisrt_userid a \
        join( \
            select dt,user_id,amount \
            from gmv_source_month \
        )b on a.user_id = b.user_id and b.dt between a.dt and date_add(a.dt,2) \
        group by a.bucket_id,a.dt,a.user_id \
    union all \
        select a.bucket_id,a.dt as base_date,a.user_id,6 as period,sum(b.amount) as gmv \
        from device_fisrt_userid a \
        join( \
            select dt,user_id,amount \
            from gmv_source_month \
        )b on a.user_id = b.user_id and b.dt between a.dt and date_add(a.dt,6) \
        group by a.bucket_id,a.dt,a.user_id \
    union all  \
        select a.bucket_id,a.dt as base_date,a.user_id,13 as period,sum(b.amount) as gmv \
        from device_fisrt_userid a \
        join( \
            select dt,user_id,amount \
            from gmv_source_month \
        )b on a.user_id = b.user_id and b.dt between a.dt and date_add(a.dt,13) \
        group by a.bucket_id,a.dt,a.user_id \
    union all  \
        select a.bucket_id,a.dt as base_date,a.user_id,29 as period,sum(b.amount) as gmv \
        from device_fisrt_userid a \
        join( \
            select dt,user_id,amount \
            from gmv_source_month \
        )b on a.user_id = b.user_id and b.dt between a.dt and date_add(a.dt,29) \
        group by a.bucket_id,a.dt,a.user_id \
    ) \
    where date_add(base_date,period) <= '${azkaban.flow.1.days.ago}' \
), \
roles_metric_source as( \
    select dt as base_date,0 as period,user_id,count(character_id) as roles_cnt \
    from vc.dws_vc_uc_talk_day_cnt_single_i_d \
    where dt between '${azkaban.flow.30.days.ago}' and '${azkaban.flow.1.days.ago}' \
    group by dt,user_id \
), \
retain_metric_source as( \
    SELECT \
        base_date, user_id, period, retain_uv \
    FROM ( \
        SELECT \
            a.dt AS base_date, \
            p.period, \
            a.user_id, \
            IF(b.user_id IS NOT NULL, 1, 0) AS retain_uv \
        FROM user_dates a \
        CROSS JOIN ( \
            SELECT 1 AS period \
            UNION ALL SELECT 2 \
            UNION ALL SELECT 6 \
            UNION ALL SELECT 13 \
        ) p \
        LEFT JOIN user_dates b \
        ON a.user_id = b.user_id \
        AND b.dt = DATE_ADD(a.dt, p.period) \
        WHERE a.dt <= DATE_SUB('${azkaban.flow.1.days.ago}', p.period) \
    ) \
), \
visit_chat_metric_source as( \
    select distinct base_date,period,user_id,visit_chat_uv \
    from( \
        select dt as base_date,0 as period,user_id,if(user_id is not null,1,0) as visit_chat_uv \
        from event_source_month \
        union all  \
        select a.dt as base_date,2 as period,a.user_id,if(count(b.user_id)>=1,1,0) as visit_chat_uv \
        from event_source_month a  \
        left join( \
            select dt,user_id \
            from event_source_month \
        )b on a.user_id = b.user_id and b.dt between a.dt and date_add(a.dt,2) \
        group by a.dt,a.user_id \
        union all \
        select a.dt as base_date,6 as period,a.user_id,if(count(b.user_id)>=1,1,0) as visit_chat_uv \
        from event_source_month a  \
        left join( \
            select dt,user_id \
            from event_source_month \
        )b on a.user_id = b.user_id and b.dt between a.dt and date_add(a.dt,6) \
        group by a.dt,a.user_id \
        union all  \
        select a.dt as base_date,13 as period,a.user_id,if(count(b.user_id)>=1,1,0) as visit_chat_uv \
        from event_source_month a  \
        left join( \
            select dt,user_id \
            from event_source_month \
        )b on a.user_id = b.user_id and b.dt between a.dt and date_add(a.dt,13) \
        group by a.dt,a.user_id \
        union all  \
        select a.dt as base_date,29 as period,a.user_id,if(count(b.user_id)>=1,1,0) as visit_chat_uv \
        from event_source_month a  \
        left join( \
            select dt,user_id \
            from event_source_month \
        )b on a.user_id = b.user_id and b.dt between a.dt and date_add(a.dt,29) \
        group by a.dt,a.user_id \
    ) \
    where base_date <= date_sub('${azkaban.flow.1.days.ago}',period) \
), \
visit_metric_source as( \
    select dt as base_date,0 as period ,user_id, 1 as visit_uv \
    from ( \
        select dt,device_udid,user_id \
        from active_source_month \
    ) \
    group by dt,user_id \
union all \
    select base_date,1 as period ,user_id, 1 as visit_uv \
    from ( \
        select base_date,b.device_udid,b.user_id \
        from ( \
            select distinct dt as base_date from device_fisrt_userid \
        )a \
        left join( \
            select dt,device_udid,user_id \
            from active_source_month \
        )b on datediff(b.dt,a.base_date) between 0 and 1 \
    ) \
    group by base_date,user_id \
union all \
    select base_date,2 as period ,user_id, 1 as visit_uv \
    from ( \
        select base_date,b.device_udid,b.user_id \
        from ( \
            select distinct dt as base_date from device_fisrt_userid \
        )a \
        left join( \
            select dt,device_udid,user_id \
            from active_source_month \
        )b on datediff(b.dt,a.base_date) between 0 and 2 \
    ) \
    group by base_date,user_id \
union all \
    select base_date,6 as period ,user_id, 1 as visit_uv \
    from ( \
        select base_date,b.device_udid,b.user_id \
        from ( \
            select distinct dt as base_date from device_fisrt_userid \
        )a \
        left join( \
            select dt,device_udid,user_id \
            from active_source_month \
        )b on datediff(b.dt,a.base_date) between 0 and 6 \
    ) \
    group by base_date,user_id \
union all \
    select base_date,13 as period ,user_id, 1 as visit_uv \
    from ( \
        select base_date,b.device_udid,b.user_id \
        from ( \
            select distinct dt as base_date from device_fisrt_userid \
        )a \
        left join( \
            select dt,device_udid,user_id \
            from active_source_month \
        )b on datediff(b.dt,a.base_date) between 0 and 13 \
    ) \
    group by base_date,user_id \
union all \
    select base_date,29 as period ,user_id, 1 as visit_uv \
    from ( \
        select base_date,b.device_udid,b.user_id \
        from ( \
            select distinct dt as base_date from device_fisrt_userid \
        )a \
        left join( \
            select dt,device_udid,user_id \
            from active_source_month \
        )b on datediff(b.dt,a.base_date) between 0 and 29 \
    ) \
    group by base_date,user_id \
), \
retain_visit_metric_source as( \
    select base_date, b.period, user_id, retain_visit_uv \
    from( \
        select dt as base_date, user_id, 1 as retain_visit_uv \
        from ( \
            select dt,device_udid,user_id \
            from active_source_month \
        ) \
        group by dt,user_id \
    )a \
    cross join( \
        select 1 as period \
        union all select 2 \
        union all select 6 \
        union all select 13 \
    )b \
) \
insert overwrite table vc.dws_ab_platform_vc_metric_di partition(dt = '${azkaban.flow.1.days.ago}') \
select base_date,period,user_id,nvl(chat_rounds,0) chat_rounds,nvl(chat_30_uv,0),nvl(chat_uv,0) chat_uv, \
    nvl(pay_uv,0) pay_uv,nvl(pay_money,0.0) pay_money,nvl(gmv,0.0) gmv,nvl(roles_cnt,0) roles_cnt, \
    nvl(retain_uv,0) retain_uv,nvl(visit_chat_uv,0) visit_chat_uv,nvl(visit_uv,0) visit_uv,nvl(retain_visit_uv,0) retain_visit_uv, nvl(chat_10_uv,0) chat_10_uv, \
    exp_id, bucket_id, nvl(order_cnt,0) order_cnt, nvl(new_gift_package_pay_uv,0) new_gift_package_pay_uv, \
    nvl(new_gift_package_amount,0) new_gift_package_amount, nvl(new_gift_package_order_cnt,0) new_gift_package_order_cnt, \
    nvl(old_gift_package_pay_uv,0) old_gift_package_pay_uv, nvl(old_gift_package_amount,0) old_gift_package_amount, \
    nvl(old_gift_package_order_cnt,0) old_gift_package_order_cnt \
from( \
    select a.dt as base_date,a.user_id as user_id, 0 as period,b.chat_rounds,b.chat_30_uv,b.chat_uv, \
        c.pay_uv,c.pay_money,d.gmv,e.roles_cnt,null as retain_uv,f.visit_chat_uv,g.visit_uv,null as retain_visit_uv, b.chat_10_uv, \
        a.exp_id, a.bucket_id, c.order_cnt, c.new_gift_package_pay_uv, c.new_gift_package_amount, c.new_gift_package_order_cnt, \
        c.old_gift_package_pay_uv, c.old_gift_package_amount, c.old_gift_package_order_cnt \
    from( \
        select dt,user_id, exp_id, bucket_id from device_fisrt_userid \
    )a \
    left join( \
        select * from talk_metric_source where period = 0 \
    )b on a.user_id = b.user_id and a.dt = b.base_date and a.bucket_id = b.bucket_id \
    left join( \
        select * from pay_metric_source where period = 0 \
    )c on a.user_id = c.user_id and a.dt = c.base_date and a.bucket_id = c.bucket_id \
    left join( \
        select * from gmv_metric_source where period = 0 \
    )d on a.user_id = d.user_id and a.dt = d.base_date and a.bucket_id = d.bucket_id \
    left join( \
        select * from roles_metric_source where period = 0 \
    )e on a.user_id = e.user_id and a.dt = e.base_date \
    left join( \
        select * from visit_chat_metric_source where period = 0 \
    )f on a.user_id = f.user_id and a.dt = f.base_date \
    left join( \
        select * from visit_metric_source where period = 0 \
    )g on a.user_id = g.user_id and a.dt = g.base_date \
union all \
    select a.dt as base_date,a.user_id as user_id, 1 as period,null as chat_rounds,null as chat_30_uv,null as chat_uv, \
        null as pay_uv,null as pay_money,null as gmv,null as roles_cnt,b.retain_uv,null as visit_chat_uv,null as visit_uv,h.retain_visit_uv, null as chat_10_uv, \
        a.exp_id, a.bucket_id, null as order_cnt, null as new_gift_package_pay_uv, null as new_gift_package_amount, null as new_gift_package_order_cnt, \
        null as old_gift_package_pay_uv, null as old_gift_package_amount, null as old_gift_package_order_cnt \
    from( \
        select dt,user_id, exp_id, bucket_id from device_fisrt_userid \
    )a \
    left join( \
        select * from retain_metric_source where period = 1 \
    )b on a.user_id = b.user_id and a.dt = b.base_date \
    left join( \
        select * from retain_visit_metric_source where period = 1 \
    )h on a.user_id = h.user_id and a.dt = h.base_date \
union all \
    select a.dt as base_date,a.user_id as user_id, 2 as period,b.chat_rounds,b.chat_30_uv,b.chat_uv, \
        c.pay_uv,c.pay_money,d.gmv,null as roles_cnt,i.retain_uv,f.visit_chat_uv,g.visit_uv,h.retain_visit_uv, b.chat_10_uv, \
        a.exp_id, a.bucket_id, c.order_cnt, c.new_gift_package_pay_uv, c.new_gift_package_amount, c.new_gift_package_order_cnt, \
        c.old_gift_package_pay_uv, c.old_gift_package_amount, c.old_gift_package_order_cnt \
    from( \
        select dt,user_id, exp_id, bucket_id from device_fisrt_userid \
    )a \
    left join( \
        select * from talk_metric_source where period = 2 \
    )b on a.user_id = b.user_id and a.dt = b.base_date and a.bucket_id = b.bucket_id \
    left join( \
        select * from pay_metric_source where period = 2 \
    )c on a.user_id = c.user_id and a.dt = c.base_date and a.bucket_id = c.bucket_id \
    left join( \
        select * from gmv_metric_source where period = 2 \
    )d on a.user_id = d.user_id and a.dt = d.base_date and a.bucket_id = d.bucket_id \
    left join( \
        select * from visit_chat_metric_source where period = 2 \
    )f on a.user_id = f.user_id and a.dt = f.base_date \
    left join( \
        select * from visit_metric_source where period = 2 \
    )g on a.user_id = g.user_id and a.dt = g.base_date \
    left join( \
        select * from retain_visit_metric_source where period = 2 \
    )h on a.user_id = h.user_id and a.dt = h.base_date \
    left join( \
        select * from retain_metric_source where period = 2 \
    )i on a.user_id = i.user_id and a.dt = i.base_date \
union all \
    select a.dt as base_date,a.user_id as user_id, 6 as period,b.chat_rounds,b.chat_30_uv,b.chat_uv, \
        c.pay_uv,c.pay_money,d.gmv,null as roles_cnt,i.retain_uv,f.visit_chat_uv,g.visit_uv,h.retain_visit_uv, b.chat_10_uv \
        , a.exp_id, a.bucket_id, c.order_cnt, c.new_gift_package_pay_uv, c.new_gift_package_amount, c.new_gift_package_order_cnt, \
        c.old_gift_package_pay_uv, c.old_gift_package_amount, c.old_gift_package_order_cnt \
    from( \
        select dt,user_id, exp_id, bucket_id from device_fisrt_userid \
    )a \
    left join( \
        select * from talk_metric_source where period = 6 \
    )b on a.user_id = b.user_id and a.dt = b.base_date and a.bucket_id = b.bucket_id \
    left join( \
        select * from pay_metric_source where period = 6 \
    )c on a.user_id = c.user_id and a.dt = c.base_date and a.bucket_id = c.bucket_id \
    left join( \
        select * from gmv_metric_source where period = 6 \
    )d on a.user_id = d.user_id and a.dt = d.base_date and a.bucket_id = d.bucket_id \
    left join( \
        select * from visit_chat_metric_source where period = 6 \
    )f on a.user_id = f.user_id and a.dt = f.base_date \
    left join( \
        select * from visit_metric_source where period = 6 \
    )g on a.user_id = g.user_id and a.dt = g.base_date \
    left join( \
        select * from retain_visit_metric_source where period = 6 \
    )h on a.user_id = h.user_id and a.dt = h.base_date \
    left join( \
        select * from retain_metric_source where period = 6 \
    )i on a.user_id = i.user_id and a.dt = i.base_date \
union all \
    select a.dt as base_date,a.user_id as user_id, 13 as period,b.chat_rounds,b.chat_30_uv,b.chat_uv, \
        c.pay_uv,c.pay_money,d.gmv,null as roles_cnt, i.retain_uv,f.visit_chat_uv,g.visit_uv, h.retain_visit_uv,b.chat_10_uv \
        , a.exp_id, a.bucket_id, c.order_cnt, c.new_gift_package_pay_uv, c.new_gift_package_amount, c.new_gift_package_order_cnt, \
        c.old_gift_package_pay_uv, c.old_gift_package_amount, c.old_gift_package_order_cnt \
    from( \
        select dt,user_id, exp_id, bucket_id from device_fisrt_userid \
    )a \
    left join( \
        select * from talk_metric_source where period = 13 \
    )b on a.user_id = b.user_id and a.dt = b.base_date and a.bucket_id = b.bucket_id \
    left join( \
        select * from pay_metric_source where period = 13 \
    )c on a.user_id = c.user_id and a.dt = c.base_date and a.bucket_id = c.bucket_id \
    left join( \
        select * from gmv_metric_source where period = 13 \
    )d on a.user_id = d.user_id and a.dt = d.base_date and a.bucket_id = d.bucket_id \
    left join( \
        select * from visit_chat_metric_source where period = 13 \
    )f on a.user_id = f.user_id and a.dt = f.base_date \
    left join( \
        select * from visit_metric_source where period = 13 \
    )g on a.user_id = g.user_id and a.dt = g.base_date \
    left join( \
        select * from retain_visit_metric_source where period = 13 \
    )h on a.user_id = h.user_id and a.dt = h.base_date \
    left join( \
        select * from retain_metric_source where period = 13 \
    )i on a.user_id = i.user_id and a.dt = i.base_date \
union all \
    select a.dt as base_date,a.user_id as user_id, 29 as period,b.chat_rounds,b.chat_30_uv,b.chat_uv, \
        c.pay_uv,c.pay_money,d.gmv,null as roles_cnt,null as retain_uv,f.visit_chat_uv,g.visit_uv,null as retain_visit_uv,b.chat_10_uv \
        , a.exp_id, a.bucket_id, c.order_cnt, c.new_gift_package_pay_uv, c.new_gift_package_amount, c.new_gift_package_order_cnt, \
        c.old_gift_package_pay_uv, c.old_gift_package_amount, c.old_gift_package_order_cnt \
    from( \
        select dt,user_id, exp_id, bucket_id from device_fisrt_userid \
    )a \
    left join( \
        select * from talk_metric_source where period = 29 \
    )b on a.user_id = b.user_id and a.dt = b.base_date and a.bucket_id = b.bucket_id \
    left join( \
        select * from pay_metric_source where period = 29 \
    )c on a.user_id = c.user_id and a.dt = c.base_date and a.bucket_id = c.bucket_id \
    left join( \
        select * from gmv_metric_source where period = 29 \
    )d on a.user_id = d.user_id and a.dt = d.base_date and a.bucket_id = d.bucket_id \
    left join( \
        select * from visit_chat_metric_source where period = 29 \
    )f on a.user_id = f.user_id and a.dt = f.base_date \
    left join( \
        select * from visit_metric_source where period = 29 \
    )g on a.user_id = g.user_id and a.dt = g.base_date \
) \
where base_date <= date_sub('${azkaban.flow.1.days.ago}',period)
dependencies=dwd_ab_platform_exp_user_di