type=sparksql
hive.query.01=create temporary function resolve_tag_ip as 'com.netease.wm.udf.ResolveTagIp';
hive.query.02=insert overwrite table lofter_dm.ads_push_active_top1_photo_di partition(dt = '${azkaban.flow.current.date}') \
  select x.*, y.postId, y.blogId \
  from ( \
      select a.userId, a1.prefer_ip \
      from ( \
          select userId, \
                 nvl(sum(if(dt >= date_sub('${azkaban.flow.1.days.ago}', 6), 1, 0)),0) active_days_7d, \
                 count(1) active_days_30d \
          from lofter.dwd_user_active_di \
          where dt <= '${azkaban.flow.1.days.ago}' and dt >= date_sub('${azkaban.flow.1.days.ago}', 29) \
          group by 1 \
      ) a \
      join ( \
        select userId, element_at(top_ips,1) as prefer_ip \
        from lofter.dws_par_user_ip_prefer_dd \
        where dt = '${azkaban.flow.1.days.ago}' \
      ) a1 on a.userId = a1.userId \
      left join ( \
        select userId \
        from `lofter`.`ods_binlog_user_statistic_di` \
        where dt = '${azkaban.flow.current.date}' and `_bin_op` in (0,2) and \
          from_unixtime(cast(lastLoginTime/1000 as bigint), 'yyyy-MM-dd') = '${azkaban.flow.current.date}' \
        group by 1 \
      ) b on a.userId = b.userId \
      where a.active_days_30d > 0 and a.active_days_7d = 0 and b.userId is null \
  ) x \
  join ( \
      select x.* \
      from ( \
          select a.ip, a.postId, b.blogId, hot, row_number() over (partition by ip order by hot desc) as rk \
          from ( \
              select ip, postId, sum(hot_pv) as hot \
              from lofter.dws_post_interaction_di \
                   lateral view explode(resolve_tag_ip(post_tags)) as ip \
              where dt between date_sub('${azkaban.flow.1.days.ago}', 14) and '${azkaban.flow.1.days.ago}' and \
                    post_publish_date between date_sub('${azkaban.flow.1.days.ago}', 14) and '${azkaban.flow.1.days.ago}' \
              group by 1, 2 \
          ) a \
          join lofter.dim_post b on a.postId = b.id \
          where b.contentType = '图片' \
      ) x \
      left join lofter.dim_gift_post y on x.postId = y.postId \
      where y.postId is null and x.hot >= 50 and x.rk = 1 \
  ) y on x.prefer_ip = y.ip \
  left join ( \
      select * from lofter_dm.ads_push_active_top1_photo_di where dt < '${azkaban.flow.current.date}' \
  ) z on x.userId = z.userId and y.postId = z.postId \
  where z.postId is null \
