execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="select postId, blogId, nvl(positive_feedback_rate,0) as positiveFeedbackRate, nvl(interaction_rate,0) as interactionRate, nvl(follow_subscribe_uv,0) as followSubscribeUv, quality_type as qualityType, nvl(quality_score,0) as qualityScore, nvl(quality_desc, -1) as qualityDesc, type from lofter_dm.ads_paid_post_post_quality_dd where dt = '${azkaban.flow.1.days.ago}' "
params= --partition ${azkaban.flow.1.days.ago} --id postId --dest gift_post_quality --postfixsep --full --atom --url lofter-online-es1.gy.ntes:7000,lofter-online-es2.gy.ntes:7000,lofter-online-es3.gy.ntes:7000,lofter-online-es4.gy.ntes:7000 --username lofter_online --password Yi3DLCppSI
