package com.netease.wm.clickhouse

object clickhouseConfig {
  val hiveUrl = "jdbc:hive2://10.59.187.159:10001/;principal=da_lofter/dev@HADOOP.HZ.NETEASE.COM"
  val hiveDatabase = "lofter_dm"
  val clickHousePrefix = "jdbc:clickhouse://"
  val clickHouseSuffix = "/hive?socket_timeout=1000000"
  val clickHouseHost = List("lofter-data-common5.gy.ntes","lofter-data-common6.gy.ntes","lofter-data-common7.gy.ntes", "lofter-data-common8.gy.ntes", "lofter-data-common9.gy.ntes")
  val clickHouseTableHost = "lofter-data-common7.gy.ntes"
  val clickHouseViewHost = List("lofter-data-common5.gy.ntes","lofter-data-common6.gy.ntes", "lofter-data-common8.gy.ntes", "lofter-data-common9.gy.ntes")
  val clickHousePort = ":8123"
  val clickHousePassword = "O4nWNA9slAn8"
  val clickHouseUser = "lofter_rw"
  val clickHouseDriverName = "com.clickhouse.jdbc.ClickHouseDriver"
  val batchSize = 10000
  val parallelism = 10

  def getMasterClickhouseJdbcUrl: String = clickHousePrefix + clickHouseTableHost + clickHousePort + clickHouseSuffix
  def getSlaveClickhouseJdbcUrl: Seq[String] = clickHouseViewHost.map(host => clickHousePrefix + host + clickHousePort + clickHouseSuffix)

  val historyLoadJobs: Set[String] = Set(
    "ads_creator_gift_positive_feedback_rank_di", "ads_risk_induction_warn_posts_di", "ads_tag_rec_reason_di", "ads_specialty_user_consume_di",
    "ads_post_comment_vip_copy_di", "ads_risk_actpwd_similar_posts_di", "ads_cmb_ip_di", "ads_act_coupon_summer_holiday_user_group_dd",
    "ads_domain_daren_general_di", "ads_risk_induction_shuare_warn_di", "ads_mbo_revenue_marketing_di", "ads_risk_induction_block_blogs_di",
    "ads_rec_question_rec_reason_di", "ads_creator_support_score_rank_di", "ads_growth_content_di", "ads_post_comment_hot_list_di",
    "ads_antispam_dispose_dd", "ads_specialty_categories_post_1level_di", "ads_post_high_expose_di", "ads_growth_new_attribution_content_di",
    "ads_par_device_ecology_affinity_di", "ads_image_market_product_tag_dd", "ads_hot_search_list_di", "ads_ad_trace_source_device_detail_di",
    "ads_act_showcase_user_group_di", "ads_video_grab_strategy_dd", "ads_grain_batch_hot_list_di", "ads_risk_actpwd_post_footer_induction_di",
    "ads_mbo_revenue_dd", "ads_post_paid_creator_revenue_v2_di", "ads_creator_private_zone_conversion_di", "ads_push_group_di",
    "ads_growth_act_password_retain_di", "ads_specialty_creator_publish_di", "ads_risk_offsite_induction_zhihu_collection_di", "ads_fans_vip_invitation_di",
    "ads_creator_gift_support_score_user_rank_di", "ads_ip_traffic_sensing_percentile_di", "ads_gift_return_negative_di", "ads_domain_tag_rank_di",
    "ads_creator_benchmark_detail_di", "ads_rec_content_rec_reason_di", "ads_gift_ecology_rectify_limit_user_di", "ads_question_square_host_list_di",
    "ads_risk_induction_block_posts_di", "ads_par_user_subscribed_hot_tags_di", "ads_act_coupon_new_year_user_group_dd", "ads_creator_gift_tag_good_examples_di",
    "ads_ad_video_extend_user_group_di", "ads_risk_actpwd_comment_induction_di", "ads_suspect_hot_based_on_user_di",
    "ads_risk_induction_warn_blogs_di", "ads_creator_gift_level_change_di", "ads_search_collection_pool_di", "ads_gift_ecology_rectify_limit_post_di",
    "ads_ad_user_group_di", "ads_par_creator_rank_di", "ads_card_path_monitor_di", "ads_rec_content_rec_reason_detail_di", "ads_creator_vip_circle_privilege_di",
    "ads_act_pve_user_group_di", "ads_domain_general_di", "ads_miniprogram_post_hot_list_di", "ads_tag_discuss_hot_list_di", "ads_ip_yiyou_high_net_value_user_di",
    "ads_act_coupon_spring_user_group_dd", "ads_creator_create_subject_dd", "ads_post_trend_grade_di", "ads_creator_rec_reason_detail_di",
    "ads_rec_collection_rec_reason_detail_di", "ads_rev_gift_consume_dd", "ads_gift_post_induction_di", "ads_risk_shuare_warn_blogs_di", "ads_act_card_browse_dd",
    "ads_gift_post_similarity_di", "ads_user_black_low_quality_dd", "ads_search_word_top_di", "ads_grain_tag_list_di", "ads_tag_rec_reason_detail_di",
    "ads_ec_paid_subscribe_actpwd_funnel_di", "ads_creator_gift_open_entry_dd", "ads_search_keyword_rec_reason_detail_di",
    "ads_gift_bc_user_relation_di", "ads_rec_collection_rec_reason_di", "ads_growth_ad_period_cvr_di",
    "ads_creator_double_perspective_user_di", "ads_ec_market_product_dd", "ads_cc_question_top_di", "ads_cmb_tag_di", "ads_post_paid_creator_revenue_detail_di",
    "ads_act_music_interaction_present_di", "ads_mbo_revenue_content_di", "ads_device_platform_retain_di", "ads_bookstore_hot_list_di",
    "ads_creator_private_zone_premium_posts_di", "ads_ip_yiyou_traffic_limit_creator_di", "ads_blog_score_di", "ads_image_market_tag_stat_dd", "ads_tag_noncp_hot_top_di",
    "ads_rec_collection_user_follow_di", "ads_collection_search_hot_list_di", "ads_act_card_ip_gmv_dd", "ads_pve_user_interview_chat_days_di", "ads_search_tag_score_top_di",
    "ads_rec_collection_user_browse_di", "ads_par_device_ecology_scale_di", "ads_act_note_page_cvr_scene_di", "ads_grain_detail_dd", "ads_creator_active_fans_dd",
    "ads_act_pve_role_user_group_di", "ads_risk_shortlink_induction_posts_di", "ads_collection_noncp_praise_top_di", "ads_ec_gift_tag_order_index_di",
    "ads_post_paid_low_quality_creator_detail_di", "ads_mbo_ip_di", "ads_par_creator_post_aid_push_di", "ads_risk_actpwd_post_header_induction_di", "ads_user_interaction_di",
    "ads_daren_dd", "ads_gift_post_high_positive_vote_blogs_di", "ads_creator_representative_di", "ads_risk_post_ai_suspect_di",
    "ads_search_trend_hot_tag_di", "ads_post_interaction_di", "ads_user_tag_pay_dd", "ads_post_premium_monitor_di",
    "ads_device_platform_v2_di", "ads_act_paper_man_user_group_di", "ads_pve_user_chat_retain_di", "ads_video_audit_di", "ads_creator_private_zone_induction_di",
    "ads_creator_vip_fans_open_entry_dd", "ads_risk_rec_review_retrospect_di", "ads_pve_user_interview_di", "ads_content_ecology_di", "ads_mbo_revenue_user_di",
    "ads_rec_high_revenue_blogs_di", "ads_post_highlight_comment_top_di", "ads_backend_post_publish_di",
    "ads_par_user_ecology_content_consume_di", "ads_creator_idea_di", "ads_ec_product_category_trade_dd", "ads_act_coupon_daily_user_group_dd",
    "ads_search_password_device_retain_di", "ads_hot_search_list_di", "ads_creator_premium_detail_di", "ads_growth_content_monitor_di", "ads_ec_gift_order_index_di",
    "ads_creator_double_perspective_post_di", "ads_image_market_stat_dd", "ads_gift_return_hot_list_di", "ads_device_platform_di", "ads_post_paid_creator_revenue_di",
    "ads_creator_gift_support_score_rank_di", "ads_creator_rec_reason_di", "ads_risk_rec_audit_publish_monitor_di", "ads_risk_gr_blog_ia_di", "ads_pve_user_interview_retain_di",
    "ads_high_security_user_di", "ads_risk_shuare_model_stat_di", "ads_ec_user_streak_inactive_days_di", "ads_act_new_user_guide_cvr_di", "ads_growth_ad_material_notify_di",
    "ads_search_keyword_rec_reason_di", "ads_domain_subscribe_di", "ads_video_di", "ads_paid_gift_postid_no_income_di", "ads_creator_type_ebc_hd_monitor_di",
    "ads_paid_dress_emote_dd", "ads_fans_vip_monitor_di", "ads_ec_product_user_search_di", "ads_creator_monitor_mi", "ads_cc_module_di", "ads_ad_exp_click_report_di",
    "ads_growth_mau_destructure_duration_di", "ads_ip_potential_user_retain_di", "ads_content_monitor_fans_di", "dwb_hubble_app_general_di", "ads_ec_market_cvr_di",
    "ads_evt_paid_post_overall_dd", "ads_ip_supply_consume_interaction_di", "ads_gift_return_type_pv_di", "ads_activity_device_di", "ads_search_sug_cvr_di", "ads_ec_trace_cvr_di",
    "ads_paid_gift_user_income_di", "ads_ec_paid_subscribe_di", "ads_post_paid_retain_di", "ads_antispam_tag_suspect_di", "ads_tag_protection_exempt_di", "ads_card_home_path_monitor_di",
    "ads_creator_key_area_monitor_di", "ads_par_user_stratify_mi", "ads_ec_store_vip_contract_cancel_dd", "ads_ec_product_user_consume_di", "ads_ip_category_post_supply_di",
    "ads_ip_summary_di", "ads_antispam_callback_forbidtype_di", "ads_ad_device_collect_apk_di", "ads_video_external_link_hot_top_di", "ads_liaoliao_pvuv_based_on_source_di",
    "ads_rec_cvr_pt_di", "ads_ec_market_product_order_di", "ads_ec_coupon_card_di", "ads_ad_adtrace_monitor_di", "ads_paid_gift_postid_money_top1000_di",
    "ads_device_growth_dau_stratify_di", "ads_ec_product_trade_monitor_di", "ads_gift_return_scene_pv_di", "ads_ec_coupon_di", "ads_post_top_list_month_di", "ads_growth_device_di",
    "ads_paid_post_return_gift_feed_back_dd", "ads_device_appchannel_retain_di", "ads_ec_product_trade_retain_di", "ads_pve_user_active_trade_di", "ads_ip_interest_dau_di",
    "ads_activity_new_device_retain_di", "ads_paid_post_return_gift_feed_back_stats_di", "ads_act_lottery_path_di", "ads_evt_content_paid_hotsell_dd",
    "ads_domain_post_publish_by_content_type_di", "ads_post_paid_post_revenue_detail_di", "ads_creator_level_transition_week_di", "ads_antispam_copy_no_callback_di",
    "ads_creator_top_list_di", "ads_risk_offsite_induction_comment_di", "ads_risk_rec_audit_review_monitor_di", "ads_gift_apply_user_di", "ads_ip_interest_dau_retain_di",
    "ads_paid_gift_postid_money_from_blog_dd", "ads_domain_post_publish_di", "ads_ip_supply_demand_newuser_di", "ads_user_life_cycle_change_monitor_dd", "ads_content_monitor_hot_op_di",
    "ads_new_user_rec_post_wd", "ads_ec_coupon_benefit_di", "ads_collection_revisit_di", "ads_creator_monitor_domain_wi", "ads_card_sku_cvr_di", "ads_risk_inspection_record_di",
    "ads_post_top_list_day_di", "ads_ad_device_dsp_fill_fail_di", "ads_paid_image_market_dd", "ads_risk_offsite_induction_return_gift_di", "ads_ec_fans_vip_sku_trade_dd",
    "ads_creator_valid_detail_di", "ads_evt_content_supply_dd", "ads_ad_trade_user_free_gift_di", "ads_user_login_by_one_key_di", "ads_note_page_device_type_di",
    "ads_device_active_layer_active_days_1d_di", "ads_ec_store_vip_gross_profit_di", "ads_core_security_user_di", "ads_evt_post_paid_hotsell_dd", "ads_ip_potential_consum_user_retain_di",
    "ads_act_card_general_di", "ads_specialty_categories_post_2level_di", "ads_antispam_tag_unpass_rate_di", "ads_post_paid_scene_ip_action_detail_di",
    "ads_ec_book_store_growth_user_action_di", "ads_fans_vip_rev_period_di", "ads_post_tag_cover_monitor_di", "ads_growth_dau_destructure_duration_di",
    "ads_search_sug_word_cvr_di", "ads_ec_paid_subscribe_actpwd_di", "ads_growth_dau_stratify_di", "ads_ad_device_dsp_expose_di", "ads_ec_book_store_growth_user_di",
    "ads_ec_product_trade_di", "ads_tag_concurrency_wd", "ads_post_paid_monitor_v2_di", "ads_photo_frame_free_detail_stat_di", "ads_ad_new_linkup_detail_di",
    "ads_gift_return_type_detail_di", "ads_fans_vip_blog_detail_dd", "ads_cc_search_di", "ads_ec_store_vip_user_effective_dd", "ads_miniprogram_paid_order_actpwd_post_dd",
    "ads_paid_gift_postid_conv_di", "ads_creator_lighthouse_potential_di", "ads_video_tag_hot_top_di", "ads_gift_return_type_di", "ads_webview_pageurl_di", "ads_ip_potential_levelup_user_di",
    "ads_risk_offsite_induction_self_intro_di", "ads_growth_device_tag_retain_di", "ads_rec_retain_next_day_pt_di", "ads_post_paid_scene_ip_action_detail_v2_di",
    "ads_antispam_callback_monitor_stat_di", "ads_creator_level_transition_di", "ads_ec_paid_subscribe_actpwd_channel_funnel_di", "ads_creator_support_monitor_di",
    "ads_webview_pageurl_mpid_di", "ads_ad_device_startup_time_report_di", "ads_suit_reserve_pay_dd", "ads_rec_post_review_monitor_di", "ads_act_lottery_path_group_uv_di",
    "ads_ad_trade_equity_center_score_log_di", "ads_blog_monitor_qianfen_di", "ads_tag_supply_consume_interaction_di", "ads_risk_offsite_induction_content_di",
    "ads_creator_lighthouse_traffic_sensing_di", "ads_page_scene_di", "ads_liaoliao_active_remain_di", "ads_miniprogram_user_active_di", "ads_resource_traffic_value_di",
    "ads_user_life_cycle_uv_dd", "ads_ec_paid_subscribe_actpwd_channel_di", "ads_video_native_hot_top_di", "ads_domain_page_access_di", "ads_growth_device_tag_di",
    "ads_act_card_reward_exchange_inventory_consumption_dd", "ads_post_tag_cover_daily_di", "ads_growth_act_password_trade_di", "ads_rec_silent_user_di",
    "ads_ad_trade_equity_center_income_di", "ads_video_scene_di", "ads_creator_monitor_domain_mi", "ads_act_card_reward_exchange_di", "ads_collection_type_di",
    "ads_creator_level_monitor_di", "ads_collection_subscribe_top_di", "ads_photo_frame_charge_detail_stat_di", "ads_post_paid_user_consume_detail_di",
    "ads_par_user_stratify_di", "ads_suspect_hot_based_on_slider_di", "ads_growth_device_ip_retain_di", "ads_liaoliao_active_di", "ads_liaoliao_stat_based_on_optype_di",
    "ads_post_paid_user_consume_di", "ads_post_high_comment_dd", "ads_sdk_hybrid_loadtime_di", "ads_post_paid_monitor_di", "ads_paid_post_quality_score_value_di",
    "ads_creator_monitor_di", "ads_ip_potential_user_di", "ads_act_card_trace_di", "ads_ec_retain_trade_di", "ads_device_active_deviceos_monitor_di",
    "ads_drawing_expert_monitor_di", "ads_growth_device_ip_di", "ads_act_card_subscribe_dd", "ads_grain_summary_di", "ads_wmyzy_post_level1_monitor_di",
    "ads_ec_store_vip_channel_actpwd_silent_user_di", "ads_antispam_report_forbid_post_detail_di", "ads_liaoliao_module_monitor_di", "ads_user_interaction_level_monitor_di",
    "ads_ip_potential_device_active_7d_di", "ads_card_aggregation_monitor_di", "ads_growth_kol_promote_channel_di", "ads_par_user_ecology_di", "ads_ec_store_vip_sku_trade_dd",
    "ads_activity_callback_device_retain_di", "ads_rec_pending_humanreview_monitor_di", "ads_hubble_appchannel_session_di", "ads_collection_supply_demand_di", "ads_tag_interest_dau_di",
    "ads_ad_trade_equity_center_score_exchange_di", "ads_photo_frame_summary_stat_di", "ads_sdk_hybrid_white_screen_di", "ads_creator_first_publish_di", "ads_act_pve_ad_cvr_di",
    "ads_miniprogram_channel_launch_order_di", "ads_paid_post_consumption_di", "ads_ec_product_adtrace_activity_di", "ads_wmyzy_post_publish_di", "ads_suspect_hot_based_on_client_di",
    "ads_pve_user_dialogue_trade_dd", "ads_creator_lighthouse_support_blog_dd", "ads_image_market_loot_box_dd", "ads_specialty_categories_post_3level_di", "ads_growth_device_value_di",
    "ads_ad_growth_trade_di", "ads_domain_daren_active_di", "ads_pve_user_paid_retain_di", "ads_growth_device_retain_di", "ads_bookstore_apply_password_di", "ads_tag_interest_dau_retain_di",
    "ads_antispam_copy_post_type_stat_di", "ads_growth_proxy_quality_di", "ads_post_top_list_week_di", "ads_creator_monitor_wi", "ads_ec_store_vip_contract_order_di",
    "ads_wmyzy_post_monitor_di", "ads_ec_paid_subscribe_funnel_di", "ads_video_scene_next_day_play_di", "ads_par_user_core_monitor_di", "ads_creator_premium_monitor_di",
    "ads_card_distribution_monitor_dd", "ads_par_user_creator_month_report_di", "ads_par_user_stratify_wi", "ads_post_share_dd", "ads_post_score_di",
    "ads_risk_abnormal_blog_copy_link_di", "ads_ip_interest_type_di", "ads_growth_channel_dau_stratify_di", "ads_post_life_path_dd", "ads_ad_exp_click_di", "ads_talk_consume_retain_v1_di",
    "ads_talk_consume_retain_v2_di", "ads_userid_core_action_di", "ads_talk_publish_retain_di", "ads_talk_publish_di", "ads_user_interaction_v1_di", "ads_post_browser_info_di",
    "ads_ec_lofgoods_product_cvr_di", "ads_post_life_path_di", "ads_deviceudid_new_sum_ratio_dd", "ads_excellent_new_device_cnt_di", "ads_ip_life_cycle_type_info_dd",
    "ads_ip_life_cycle_type_dd", "ads_lofter_exp_click_checkout_di", "ads_search_to_click_article_hopper_di", "ads_search_hopper_di", "ads_post_audit_and_rec_all_di", "ads_post_audit_and_rec_detail_di",
    "ads_abnormal_low_score_user_query_stats_di", "ads_dangerous_user_monitor_stats_di", "ads_dangerous_user_ip_monitor_stats_di", "ads_abnormal_behavior_user_overall_stats_di",
    "ads_abnormal_behavior_user_detail_stats_di", "ads_abnormal_behavior_user_ip_stats_di", "ads_anti_risk_similarity_post_di", "ads_anti_risk_similarity_message_di", "ads_anti_risk_rule_stats_di",
    "ads_anti_risk_rule_group_stats_di", "ads_anti_risk_rule_detail_stats_di", "ads_anti_spam_audit_stats_di", "ads_anti_spam_post_time_interval_stats_di", "ads_anti_spam_operator_time_stats_di",
    "ads_anti_spam_operator_time_interval_stats_di", "ads_anti_spam_suspect_time_interval_stats_hour_di", "ads_anti_spam_summary_stats_di", "ads_anti_spam_hour_summary_stats_di",
    "ads_anti_spam_idle_send_detail_nd", "ads_anti_spam_idle_send_forbidden_blog_nd", "ads_anti_spam_idle_send_machine_audit_nd", "ads_anti_spam_idle_send_human_audit_nd",
    "ads_ec_market_page_cvr_pt_di", "ads_ec_market_trade_di", "ads_ec_market_trace_sale_cvr_di", "ads_ec_market_shelf_cvr_di", "ads_blog_gift_detail_stat_di", "ads_post_publish_by_content_type_di",
    "ads_creator_first_publish_active_remain_di", "ads_creator_first_publish_hot_remain_di", "ads_gift_send_stats_di", "ads_grain_hot_list_di", "ads_grain_hot_list_monthly_di",
    "dwb_user_nega_feed_stat_di", "ads_note_page_source_stat_di", "ads_operate_daren_video_detail_stat_di", "ads_video_source_stat_di", "ads_video_source_post_stat_di",
    "ads_post_audit_efficiency_monitor_stats_di", "ads_post_change_reason_stat_di", "ads_video_retain_realplay_di", "ads_risk_message_stats_di", "ads_live_charge_stats_di",
    "ads_anti_spam_whitelist_all_di", "ads_anti_spam_whitelist_detail_di", "ads_anti_spam_patrol_all_di", "ads_growth_content_view_di", "ads_finance_revenue_monitor_detail_di",
    "ads_grain_distribute_ip_category_list_di", "ads_recommend_marking_audit_detail_stats_di", "ads_recommend_marking_audit_all_stats_di", "ads_pve_user_chats_stats_di",
    "ads_ec_market_product_di", "ads_mbo_di", "ads_growth_arpu_view_v1_di", "ads_tag_fetch_tag_di", "ads_tag_fetch_ip_di", "ads_free_gift_rule_stats_di", "ads_gift_detail_stats_di",
    "ads_tag_fetch_post_di", "ads_user_grade_post_stat_di", "ads_growth_arpu_view_di", "ads_search_no_result_stats_di", "ads_search_click_result_stats_di",
    "ads_post_premium_detail_di", "ads_ue_user_order_di", "ads_ue_report_di", "ads_ue_user_base_dd", "ads_membership_finance_revenue_di",
    "ads_paid_post_all_vip_blog_postquality_detail_di","ads_paid_post_all_vip_overview_di","ads_paid_post_all_vip_search_paid_di","ads_paid_post_all_vip_search_paid_sku_detail_di","ads_paid_post_all_vip_subgroup_di",
    "ads_ad_content_revenue_di", "ads_ad_content_ad_post_detail_di", "ads_ad_content_collection_detail_di", "ads_ad_outer_income_split_di", "ads_device_daily_status_di", "ads_devicecnt_daily_di",
    "ads_growth_video_icloud_download_funnel_di"
  )
}
