SET pipeline.name = 'Mda2DorisJob';
SET table.exec.resource.default-parallelism = 16;
-- SET table.exec.sink.not-null-enforcer = 'drop';
SET restart-strategy = 'failure-rate';


CREATE TABLE ods_lofter_mda_online (
    eventId STRING,
    deviceUdid STRING,
    userId BIGINT,
    userType INT,
    userName STRING,
    appVersion STRING,
    appChannel STRING,
    occurTime BIGINT,
    category STRING,
    label STRING,
    customUDID STRING,
    sessionUuid STRING,
    ip STRING,
    devicePlatform STRING,
    deviceOs STRING,
    deviceOsVersion STRING,
    deviceModel STRING,
    deviceAdid STRING,
    deviceIdfv STRING,
    deviceIMEI STRING,
    deviceCarrier STRING,
    appKey STRING,
    city STRING,
    params MAP<STRING, STRING>,
    costTime BIGINT,
    source STRING,
    deviceAndroidId STRING,
    itemId STRING,
    itemType STRING,
    recId STRING,
    scene STRING,
    action STRING,
    tagName STRING,
    layout STRING,
    algInfo STRING,
    kafkaTime BIGINT,
    oaid STRING,
    isBeta STRING,
    tdid STRING
) WITH (
    'connector' = 'kafka',
    'topic' = 'lofter.mda.online',
    'properties.bootstrap.servers' = 'lofter-kafka-bi-risk1.gy.ntes:9092,lofter-kafka-bi-risk2.gy.ntes:9092,lofter-kafka-bi-risk3.gy.ntes:9092,lofter-kafka-bi-risk4.gy.ntes:9092,lofter-kafka-bi-risk5.gy.ntes:9092,lofter-kafka-bi-risk6.gy.ntes:9092,lofter-kafka-bi-risk7.gy.ntes:9092,lofter-kafka-bi-risk8.gy.ntes:9092',
    'properties.group.id' = 'Mda2DorisJob',
    'scan.startup.mode' = 'latest-offset',
    'scan.topic-partition-discovery.interval' = '2min',
    'format' = 'avro'
);


CREATE TABLE ods_lofter_mda_online_di (
    dt DATE NOT NULL,
    eventId STRING,
    deviceUdid STRING,
    userId BIGINT,
    userType INT,
    userName STRING,
    appVersion STRING,
    appChannel STRING,
    occurTime BIGINT,
    category STRING,
    label STRING,
    customUDID STRING,
    sessionUuid STRING,
    ip STRING,
    devicePlatform STRING,
    deviceOs STRING,
    deviceOsVersion STRING,
    deviceModel STRING,
    deviceAdid STRING,
    deviceIdfv STRING,
    deviceIMEI STRING,
    deviceCarrier STRING,
    appKey STRING,
    city STRING,
    costTime BIGINT,
    deviceAndroidId STRING,
    itemId STRING,
    itemType STRING,
    recId STRING,
    scene STRING,
    action STRING,
    tagName STRING,
    layout STRING,
    algInfo STRING,
    kafkaTime BIGINT,
    oaid STRING,
    isBeta STRING,
    tdid STRING
) WITH (
    'connector' = 'doris',
    'fenodes' = 'lofter-doris-1.gy.ntes:8030,lofter-doris-2.gy.ntes:8030,lofter-doris-3.gy.ntes:8030',
    'table.identifier' = 'lofter.ods_lofter_mda_online_di',
    'username' = 'doris_rw',
    'password' = 'Fkhike8A',
    'sink.properties.format' = 'json',
    'sink.batch.interval' = '60000',
    'sink.batch.bytes' = '805306368',
    'sink.batch.size' = '2000000',
    'sink.properties.read_json_by_line' = 'true',
    'sink.properties.strip_outer_array' = 'true',
    'sink.doris.key.fields' = 'dt,eventId,deviceUdid',
    'sink.parallelism' = '-1',
    'jdbc-url' = 'jdbc:mysql://music-doris-das.service.gy.ntes:6040'
);


INSERT INTO ods_lofter_mda_online_di
SELECT TO_DATE(FROM_UNIXTIME(CAST(`kafkaTime` / 1000 AS BIGINT), 'yyyy-MM-dd')) AS dt,
       eventId,
       deviceUdid,
       userId,
       userType,
       userName,
       appVersion,
       appChannel,
       occurTime,
       category,
       label,
       customUDID,
       sessionUuid,
       ip,
       devicePlatform,
       deviceOs,
       deviceOsVersion,
       deviceModel,
       deviceAdid,
       deviceIdfv,
       deviceIMEI,
       deviceCarrier,
       appKey,
       city,
       costTime,
       deviceAndroidId,
       itemId,
       itemType,
       recId,
       scene,
       action,
       tagName,
       layout,
       algInfo,
       kafkaTime,
       oaid,
       isBeta,
       tdid
FROM ods_lofter_mda_online;


/* -- Doris DDL

CREATE TABLE `lofter`.`ods_lofter_mda_online_di` (
  `dt` date NOT NULL,
  `eventId` char(128) NULL,
  `deviceUdid` char(64) NULL,
  `userId` bigint NULL,
  `userType` int NULL,
  `userName` varchar(64) NULL,
  `appVersion` varchar(64) NULL,
  `appChannel` varchar(64) NULL,
  `occurTime` bigint NULL,
  `category` varchar(64) NULL,
  `label` varchar(64) NULL,
  `customUDID` varchar(64) NULL,
  `sessionUuid` varchar(64) NULL,
  `ip` varchar(64) NULL,
  `devicePlatform` varchar(32) NULL,
  `deviceOs` varchar(16) NULL,
  `deviceOsVersion` varchar(64) NULL,
  `deviceModel` varchar(64) NULL,
  `deviceAdid` varchar(64) NULL,
  `deviceIdfv` varchar(64) NULL,
  `deviceIMEI` varchar(32) NULL,
  `deviceCarrier` varchar(128) NULL,
  `appKey` varchar(32) NULL,
  `city` varchar(64) NULL,
  `costTime` bigint NULL,
  `deviceAndroidId` varchar(32) NULL,
  `itemId` varchar(1024) NULL,
  `itemType` varchar(64) NULL,
  `recId` varchar(256) NULL,
  `scene` varchar(64) NULL,
  `action` varchar(16) NULL,
  `tagName` varchar(256) NULL,
  `layout` varchar(16) NULL,
  `algInfo` varchar(1024) NULL,
  `kafkaTime` bigint NULL,
  `oaid` varchar(128) NULL,
  `isBeta` varchar(4) NULL,
  `tdid` varchar(256) NULL
) ENGINE=OLAP
DUPLICATE KEY(`dt`, `eventId`, `deviceUdid`)
COMMENT 'owner:zhaozijun03@corp.netease.com'
AUTO PARTITION BY RANGE (date_trunc(`dt`, 'day')) ()
DISTRIBUTED BY HASH(`eventId`, `deviceUdid`) BUCKETS 64
PROPERTIES (
  "dynamic_partition.time_unit" = "DAY",
  "dynamic_partition.start" = "-30",
  "dynamic_partition.end" = "2",
  "dynamic_partition.create_history_partition" = "false",
  "dynamic_partition.enable" = "true",
  "dynamic_partition.prefix" = "p",
  "dynamic_partition.replication_allocation" = "tag.location.default: 3",
  "dynamic_partition.time_zone" = "Asia/Shanghai",
  "replication_allocation" = "tag.location.default: 3",
  "light_schema_change" = "true",
  "compression" = "zstd"
);

*/