SET pipeline.name = 'Wda2DorisJob';
SET table.exec.resource.default-parallelism = 4;
-- SET table.exec.sink.not-null-enforcer = 'drop';
SET restart-strategy = 'failure-rate';


CREATE TABLE ods_lofter_wap_online_di (
    eventId STRING,
    deviceUdid STRING,
    urlPath STRING,
    userId BIGINT,
    region STRING,
    screenHeight INT,
    browserVersion STRING,
    referrerDomain STRING,
    kafkaTime BIGINT,
    secondLevelSource STRING,
    data STRING,
    deviceModel STRING,
    devicePlatform STRING,
    ipCity STRING,
    hubbleId STRING,
    city STRING,
    `timestamp` STRING,
    occurTime BIGINT,
    activationTime STRING,
    processTime STRING,
    serverTime STRING,
    browser STRING,
    deviceOs STRING,
    ipCountry STRING,
    currentUrl STRING,
    deviceOsVersion STRING,
    currentDomain STRING,
    country STRING,
    ip STRING,
    referrer STRING,
    datatype STRING,
    productKey STRING,
    sessionUuid STRING,
    screenWidth INT,
    pageTitle STRING,
    appChannel STRING,
    pageOpenScene STRING,
    firstLevelSource STRING,
    ipProvince STRING,
    appKey STRING,
    costTime BIGINT,
    attributes MAP<STRING, STRING>,
    useragent STRING
) WITH (
    'connector' = 'kafka',
    'topic' = 'lofter.wap.online',
    'properties.bootstrap.servers' = 'lofter-kafka-bi-risk1.gy.ntes:9092,lofter-kafka-bi-risk2.gy.ntes:9092,lofter-kafka-bi-risk3.gy.ntes:9092,lofter-kafka-bi-risk4.gy.ntes:9092,lofter-kafka-bi-risk5.gy.ntes:9092,lofter-kafka-bi-risk6.gy.ntes:9092,lofter-kafka-bi-risk7.gy.ntes:9092,lofter-kafka-bi-risk8.gy.ntes:9092',
    'properties.group.id' = 'Wda2DorisJob',
    'scan.startup.mode' = 'latest-offset',
    'scan.topic-partition-discovery.interval' = '2min',
    'format' = 'avro'
);

CREATE TABLE ods_lofter_web_online_di (
    eventId STRING,
    deviceUdid STRING,
    urlPath STRING,
    userId BIGINT,
    region STRING,
    screenHeight INT,
    browserVersion STRING,
    referrerDomain STRING,
    kafkaTime BIGINT,
    secondLevelSource STRING,
    data STRING,
    deviceModel STRING,
    devicePlatform STRING,
    ipCity STRING,
    hubbleId STRING,
    city STRING,
    `timestamp` STRING,
    occurTime BIGINT,
    activationTime STRING,
    processTime STRING,
    serverTime STRING,
    browser STRING,
    deviceOs STRING,
    ipCountry STRING,
    currentUrl STRING,
    deviceOsVersion STRING,
    currentDomain STRING,
    country STRING,
    ip STRING,
    referrer STRING,
    datatype STRING,
    productKey STRING,
    sessionUuid STRING,
    screenWidth INT,
    pageTitle STRING,
    appChannel STRING,
    pageOpenScene STRING,
    firstLevelSource STRING,
    ipProvince STRING,
    appKey STRING,
    costTime BIGINT,
    attributes MAP<STRING, STRING>,
    useragent STRING
) WITH (
    'connector' = 'kafka',
    'topic' = 'lofter.web.online',
    'properties.bootstrap.servers' = 'lofter-kafka-bi-risk1.gy.ntes:9092,lofter-kafka-bi-risk2.gy.ntes:9092,lofter-kafka-bi-risk3.gy.ntes:9092,lofter-kafka-bi-risk4.gy.ntes:9092,lofter-kafka-bi-risk5.gy.ntes:9092,lofter-kafka-bi-risk6.gy.ntes:9092,lofter-kafka-bi-risk7.gy.ntes:9092,lofter-kafka-bi-risk8.gy.ntes:9092',
    'properties.group.id' = 'Wda2DorisJob',
    'scan.startup.mode' = 'latest-offset',
    'scan.topic-partition-discovery.interval' = '2min',
    'format' = 'avro'
);


CREATE TABLE ods_lofter_wda_online_di (
    dt DATE NOT NULL,
    platform STRING,
    dataType STRING,
    appKey STRING,
    deviceUdid STRING,
    devicePlatform STRING,
    deviceOs STRING,
    deviceOsVersion STRING,
    deviceModel STRING,
    sessionUuid STRING,
    eventId STRING,
    occurTime BIGINT,
    costTime BIGINT,
    userId BIGINT,
    attributes STRING,
    ip STRING,
    `timestamp` BIGINT,
    kafkaTime BIGINT,
    urlPath STRING,
    currentUrl STRING,
    referrer STRING,
    referrerDomain STRING,
    browser STRING,
    browserVersion STRING,
    currentDomain STRING,
    region STRING,
    screenHeight INT,
    screenWidth INT,
    firstLevelSource STRING,
    secondLevelSource STRING,
    pageTitle STRING,
    pageOpenScene STRING
) WITH (
    'connector' = 'doris',
    'fenodes' = 'lofter-doris-1.gy.ntes:8030,lofter-doris-2.gy.ntes:8030,lofter-doris-3.gy.ntes:8030',
    'table.identifier' = 'lofter.ods_lofter_wda_online_di',
    'username' = 'doris_rw',
    'password' = 'Fkhike8A',
    'sink.properties.format' = 'json',
    'sink.batch.interval' = '60000',
    'sink.batch.bytes' = '805306368',
    'sink.batch.size' = '2000000',
    'sink.properties.read_json_by_line' = 'true',
    'sink.properties.strip_outer_array' = 'true',
    'sink.doris.key.fields' = 'dt,eventId,deviceUdid',
    'sink.parallelism' = '-1',
    'jdbc-url' = 'jdbc:mysql://music-doris-das.service.gy.ntes:6040'
);


INSERT INTO ods_lofter_wda_online_di
SELECT TO_DATE(FROM_UNIXTIME(CAST(`kafkaTime` / 1000 AS BIGINT), 'yyyy-MM-dd')) as dt,
       'wap' AS platform,
       datatype AS dataType,
       appKey,
       deviceUdid,
       devicePlatform,
       deviceOs,
       deviceOsVersion,
       deviceModel,
       sessionUuid,
       eventId,
       occurTime,
       costTime,
       userId,
       JSON_STRING(attributes) AS attributes,
       ip,
       CAST(`timestamp` AS BIGINT) AS `timestamp`,
       kafkaTime,
       urlPath,
       currentUrl,
       referrer,
       referrerDomain,
       browser,
       browserVersion,
       currentDomain,
       region,
       screenHeight,
       screenWidth,
       firstLevelSource,
       secondLevelSource,
       pageTitle,
       pageOpenScene
FROM ods_lofter_wap_online_di
UNION ALL
SELECT TO_DATE(FROM_UNIXTIME(CAST(`kafkaTime` / 1000 AS BIGINT), 'yyyy-MM-dd')) as dt,
       'web' AS platform,
       datatype AS dataType,
       appKey,
       deviceUdid,
       devicePlatform,
       deviceOs,
       deviceOsVersion,
       deviceModel,
       sessionUuid,
       eventId,
       occurTime,
       costTime,
       userId,
       JSON_STRING(attributes) AS attributes,
       ip,
       CAST(`timestamp` AS BIGINT) AS `timestamp`,
       kafkaTime,
       urlPath,
       currentUrl,
       referrer,
       referrerDomain,
       browser,
       browserVersion,
       currentDomain,
       region,
       screenHeight,
       screenWidth,
       firstLevelSource,
       secondLevelSource,
       pageTitle,
       pageOpenScene
FROM ods_lofter_web_online_di;


/* -- Doris DDL

CREATE TABLE lofter.ods_lofter_wda_online_di
(
    `dt` DATE NOT NULL COMMENT '分区日期',
    `eventId` char(128) NULL,
    `deviceUdid` char(64) NULL,
    `platform` CHAR(32) NULL,
    `dataType` VARCHAR(64) NULL,
    `appKey` varchar(32) NULL,
    `kafkaTime` BIGINT NULL,
    `devicePlatform` varchar(32) NULL,
    `deviceOs` varchar(16) NULL,
    `deviceOsVersion` varchar(64) NULL,
    `deviceModel` varchar(128) NULL,
    `sessionUuid` varchar(64) NULL,
    `occurTime` BIGINT NULL,
    `costTime` BIGINT NULL,
    `userId` BIGINT NULL,
    `attributes` VARCHAR(8192) NULL,
    `ip` VARCHAR(64) NULL,
    `timestamp` BIGINT NULL,;lp
    `urlPath` VARCHAR(256) NULL,
    `currentUrl` VARCHAR(512) NULL,
    `referrer` VARCHAR(256) NULL,
    `referrerDomain` VARCHAR(64) NULL,
    `browser` VARCHAR(32) NULL,
    `browserVersion` VARCHAR(64),
    `currentDomain` VARCHAR(128) NULL,
    `region` VARCHAR(64) NULL,
    `screenHeight` INT NULL,
    `screenWidth` INT NULL,
    `firstLevelSource` VARCHAR(256) NULL,
    `secondLevelSource` VARCHAR(256) NULL,
    `pageTitle` VARCHAR(1024) NULL,
    `pageOpenScene` VARCHAR(128) NULL
)
ENGINE = OLAP
DUPLICATE KEY(`dt`, `eventId`, `deviceUdid`, `platform`)
COMMENT 'owner:zhaozijun03@corp.netease.com'
AUTO PARTITION BY RANGE (date_trunc(`dt`, 'day')) ()
DISTRIBUTED BY HASH(`eventId`, `deviceUdid`, `platform`) BUCKETS 16
PROPERTIES (
  "dynamic_partition.time_unit" = "DAY",
  "dynamic_partition.start" = "-30",
  "dynamic_partition.end" = "2",
  "dynamic_partition.create_history_partition" = "false",
  "dynamic_partition.enable" = "true",
  "dynamic_partition.prefix" = "p",
  "dynamic_partition.replication_allocation" = "tag.location.default: 3",
  "dynamic_partition.time_zone" = "Asia/Shanghai",
  "replication_allocation" = "tag.location.default: 3",
  "light_schema_change" = "true",
  "compression" = "zstd"
);

*/

