execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="select concat_ws('-', flowTaskId, flowTaskType, postId,translate(dt,'-','')) as id, dt, flowTaskId, flowTaskType, postId,userId,contentType,firstTag,secondTag,thirdTag,publishDate,enterRecDate,exposurePv,exposureUv,clickPv,clickUv,posHotPv, hdUv,browseUv,realPlayPv,finishPlayRatio,realFinishPlayRatio, newUvConsumeRatio from lofter_dm.ads_rec_dis_post_di where  dt='${azkaban.flow.1.days.ago}'"
params= --partition ${azkaban.flow.1.days.ago} --dest lofter_rec_dis_detail_v2 --postfixsep --atom
dependencies=flow_control_effect_by_post
