execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="select concat_ws('-',flowTaskId,flowTaskType, userId) as id,dt,flowTaskId, flowTaskType,userId,blogNickName,level1Category,creatorLevel, fansAcc,hdFansAcc,darenFlag,exposurePv,exposureUv,clickPv,clickUv,realPlayPv,realPlayUv,hotPv,hotUv,pvClickRate,uvClickRate,realPlayRate,hdUv,browseUv, supportPostCount, sensingUserCount as pushUserNumb, sensingItemCount as pushItemNumb from lofter_dm.ads_rec_dis_task_user_acc_di where dt='${azkaban.flow.1.days.ago}'"
params= --partition ${azkaban.flow.1.days.ago} --dest lofter_rec_dis_user_acc_v2 --postfixsep --atom
dependencies=flow_control_effect_by_task_user
