mysql.jdbc.driver=com.mysql.jdbc.Driver
mysql.lofter.db.jdbc.url=jdbc:mysql://lofter-online-jd-qs-29.ddb.cn-east-p1.internal.:6000/public_mirror?user=lofter_bi&password=WndkIpgkr&characterEncoding=utf8&connectTimeout=5000&socketTimeout=1800000
mysql.lofter.mall.db.jdbc.url=jdbc:mysql://lofter-online-jd-qs-21.ddb.cn-east-p1.internal.:6000,lofter-online-jd-qs-22.ddb.cn-east-p1.internal.:6000,lofter-online-jd-qs-23.ddb.cn-east-p1.internal.:6000/mall_online?user=lofter_bi&password=WndkIpgkr&characterEncoding=utf8&connectTimeout=5000&socketTimeout=1800000
mysql.lofter.rec.db.jdbc.url=jdbc:mysql://lofter-rds-common-recomment-mirror-jd-27427.rds.cn-east-p1.internal.:3331/recomment?useUnicode=true&characterEncoding=UTF-8&user=lofter_bi&password=mBESHdBRr&characterEncoding=utf8&connectTimeout=5000&socketTimeout=1800000
mysql.lofter.db.jdbc.url.test=jdbc:mysql://10.57.60.11:6000,10.57.60.12:6000/public?user=public_test&password=eThNXWMVirg&connectTimeout=5000&socketTimeout=1800000&characterEncoding=utf-8

clickhouse.jdbc.driver=com.clickhouse.jdbc.ClickHouseDriver
clickhouse.data.jdbc.url=jdbc:clickhouse://lofter-clickhouse2.jd.163.org:8123/lofter?socket_timeout=1000000
clickhouse.data.jdbc.user=lofter_rw
clickhouse.data.jdbc.password=O4nWNA9slAn8

kafka.bootstrap.servers.backend=lofter-dc-kafka4.service.163.org:9092,lofter-dc-kafka5.service.163.org:9092,lofter-dc-kafka6.service.163.org:9092
kafka.bootstrap.servers.rec=lofter-kafka0.service.163.org:9093,lofter-kafka1.service.163.org:9093,lofter-kafka2.service.163.org:9093
kafka.bootstrap.servers=lofter-kafka3.service.163.org:9092,lofter-kafka4.service.163.org:9092,lofter-kafka5.service.163.org:9092
kafka.bootstrap.servers.backend.test=10.189.176.81:9092,10.189.176.81:9093,10.189.176.81:9094
kafka.bootstrap.servers.rec.test=10.196.9.102:9092,10.196.9.102:9093,10.196.9.102:9094

kafka.rec.rec_action_topic=rec_upload_action
kafka.rec.rec_action_parse_topic=rec_upload_action_parse
kafka.rec.rec_request_topic=rec_ds_rec_log
kafka.rec.rec_question_reason_topic=rec_bdms_question_reason

kafka.lofter.binlog_ndc_topic=lofter.binlog.ndc
kafka.lofter.backend_common_topic=lofter.common.businessData
kafka.lofter.pve_role_rank_topic=LOFTER.PVEMAN.rolerank

kafka.lofter.dwd_binlog_ndc_topic=lofter.dwd_binlog_ndc
kafka.lofter.dwd_rec_action_topic=lofter.dwd_rec_action
kafka.lofter.dwd_rec_action_label_topic=lofter.dwd_rec_action_label
kafka.lofter.dwd_rec_request_topic=lofter.dwd_rec_request
kafka.lofter.dws_rec_request_and_action_label_topic=lofter.dws_rec_request_and_action_label