/**
 * Autogenerated by Avro
 *
 * DO NOT EDIT DIRECTLY
 */
package com.netease.wm.hubble.avro;

import org.apache.avro.generic.GenericArray;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.SchemaStore;

@org.apache.avro.specific.AvroGenerated
public class AdxDspEvent extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  private static final long serialVersionUID = 6374849380434511393L;


  public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"AdxDspEvent\",\"namespace\":\"com.netease.wm.hubble.avro\",\"fields\":[{\"name\":\"adId\",\"type\":\"string\"},{\"name\":\"appId\",\"type\":\"string\"},{\"name\":\"dspId\",\"type\":\"string\"},{\"name\":\"os\",\"type\":\"string\"},{\"name\":\"positionId\",\"type\":\"string\"},{\"name\":\"positionName\",\"type\":\"string\"},{\"name\":\"success\",\"type\":\"int\"},{\"name\":\"requestTime\",\"type\":[\"null\",\"long\"]},{\"name\":\"responseTime\",\"type\":[\"null\",\"long\"]},{\"name\":\"msg\",\"type\":\"string\"},{\"name\":\"externalAdId\",\"type\":[\"null\",\"string\"]},{\"name\":\"ip\",\"type\":[\"null\",\"string\"]},{\"name\":\"wakeupBoot\",\"type\":\"int\"},{\"name\":\"winFlag\",\"type\":[\"null\",\"int\"]},{\"name\":\"la\",\"type\":[\"null\",\"string\"]},{\"name\":\"lo\",\"type\":[\"null\",\"string\"]},{\"name\":\"version\",\"type\":[\"null\",\"string\"]},{\"name\":\"uuid\",\"type\":[\"null\",\"string\"]},{\"name\":\"banwords\",\"type\":[\"null\",\"string\"]},{\"name\":\"reqId\",\"type\":[\"null\",\"string\"]},{\"name\":\"industryId\",\"type\":[\"null\",\"string\"]},{\"name\":\"slotId\",\"type\":[\"null\",\"string\"]},{\"name\":\"advertiser_type\",\"type\":[\"null\",\"string\"]},{\"name\":\"price\",\"type\":[\"null\",\"double\"]},{\"name\":\"blogId\",\"type\":[\"null\",\"long\"]},{\"name\":\"bidFactor\",\"type\":[\"null\",\"double\"]},{\"name\":\"ext\",\"type\":{\"type\":\"map\",\"values\":\"string\",\"default\":null}}]}");
  public static org.apache.avro.Schema getClassSchema() { return SCHEMA$; }

  private static final SpecificData MODEL$ = new SpecificData();

  private static final BinaryMessageEncoder<AdxDspEvent> ENCODER =
      new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

  private static final BinaryMessageDecoder<AdxDspEvent> DECODER =
      new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

  /**
   * Return the BinaryMessageEncoder instance used by this class.
   * @return the message encoder used by this class
   */
  public static BinaryMessageEncoder<AdxDspEvent> getEncoder() {
    return ENCODER;
  }

  /**
   * Return the BinaryMessageDecoder instance used by this class.
   * @return the message decoder used by this class
   */
  public static BinaryMessageDecoder<AdxDspEvent> getDecoder() {
    return DECODER;
  }

  /**
   * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
   * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
   * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
   */
  public static BinaryMessageDecoder<AdxDspEvent> createDecoder(SchemaStore resolver) {
    return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
  }

  /**
   * Serializes this AdxDspEvent to a ByteBuffer.
   * @return a buffer holding the serialized data for this instance
   * @throws java.io.IOException if this instance could not be serialized
   */
  public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
    return ENCODER.encode(this);
  }

  /**
   * Deserializes a AdxDspEvent from a ByteBuffer.
   * @param b a byte buffer holding serialized data for an instance of this class
   * @return a AdxDspEvent instance decoded from the given buffer
   * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
   */
  public static AdxDspEvent fromByteBuffer(
      java.nio.ByteBuffer b) throws java.io.IOException {
    return DECODER.decode(b);
  }

  private java.lang.CharSequence adId;
  private java.lang.CharSequence appId;
  private java.lang.CharSequence dspId;
  private java.lang.CharSequence os;
  private java.lang.CharSequence positionId;
  private java.lang.CharSequence positionName;
  private int success;
  private java.lang.Long requestTime;
  private java.lang.Long responseTime;
  private java.lang.CharSequence msg;
  private java.lang.CharSequence externalAdId;
  private java.lang.CharSequence ip;
  private int wakeupBoot;
  private java.lang.Integer winFlag;
  private java.lang.CharSequence la;
  private java.lang.CharSequence lo;
  private java.lang.CharSequence version;
  private java.lang.CharSequence uuid;
  private java.lang.CharSequence banwords;
  private java.lang.CharSequence reqId;
  private java.lang.CharSequence industryId;
  private java.lang.CharSequence slotId;
  private java.lang.CharSequence advertiser_type;
  private java.lang.Double price;
  private java.lang.Long blogId;
  private java.lang.Double bidFactor;
  private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> ext;

  /**
   * Default constructor.  Note that this does not initialize fields
   * to their default values from the schema.  If that is desired then
   * one should use <code>newBuilder()</code>.
   */
  public AdxDspEvent() {}

  /**
   * All-args constructor.
   * @param adId The new value for adId
   * @param appId The new value for appId
   * @param dspId The new value for dspId
   * @param os The new value for os
   * @param positionId The new value for positionId
   * @param positionName The new value for positionName
   * @param success The new value for success
   * @param requestTime The new value for requestTime
   * @param responseTime The new value for responseTime
   * @param msg The new value for msg
   * @param externalAdId The new value for externalAdId
   * @param ip The new value for ip
   * @param wakeupBoot The new value for wakeupBoot
   * @param winFlag The new value for winFlag
   * @param la The new value for la
   * @param lo The new value for lo
   * @param version The new value for version
   * @param uuid The new value for uuid
   * @param banwords The new value for banwords
   * @param reqId The new value for reqId
   * @param industryId The new value for industryId
   * @param slotId The new value for slotId
   * @param advertiser_type The new value for advertiser_type
   * @param price The new value for price
   * @param blogId The new value for blogId
   * @param bidFactor The new value for bidFactor
   * @param ext The new value for ext
   */
  public AdxDspEvent(java.lang.CharSequence adId, java.lang.CharSequence appId, java.lang.CharSequence dspId, java.lang.CharSequence os, java.lang.CharSequence positionId, java.lang.CharSequence positionName, java.lang.Integer success, java.lang.Long requestTime, java.lang.Long responseTime, java.lang.CharSequence msg, java.lang.CharSequence externalAdId, java.lang.CharSequence ip, java.lang.Integer wakeupBoot, java.lang.Integer winFlag, java.lang.CharSequence la, java.lang.CharSequence lo, java.lang.CharSequence version, java.lang.CharSequence uuid, java.lang.CharSequence banwords, java.lang.CharSequence reqId, java.lang.CharSequence industryId, java.lang.CharSequence slotId, java.lang.CharSequence advertiser_type, java.lang.Double price, java.lang.Long blogId, java.lang.Double bidFactor, java.util.Map<java.lang.CharSequence,java.lang.CharSequence> ext) {
    this.adId = adId;
    this.appId = appId;
    this.dspId = dspId;
    this.os = os;
    this.positionId = positionId;
    this.positionName = positionName;
    this.success = success;
    this.requestTime = requestTime;
    this.responseTime = responseTime;
    this.msg = msg;
    this.externalAdId = externalAdId;
    this.ip = ip;
    this.wakeupBoot = wakeupBoot;
    this.winFlag = winFlag;
    this.la = la;
    this.lo = lo;
    this.version = version;
    this.uuid = uuid;
    this.banwords = banwords;
    this.reqId = reqId;
    this.industryId = industryId;
    this.slotId = slotId;
    this.advertiser_type = advertiser_type;
    this.price = price;
    this.blogId = blogId;
    this.bidFactor = bidFactor;
    this.ext = ext;
  }

  @Override
  public org.apache.avro.specific.SpecificData getSpecificData() { return MODEL$; }

  @Override
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }

  // Used by DatumWriter.  Applications should not call.
  @Override
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return adId;
    case 1: return appId;
    case 2: return dspId;
    case 3: return os;
    case 4: return positionId;
    case 5: return positionName;
    case 6: return success;
    case 7: return requestTime;
    case 8: return responseTime;
    case 9: return msg;
    case 10: return externalAdId;
    case 11: return ip;
    case 12: return wakeupBoot;
    case 13: return winFlag;
    case 14: return la;
    case 15: return lo;
    case 16: return version;
    case 17: return uuid;
    case 18: return banwords;
    case 19: return reqId;
    case 20: return industryId;
    case 21: return slotId;
    case 22: return advertiser_type;
    case 23: return price;
    case 24: return blogId;
    case 25: return bidFactor;
    case 26: return ext;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  // Used by DatumReader.  Applications should not call.
  @Override
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: adId = (java.lang.CharSequence)value$; break;
    case 1: appId = (java.lang.CharSequence)value$; break;
    case 2: dspId = (java.lang.CharSequence)value$; break;
    case 3: os = (java.lang.CharSequence)value$; break;
    case 4: positionId = (java.lang.CharSequence)value$; break;
    case 5: positionName = (java.lang.CharSequence)value$; break;
    case 6: success = (java.lang.Integer)value$; break;
    case 7: requestTime = (java.lang.Long)value$; break;
    case 8: responseTime = (java.lang.Long)value$; break;
    case 9: msg = (java.lang.CharSequence)value$; break;
    case 10: externalAdId = (java.lang.CharSequence)value$; break;
    case 11: ip = (java.lang.CharSequence)value$; break;
    case 12: wakeupBoot = (java.lang.Integer)value$; break;
    case 13: winFlag = (java.lang.Integer)value$; break;
    case 14: la = (java.lang.CharSequence)value$; break;
    case 15: lo = (java.lang.CharSequence)value$; break;
    case 16: version = (java.lang.CharSequence)value$; break;
    case 17: uuid = (java.lang.CharSequence)value$; break;
    case 18: banwords = (java.lang.CharSequence)value$; break;
    case 19: reqId = (java.lang.CharSequence)value$; break;
    case 20: industryId = (java.lang.CharSequence)value$; break;
    case 21: slotId = (java.lang.CharSequence)value$; break;
    case 22: advertiser_type = (java.lang.CharSequence)value$; break;
    case 23: price = (java.lang.Double)value$; break;
    case 24: blogId = (java.lang.Long)value$; break;
    case 25: bidFactor = (java.lang.Double)value$; break;
    case 26: ext = (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>)value$; break;
    default: throw new IndexOutOfBoundsException("Invalid index: " + field$);
    }
  }

  /**
   * Gets the value of the 'adId' field.
   * @return The value of the 'adId' field.
   */
  public java.lang.CharSequence getAdId() {
    return adId;
  }


  /**
   * Sets the value of the 'adId' field.
   * @param value the value to set.
   */
  public void setAdId(java.lang.CharSequence value) {
    this.adId = value;
  }

  /**
   * Gets the value of the 'appId' field.
   * @return The value of the 'appId' field.
   */
  public java.lang.CharSequence getAppId() {
    return appId;
  }


  /**
   * Sets the value of the 'appId' field.
   * @param value the value to set.
   */
  public void setAppId(java.lang.CharSequence value) {
    this.appId = value;
  }

  /**
   * Gets the value of the 'dspId' field.
   * @return The value of the 'dspId' field.
   */
  public java.lang.CharSequence getDspId() {
    return dspId;
  }


  /**
   * Sets the value of the 'dspId' field.
   * @param value the value to set.
   */
  public void setDspId(java.lang.CharSequence value) {
    this.dspId = value;
  }

  /**
   * Gets the value of the 'os' field.
   * @return The value of the 'os' field.
   */
  public java.lang.CharSequence getOs() {
    return os;
  }


  /**
   * Sets the value of the 'os' field.
   * @param value the value to set.
   */
  public void setOs(java.lang.CharSequence value) {
    this.os = value;
  }

  /**
   * Gets the value of the 'positionId' field.
   * @return The value of the 'positionId' field.
   */
  public java.lang.CharSequence getPositionId() {
    return positionId;
  }


  /**
   * Sets the value of the 'positionId' field.
   * @param value the value to set.
   */
  public void setPositionId(java.lang.CharSequence value) {
    this.positionId = value;
  }

  /**
   * Gets the value of the 'positionName' field.
   * @return The value of the 'positionName' field.
   */
  public java.lang.CharSequence getPositionName() {
    return positionName;
  }


  /**
   * Sets the value of the 'positionName' field.
   * @param value the value to set.
   */
  public void setPositionName(java.lang.CharSequence value) {
    this.positionName = value;
  }

  /**
   * Gets the value of the 'success' field.
   * @return The value of the 'success' field.
   */
  public int getSuccess() {
    return success;
  }


  /**
   * Sets the value of the 'success' field.
   * @param value the value to set.
   */
  public void setSuccess(int value) {
    this.success = value;
  }

  /**
   * Gets the value of the 'requestTime' field.
   * @return The value of the 'requestTime' field.
   */
  public java.lang.Long getRequestTime() {
    return requestTime;
  }


  /**
   * Sets the value of the 'requestTime' field.
   * @param value the value to set.
   */
  public void setRequestTime(java.lang.Long value) {
    this.requestTime = value;
  }

  /**
   * Gets the value of the 'responseTime' field.
   * @return The value of the 'responseTime' field.
   */
  public java.lang.Long getResponseTime() {
    return responseTime;
  }


  /**
   * Sets the value of the 'responseTime' field.
   * @param value the value to set.
   */
  public void setResponseTime(java.lang.Long value) {
    this.responseTime = value;
  }

  /**
   * Gets the value of the 'msg' field.
   * @return The value of the 'msg' field.
   */
  public java.lang.CharSequence getMsg() {
    return msg;
  }


  /**
   * Sets the value of the 'msg' field.
   * @param value the value to set.
   */
  public void setMsg(java.lang.CharSequence value) {
    this.msg = value;
  }

  /**
   * Gets the value of the 'externalAdId' field.
   * @return The value of the 'externalAdId' field.
   */
  public java.lang.CharSequence getExternalAdId() {
    return externalAdId;
  }


  /**
   * Sets the value of the 'externalAdId' field.
   * @param value the value to set.
   */
  public void setExternalAdId(java.lang.CharSequence value) {
    this.externalAdId = value;
  }

  /**
   * Gets the value of the 'ip' field.
   * @return The value of the 'ip' field.
   */
  public java.lang.CharSequence getIp() {
    return ip;
  }


  /**
   * Sets the value of the 'ip' field.
   * @param value the value to set.
   */
  public void setIp(java.lang.CharSequence value) {
    this.ip = value;
  }

  /**
   * Gets the value of the 'wakeupBoot' field.
   * @return The value of the 'wakeupBoot' field.
   */
  public int getWakeupBoot() {
    return wakeupBoot;
  }


  /**
   * Sets the value of the 'wakeupBoot' field.
   * @param value the value to set.
   */
  public void setWakeupBoot(int value) {
    this.wakeupBoot = value;
  }

  /**
   * Gets the value of the 'winFlag' field.
   * @return The value of the 'winFlag' field.
   */
  public java.lang.Integer getWinFlag() {
    return winFlag;
  }


  /**
   * Sets the value of the 'winFlag' field.
   * @param value the value to set.
   */
  public void setWinFlag(java.lang.Integer value) {
    this.winFlag = value;
  }

  /**
   * Gets the value of the 'la' field.
   * @return The value of the 'la' field.
   */
  public java.lang.CharSequence getLa() {
    return la;
  }


  /**
   * Sets the value of the 'la' field.
   * @param value the value to set.
   */
  public void setLa(java.lang.CharSequence value) {
    this.la = value;
  }

  /**
   * Gets the value of the 'lo' field.
   * @return The value of the 'lo' field.
   */
  public java.lang.CharSequence getLo() {
    return lo;
  }


  /**
   * Sets the value of the 'lo' field.
   * @param value the value to set.
   */
  public void setLo(java.lang.CharSequence value) {
    this.lo = value;
  }

  /**
   * Gets the value of the 'version' field.
   * @return The value of the 'version' field.
   */
  public java.lang.CharSequence getVersion() {
    return version;
  }


  /**
   * Sets the value of the 'version' field.
   * @param value the value to set.
   */
  public void setVersion(java.lang.CharSequence value) {
    this.version = value;
  }

  /**
   * Gets the value of the 'uuid' field.
   * @return The value of the 'uuid' field.
   */
  public java.lang.CharSequence getUuid() {
    return uuid;
  }


  /**
   * Sets the value of the 'uuid' field.
   * @param value the value to set.
   */
  public void setUuid(java.lang.CharSequence value) {
    this.uuid = value;
  }

  /**
   * Gets the value of the 'banwords' field.
   * @return The value of the 'banwords' field.
   */
  public java.lang.CharSequence getBanwords() {
    return banwords;
  }


  /**
   * Sets the value of the 'banwords' field.
   * @param value the value to set.
   */
  public void setBanwords(java.lang.CharSequence value) {
    this.banwords = value;
  }

  /**
   * Gets the value of the 'reqId' field.
   * @return The value of the 'reqId' field.
   */
  public java.lang.CharSequence getReqId() {
    return reqId;
  }


  /**
   * Sets the value of the 'reqId' field.
   * @param value the value to set.
   */
  public void setReqId(java.lang.CharSequence value) {
    this.reqId = value;
  }

  /**
   * Gets the value of the 'industryId' field.
   * @return The value of the 'industryId' field.
   */
  public java.lang.CharSequence getIndustryId() {
    return industryId;
  }


  /**
   * Sets the value of the 'industryId' field.
   * @param value the value to set.
   */
  public void setIndustryId(java.lang.CharSequence value) {
    this.industryId = value;
  }

  /**
   * Gets the value of the 'slotId' field.
   * @return The value of the 'slotId' field.
   */
  public java.lang.CharSequence getSlotId() {
    return slotId;
  }


  /**
   * Sets the value of the 'slotId' field.
   * @param value the value to set.
   */
  public void setSlotId(java.lang.CharSequence value) {
    this.slotId = value;
  }

  /**
   * Gets the value of the 'advertiser_type' field.
   * @return The value of the 'advertiser_type' field.
   */
  public java.lang.CharSequence getAdvertiserType() {
    return advertiser_type;
  }


  /**
   * Sets the value of the 'advertiser_type' field.
   * @param value the value to set.
   */
  public void setAdvertiserType(java.lang.CharSequence value) {
    this.advertiser_type = value;
  }

  /**
   * Gets the value of the 'price' field.
   * @return The value of the 'price' field.
   */
  public java.lang.Double getPrice() {
    return price;
  }


  /**
   * Sets the value of the 'price' field.
   * @param value the value to set.
   */
  public void setPrice(java.lang.Double value) {
    this.price = value;
  }

  /**
   * Gets the value of the 'blogId' field.
   * @return The value of the 'blogId' field.
   */
  public java.lang.Long getBlogId() {
    return blogId;
  }


  /**
   * Sets the value of the 'blogId' field.
   * @param value the value to set.
   */
  public void setBlogId(java.lang.Long value) {
    this.blogId = value;
  }

  /**
   * Gets the value of the 'bidFactor' field.
   * @return The value of the 'bidFactor' field.
   */
  public java.lang.Double getBidFactor() {
    return bidFactor;
  }


  /**
   * Sets the value of the 'bidFactor' field.
   * @param value the value to set.
   */
  public void setBidFactor(java.lang.Double value) {
    this.bidFactor = value;
  }

  /**
   * Gets the value of the 'ext' field.
   * @return The value of the 'ext' field.
   */
  public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getExt() {
    return ext;
  }


  /**
   * Sets the value of the 'ext' field.
   * @param value the value to set.
   */
  public void setExt(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
    this.ext = value;
  }

  /**
   * Creates a new AdxDspEvent RecordBuilder.
   * @return A new AdxDspEvent RecordBuilder
   */
  public static com.netease.wm.hubble.avro.AdxDspEvent.Builder newBuilder() {
    return new com.netease.wm.hubble.avro.AdxDspEvent.Builder();
  }

  /**
   * Creates a new AdxDspEvent RecordBuilder by copying an existing Builder.
   * @param other The existing builder to copy.
   * @return A new AdxDspEvent RecordBuilder
   */
  public static com.netease.wm.hubble.avro.AdxDspEvent.Builder newBuilder(com.netease.wm.hubble.avro.AdxDspEvent.Builder other) {
    if (other == null) {
      return new com.netease.wm.hubble.avro.AdxDspEvent.Builder();
    } else {
      return new com.netease.wm.hubble.avro.AdxDspEvent.Builder(other);
    }
  }

  /**
   * Creates a new AdxDspEvent RecordBuilder by copying an existing AdxDspEvent instance.
   * @param other The existing instance to copy.
   * @return A new AdxDspEvent RecordBuilder
   */
  public static com.netease.wm.hubble.avro.AdxDspEvent.Builder newBuilder(com.netease.wm.hubble.avro.AdxDspEvent other) {
    if (other == null) {
      return new com.netease.wm.hubble.avro.AdxDspEvent.Builder();
    } else {
      return new com.netease.wm.hubble.avro.AdxDspEvent.Builder(other);
    }
  }

  /**
   * RecordBuilder for AdxDspEvent instances.
   */
  @org.apache.avro.specific.AvroGenerated
  public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<AdxDspEvent>
    implements org.apache.avro.data.RecordBuilder<AdxDspEvent> {

    private java.lang.CharSequence adId;
    private java.lang.CharSequence appId;
    private java.lang.CharSequence dspId;
    private java.lang.CharSequence os;
    private java.lang.CharSequence positionId;
    private java.lang.CharSequence positionName;
    private int success;
    private java.lang.Long requestTime;
    private java.lang.Long responseTime;
    private java.lang.CharSequence msg;
    private java.lang.CharSequence externalAdId;
    private java.lang.CharSequence ip;
    private int wakeupBoot;
    private java.lang.Integer winFlag;
    private java.lang.CharSequence la;
    private java.lang.CharSequence lo;
    private java.lang.CharSequence version;
    private java.lang.CharSequence uuid;
    private java.lang.CharSequence banwords;
    private java.lang.CharSequence reqId;
    private java.lang.CharSequence industryId;
    private java.lang.CharSequence slotId;
    private java.lang.CharSequence advertiser_type;
    private java.lang.Double price;
    private java.lang.Long blogId;
    private java.lang.Double bidFactor;
    private java.util.Map<java.lang.CharSequence,java.lang.CharSequence> ext;

    /** Creates a new Builder */
    private Builder() {
      super(SCHEMA$, MODEL$);
    }

    /**
     * Creates a Builder by copying an existing Builder.
     * @param other The existing Builder to copy.
     */
    private Builder(com.netease.wm.hubble.avro.AdxDspEvent.Builder other) {
      super(other);
      if (isValidValue(fields()[0], other.adId)) {
        this.adId = data().deepCopy(fields()[0].schema(), other.adId);
        fieldSetFlags()[0] = other.fieldSetFlags()[0];
      }
      if (isValidValue(fields()[1], other.appId)) {
        this.appId = data().deepCopy(fields()[1].schema(), other.appId);
        fieldSetFlags()[1] = other.fieldSetFlags()[1];
      }
      if (isValidValue(fields()[2], other.dspId)) {
        this.dspId = data().deepCopy(fields()[2].schema(), other.dspId);
        fieldSetFlags()[2] = other.fieldSetFlags()[2];
      }
      if (isValidValue(fields()[3], other.os)) {
        this.os = data().deepCopy(fields()[3].schema(), other.os);
        fieldSetFlags()[3] = other.fieldSetFlags()[3];
      }
      if (isValidValue(fields()[4], other.positionId)) {
        this.positionId = data().deepCopy(fields()[4].schema(), other.positionId);
        fieldSetFlags()[4] = other.fieldSetFlags()[4];
      }
      if (isValidValue(fields()[5], other.positionName)) {
        this.positionName = data().deepCopy(fields()[5].schema(), other.positionName);
        fieldSetFlags()[5] = other.fieldSetFlags()[5];
      }
      if (isValidValue(fields()[6], other.success)) {
        this.success = data().deepCopy(fields()[6].schema(), other.success);
        fieldSetFlags()[6] = other.fieldSetFlags()[6];
      }
      if (isValidValue(fields()[7], other.requestTime)) {
        this.requestTime = data().deepCopy(fields()[7].schema(), other.requestTime);
        fieldSetFlags()[7] = other.fieldSetFlags()[7];
      }
      if (isValidValue(fields()[8], other.responseTime)) {
        this.responseTime = data().deepCopy(fields()[8].schema(), other.responseTime);
        fieldSetFlags()[8] = other.fieldSetFlags()[8];
      }
      if (isValidValue(fields()[9], other.msg)) {
        this.msg = data().deepCopy(fields()[9].schema(), other.msg);
        fieldSetFlags()[9] = other.fieldSetFlags()[9];
      }
      if (isValidValue(fields()[10], other.externalAdId)) {
        this.externalAdId = data().deepCopy(fields()[10].schema(), other.externalAdId);
        fieldSetFlags()[10] = other.fieldSetFlags()[10];
      }
      if (isValidValue(fields()[11], other.ip)) {
        this.ip = data().deepCopy(fields()[11].schema(), other.ip);
        fieldSetFlags()[11] = other.fieldSetFlags()[11];
      }
      if (isValidValue(fields()[12], other.wakeupBoot)) {
        this.wakeupBoot = data().deepCopy(fields()[12].schema(), other.wakeupBoot);
        fieldSetFlags()[12] = other.fieldSetFlags()[12];
      }
      if (isValidValue(fields()[13], other.winFlag)) {
        this.winFlag = data().deepCopy(fields()[13].schema(), other.winFlag);
        fieldSetFlags()[13] = other.fieldSetFlags()[13];
      }
      if (isValidValue(fields()[14], other.la)) {
        this.la = data().deepCopy(fields()[14].schema(), other.la);
        fieldSetFlags()[14] = other.fieldSetFlags()[14];
      }
      if (isValidValue(fields()[15], other.lo)) {
        this.lo = data().deepCopy(fields()[15].schema(), other.lo);
        fieldSetFlags()[15] = other.fieldSetFlags()[15];
      }
      if (isValidValue(fields()[16], other.version)) {
        this.version = data().deepCopy(fields()[16].schema(), other.version);
        fieldSetFlags()[16] = other.fieldSetFlags()[16];
      }
      if (isValidValue(fields()[17], other.uuid)) {
        this.uuid = data().deepCopy(fields()[17].schema(), other.uuid);
        fieldSetFlags()[17] = other.fieldSetFlags()[17];
      }
      if (isValidValue(fields()[18], other.banwords)) {
        this.banwords = data().deepCopy(fields()[18].schema(), other.banwords);
        fieldSetFlags()[18] = other.fieldSetFlags()[18];
      }
      if (isValidValue(fields()[19], other.reqId)) {
        this.reqId = data().deepCopy(fields()[19].schema(), other.reqId);
        fieldSetFlags()[19] = other.fieldSetFlags()[19];
      }
      if (isValidValue(fields()[20], other.industryId)) {
        this.industryId = data().deepCopy(fields()[20].schema(), other.industryId);
        fieldSetFlags()[20] = other.fieldSetFlags()[20];
      }
      if (isValidValue(fields()[21], other.slotId)) {
        this.slotId = data().deepCopy(fields()[21].schema(), other.slotId);
        fieldSetFlags()[21] = other.fieldSetFlags()[21];
      }
      if (isValidValue(fields()[22], other.advertiser_type)) {
        this.advertiser_type = data().deepCopy(fields()[22].schema(), other.advertiser_type);
        fieldSetFlags()[22] = other.fieldSetFlags()[22];
      }
      if (isValidValue(fields()[23], other.price)) {
        this.price = data().deepCopy(fields()[23].schema(), other.price);
        fieldSetFlags()[23] = other.fieldSetFlags()[23];
      }
      if (isValidValue(fields()[24], other.blogId)) {
        this.blogId = data().deepCopy(fields()[24].schema(), other.blogId);
        fieldSetFlags()[24] = other.fieldSetFlags()[24];
      }
      if (isValidValue(fields()[25], other.bidFactor)) {
        this.bidFactor = data().deepCopy(fields()[25].schema(), other.bidFactor);
        fieldSetFlags()[25] = other.fieldSetFlags()[25];
      }
      if (isValidValue(fields()[26], other.ext)) {
        this.ext = data().deepCopy(fields()[26].schema(), other.ext);
        fieldSetFlags()[26] = other.fieldSetFlags()[26];
      }
    }

    /**
     * Creates a Builder by copying an existing AdxDspEvent instance
     * @param other The existing instance to copy.
     */
    private Builder(com.netease.wm.hubble.avro.AdxDspEvent other) {
      super(SCHEMA$, MODEL$);
      if (isValidValue(fields()[0], other.adId)) {
        this.adId = data().deepCopy(fields()[0].schema(), other.adId);
        fieldSetFlags()[0] = true;
      }
      if (isValidValue(fields()[1], other.appId)) {
        this.appId = data().deepCopy(fields()[1].schema(), other.appId);
        fieldSetFlags()[1] = true;
      }
      if (isValidValue(fields()[2], other.dspId)) {
        this.dspId = data().deepCopy(fields()[2].schema(), other.dspId);
        fieldSetFlags()[2] = true;
      }
      if (isValidValue(fields()[3], other.os)) {
        this.os = data().deepCopy(fields()[3].schema(), other.os);
        fieldSetFlags()[3] = true;
      }
      if (isValidValue(fields()[4], other.positionId)) {
        this.positionId = data().deepCopy(fields()[4].schema(), other.positionId);
        fieldSetFlags()[4] = true;
      }
      if (isValidValue(fields()[5], other.positionName)) {
        this.positionName = data().deepCopy(fields()[5].schema(), other.positionName);
        fieldSetFlags()[5] = true;
      }
      if (isValidValue(fields()[6], other.success)) {
        this.success = data().deepCopy(fields()[6].schema(), other.success);
        fieldSetFlags()[6] = true;
      }
      if (isValidValue(fields()[7], other.requestTime)) {
        this.requestTime = data().deepCopy(fields()[7].schema(), other.requestTime);
        fieldSetFlags()[7] = true;
      }
      if (isValidValue(fields()[8], other.responseTime)) {
        this.responseTime = data().deepCopy(fields()[8].schema(), other.responseTime);
        fieldSetFlags()[8] = true;
      }
      if (isValidValue(fields()[9], other.msg)) {
        this.msg = data().deepCopy(fields()[9].schema(), other.msg);
        fieldSetFlags()[9] = true;
      }
      if (isValidValue(fields()[10], other.externalAdId)) {
        this.externalAdId = data().deepCopy(fields()[10].schema(), other.externalAdId);
        fieldSetFlags()[10] = true;
      }
      if (isValidValue(fields()[11], other.ip)) {
        this.ip = data().deepCopy(fields()[11].schema(), other.ip);
        fieldSetFlags()[11] = true;
      }
      if (isValidValue(fields()[12], other.wakeupBoot)) {
        this.wakeupBoot = data().deepCopy(fields()[12].schema(), other.wakeupBoot);
        fieldSetFlags()[12] = true;
      }
      if (isValidValue(fields()[13], other.winFlag)) {
        this.winFlag = data().deepCopy(fields()[13].schema(), other.winFlag);
        fieldSetFlags()[13] = true;
      }
      if (isValidValue(fields()[14], other.la)) {
        this.la = data().deepCopy(fields()[14].schema(), other.la);
        fieldSetFlags()[14] = true;
      }
      if (isValidValue(fields()[15], other.lo)) {
        this.lo = data().deepCopy(fields()[15].schema(), other.lo);
        fieldSetFlags()[15] = true;
      }
      if (isValidValue(fields()[16], other.version)) {
        this.version = data().deepCopy(fields()[16].schema(), other.version);
        fieldSetFlags()[16] = true;
      }
      if (isValidValue(fields()[17], other.uuid)) {
        this.uuid = data().deepCopy(fields()[17].schema(), other.uuid);
        fieldSetFlags()[17] = true;
      }
      if (isValidValue(fields()[18], other.banwords)) {
        this.banwords = data().deepCopy(fields()[18].schema(), other.banwords);
        fieldSetFlags()[18] = true;
      }
      if (isValidValue(fields()[19], other.reqId)) {
        this.reqId = data().deepCopy(fields()[19].schema(), other.reqId);
        fieldSetFlags()[19] = true;
      }
      if (isValidValue(fields()[20], other.industryId)) {
        this.industryId = data().deepCopy(fields()[20].schema(), other.industryId);
        fieldSetFlags()[20] = true;
      }
      if (isValidValue(fields()[21], other.slotId)) {
        this.slotId = data().deepCopy(fields()[21].schema(), other.slotId);
        fieldSetFlags()[21] = true;
      }
      if (isValidValue(fields()[22], other.advertiser_type)) {
        this.advertiser_type = data().deepCopy(fields()[22].schema(), other.advertiser_type);
        fieldSetFlags()[22] = true;
      }
      if (isValidValue(fields()[23], other.price)) {
        this.price = data().deepCopy(fields()[23].schema(), other.price);
        fieldSetFlags()[23] = true;
      }
      if (isValidValue(fields()[24], other.blogId)) {
        this.blogId = data().deepCopy(fields()[24].schema(), other.blogId);
        fieldSetFlags()[24] = true;
      }
      if (isValidValue(fields()[25], other.bidFactor)) {
        this.bidFactor = data().deepCopy(fields()[25].schema(), other.bidFactor);
        fieldSetFlags()[25] = true;
      }
      if (isValidValue(fields()[26], other.ext)) {
        this.ext = data().deepCopy(fields()[26].schema(), other.ext);
        fieldSetFlags()[26] = true;
      }
    }

    /**
      * Gets the value of the 'adId' field.
      * @return The value.
      */
    public java.lang.CharSequence getAdId() {
      return adId;
    }


    /**
      * Sets the value of the 'adId' field.
      * @param value The value of 'adId'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setAdId(java.lang.CharSequence value) {
      validate(fields()[0], value);
      this.adId = value;
      fieldSetFlags()[0] = true;
      return this;
    }

    /**
      * Checks whether the 'adId' field has been set.
      * @return True if the 'adId' field has been set, false otherwise.
      */
    public boolean hasAdId() {
      return fieldSetFlags()[0];
    }


    /**
      * Clears the value of the 'adId' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearAdId() {
      adId = null;
      fieldSetFlags()[0] = false;
      return this;
    }

    /**
      * Gets the value of the 'appId' field.
      * @return The value.
      */
    public java.lang.CharSequence getAppId() {
      return appId;
    }


    /**
      * Sets the value of the 'appId' field.
      * @param value The value of 'appId'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setAppId(java.lang.CharSequence value) {
      validate(fields()[1], value);
      this.appId = value;
      fieldSetFlags()[1] = true;
      return this;
    }

    /**
      * Checks whether the 'appId' field has been set.
      * @return True if the 'appId' field has been set, false otherwise.
      */
    public boolean hasAppId() {
      return fieldSetFlags()[1];
    }


    /**
      * Clears the value of the 'appId' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearAppId() {
      appId = null;
      fieldSetFlags()[1] = false;
      return this;
    }

    /**
      * Gets the value of the 'dspId' field.
      * @return The value.
      */
    public java.lang.CharSequence getDspId() {
      return dspId;
    }


    /**
      * Sets the value of the 'dspId' field.
      * @param value The value of 'dspId'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setDspId(java.lang.CharSequence value) {
      validate(fields()[2], value);
      this.dspId = value;
      fieldSetFlags()[2] = true;
      return this;
    }

    /**
      * Checks whether the 'dspId' field has been set.
      * @return True if the 'dspId' field has been set, false otherwise.
      */
    public boolean hasDspId() {
      return fieldSetFlags()[2];
    }


    /**
      * Clears the value of the 'dspId' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearDspId() {
      dspId = null;
      fieldSetFlags()[2] = false;
      return this;
    }

    /**
      * Gets the value of the 'os' field.
      * @return The value.
      */
    public java.lang.CharSequence getOs() {
      return os;
    }


    /**
      * Sets the value of the 'os' field.
      * @param value The value of 'os'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setOs(java.lang.CharSequence value) {
      validate(fields()[3], value);
      this.os = value;
      fieldSetFlags()[3] = true;
      return this;
    }

    /**
      * Checks whether the 'os' field has been set.
      * @return True if the 'os' field has been set, false otherwise.
      */
    public boolean hasOs() {
      return fieldSetFlags()[3];
    }


    /**
      * Clears the value of the 'os' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearOs() {
      os = null;
      fieldSetFlags()[3] = false;
      return this;
    }

    /**
      * Gets the value of the 'positionId' field.
      * @return The value.
      */
    public java.lang.CharSequence getPositionId() {
      return positionId;
    }


    /**
      * Sets the value of the 'positionId' field.
      * @param value The value of 'positionId'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setPositionId(java.lang.CharSequence value) {
      validate(fields()[4], value);
      this.positionId = value;
      fieldSetFlags()[4] = true;
      return this;
    }

    /**
      * Checks whether the 'positionId' field has been set.
      * @return True if the 'positionId' field has been set, false otherwise.
      */
    public boolean hasPositionId() {
      return fieldSetFlags()[4];
    }


    /**
      * Clears the value of the 'positionId' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearPositionId() {
      positionId = null;
      fieldSetFlags()[4] = false;
      return this;
    }

    /**
      * Gets the value of the 'positionName' field.
      * @return The value.
      */
    public java.lang.CharSequence getPositionName() {
      return positionName;
    }


    /**
      * Sets the value of the 'positionName' field.
      * @param value The value of 'positionName'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setPositionName(java.lang.CharSequence value) {
      validate(fields()[5], value);
      this.positionName = value;
      fieldSetFlags()[5] = true;
      return this;
    }

    /**
      * Checks whether the 'positionName' field has been set.
      * @return True if the 'positionName' field has been set, false otherwise.
      */
    public boolean hasPositionName() {
      return fieldSetFlags()[5];
    }


    /**
      * Clears the value of the 'positionName' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearPositionName() {
      positionName = null;
      fieldSetFlags()[5] = false;
      return this;
    }

    /**
      * Gets the value of the 'success' field.
      * @return The value.
      */
    public int getSuccess() {
      return success;
    }


    /**
      * Sets the value of the 'success' field.
      * @param value The value of 'success'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setSuccess(int value) {
      validate(fields()[6], value);
      this.success = value;
      fieldSetFlags()[6] = true;
      return this;
    }

    /**
      * Checks whether the 'success' field has been set.
      * @return True if the 'success' field has been set, false otherwise.
      */
    public boolean hasSuccess() {
      return fieldSetFlags()[6];
    }


    /**
      * Clears the value of the 'success' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearSuccess() {
      fieldSetFlags()[6] = false;
      return this;
    }

    /**
      * Gets the value of the 'requestTime' field.
      * @return The value.
      */
    public java.lang.Long getRequestTime() {
      return requestTime;
    }


    /**
      * Sets the value of the 'requestTime' field.
      * @param value The value of 'requestTime'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setRequestTime(java.lang.Long value) {
      validate(fields()[7], value);
      this.requestTime = value;
      fieldSetFlags()[7] = true;
      return this;
    }

    /**
      * Checks whether the 'requestTime' field has been set.
      * @return True if the 'requestTime' field has been set, false otherwise.
      */
    public boolean hasRequestTime() {
      return fieldSetFlags()[7];
    }


    /**
      * Clears the value of the 'requestTime' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearRequestTime() {
      requestTime = null;
      fieldSetFlags()[7] = false;
      return this;
    }

    /**
      * Gets the value of the 'responseTime' field.
      * @return The value.
      */
    public java.lang.Long getResponseTime() {
      return responseTime;
    }


    /**
      * Sets the value of the 'responseTime' field.
      * @param value The value of 'responseTime'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setResponseTime(java.lang.Long value) {
      validate(fields()[8], value);
      this.responseTime = value;
      fieldSetFlags()[8] = true;
      return this;
    }

    /**
      * Checks whether the 'responseTime' field has been set.
      * @return True if the 'responseTime' field has been set, false otherwise.
      */
    public boolean hasResponseTime() {
      return fieldSetFlags()[8];
    }


    /**
      * Clears the value of the 'responseTime' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearResponseTime() {
      responseTime = null;
      fieldSetFlags()[8] = false;
      return this;
    }

    /**
      * Gets the value of the 'msg' field.
      * @return The value.
      */
    public java.lang.CharSequence getMsg() {
      return msg;
    }


    /**
      * Sets the value of the 'msg' field.
      * @param value The value of 'msg'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setMsg(java.lang.CharSequence value) {
      validate(fields()[9], value);
      this.msg = value;
      fieldSetFlags()[9] = true;
      return this;
    }

    /**
      * Checks whether the 'msg' field has been set.
      * @return True if the 'msg' field has been set, false otherwise.
      */
    public boolean hasMsg() {
      return fieldSetFlags()[9];
    }


    /**
      * Clears the value of the 'msg' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearMsg() {
      msg = null;
      fieldSetFlags()[9] = false;
      return this;
    }

    /**
      * Gets the value of the 'externalAdId' field.
      * @return The value.
      */
    public java.lang.CharSequence getExternalAdId() {
      return externalAdId;
    }


    /**
      * Sets the value of the 'externalAdId' field.
      * @param value The value of 'externalAdId'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setExternalAdId(java.lang.CharSequence value) {
      validate(fields()[10], value);
      this.externalAdId = value;
      fieldSetFlags()[10] = true;
      return this;
    }

    /**
      * Checks whether the 'externalAdId' field has been set.
      * @return True if the 'externalAdId' field has been set, false otherwise.
      */
    public boolean hasExternalAdId() {
      return fieldSetFlags()[10];
    }


    /**
      * Clears the value of the 'externalAdId' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearExternalAdId() {
      externalAdId = null;
      fieldSetFlags()[10] = false;
      return this;
    }

    /**
      * Gets the value of the 'ip' field.
      * @return The value.
      */
    public java.lang.CharSequence getIp() {
      return ip;
    }


    /**
      * Sets the value of the 'ip' field.
      * @param value The value of 'ip'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setIp(java.lang.CharSequence value) {
      validate(fields()[11], value);
      this.ip = value;
      fieldSetFlags()[11] = true;
      return this;
    }

    /**
      * Checks whether the 'ip' field has been set.
      * @return True if the 'ip' field has been set, false otherwise.
      */
    public boolean hasIp() {
      return fieldSetFlags()[11];
    }


    /**
      * Clears the value of the 'ip' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearIp() {
      ip = null;
      fieldSetFlags()[11] = false;
      return this;
    }

    /**
      * Gets the value of the 'wakeupBoot' field.
      * @return The value.
      */
    public int getWakeupBoot() {
      return wakeupBoot;
    }


    /**
      * Sets the value of the 'wakeupBoot' field.
      * @param value The value of 'wakeupBoot'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setWakeupBoot(int value) {
      validate(fields()[12], value);
      this.wakeupBoot = value;
      fieldSetFlags()[12] = true;
      return this;
    }

    /**
      * Checks whether the 'wakeupBoot' field has been set.
      * @return True if the 'wakeupBoot' field has been set, false otherwise.
      */
    public boolean hasWakeupBoot() {
      return fieldSetFlags()[12];
    }


    /**
      * Clears the value of the 'wakeupBoot' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearWakeupBoot() {
      fieldSetFlags()[12] = false;
      return this;
    }

    /**
      * Gets the value of the 'winFlag' field.
      * @return The value.
      */
    public java.lang.Integer getWinFlag() {
      return winFlag;
    }


    /**
      * Sets the value of the 'winFlag' field.
      * @param value The value of 'winFlag'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setWinFlag(java.lang.Integer value) {
      validate(fields()[13], value);
      this.winFlag = value;
      fieldSetFlags()[13] = true;
      return this;
    }

    /**
      * Checks whether the 'winFlag' field has been set.
      * @return True if the 'winFlag' field has been set, false otherwise.
      */
    public boolean hasWinFlag() {
      return fieldSetFlags()[13];
    }


    /**
      * Clears the value of the 'winFlag' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearWinFlag() {
      winFlag = null;
      fieldSetFlags()[13] = false;
      return this;
    }

    /**
      * Gets the value of the 'la' field.
      * @return The value.
      */
    public java.lang.CharSequence getLa() {
      return la;
    }


    /**
      * Sets the value of the 'la' field.
      * @param value The value of 'la'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setLa(java.lang.CharSequence value) {
      validate(fields()[14], value);
      this.la = value;
      fieldSetFlags()[14] = true;
      return this;
    }

    /**
      * Checks whether the 'la' field has been set.
      * @return True if the 'la' field has been set, false otherwise.
      */
    public boolean hasLa() {
      return fieldSetFlags()[14];
    }


    /**
      * Clears the value of the 'la' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearLa() {
      la = null;
      fieldSetFlags()[14] = false;
      return this;
    }

    /**
      * Gets the value of the 'lo' field.
      * @return The value.
      */
    public java.lang.CharSequence getLo() {
      return lo;
    }


    /**
      * Sets the value of the 'lo' field.
      * @param value The value of 'lo'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setLo(java.lang.CharSequence value) {
      validate(fields()[15], value);
      this.lo = value;
      fieldSetFlags()[15] = true;
      return this;
    }

    /**
      * Checks whether the 'lo' field has been set.
      * @return True if the 'lo' field has been set, false otherwise.
      */
    public boolean hasLo() {
      return fieldSetFlags()[15];
    }


    /**
      * Clears the value of the 'lo' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearLo() {
      lo = null;
      fieldSetFlags()[15] = false;
      return this;
    }

    /**
      * Gets the value of the 'version' field.
      * @return The value.
      */
    public java.lang.CharSequence getVersion() {
      return version;
    }


    /**
      * Sets the value of the 'version' field.
      * @param value The value of 'version'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setVersion(java.lang.CharSequence value) {
      validate(fields()[16], value);
      this.version = value;
      fieldSetFlags()[16] = true;
      return this;
    }

    /**
      * Checks whether the 'version' field has been set.
      * @return True if the 'version' field has been set, false otherwise.
      */
    public boolean hasVersion() {
      return fieldSetFlags()[16];
    }


    /**
      * Clears the value of the 'version' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearVersion() {
      version = null;
      fieldSetFlags()[16] = false;
      return this;
    }

    /**
      * Gets the value of the 'uuid' field.
      * @return The value.
      */
    public java.lang.CharSequence getUuid() {
      return uuid;
    }


    /**
      * Sets the value of the 'uuid' field.
      * @param value The value of 'uuid'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setUuid(java.lang.CharSequence value) {
      validate(fields()[17], value);
      this.uuid = value;
      fieldSetFlags()[17] = true;
      return this;
    }

    /**
      * Checks whether the 'uuid' field has been set.
      * @return True if the 'uuid' field has been set, false otherwise.
      */
    public boolean hasUuid() {
      return fieldSetFlags()[17];
    }


    /**
      * Clears the value of the 'uuid' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearUuid() {
      uuid = null;
      fieldSetFlags()[17] = false;
      return this;
    }

    /**
      * Gets the value of the 'banwords' field.
      * @return The value.
      */
    public java.lang.CharSequence getBanwords() {
      return banwords;
    }


    /**
      * Sets the value of the 'banwords' field.
      * @param value The value of 'banwords'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setBanwords(java.lang.CharSequence value) {
      validate(fields()[18], value);
      this.banwords = value;
      fieldSetFlags()[18] = true;
      return this;
    }

    /**
      * Checks whether the 'banwords' field has been set.
      * @return True if the 'banwords' field has been set, false otherwise.
      */
    public boolean hasBanwords() {
      return fieldSetFlags()[18];
    }


    /**
      * Clears the value of the 'banwords' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearBanwords() {
      banwords = null;
      fieldSetFlags()[18] = false;
      return this;
    }

    /**
      * Gets the value of the 'reqId' field.
      * @return The value.
      */
    public java.lang.CharSequence getReqId() {
      return reqId;
    }


    /**
      * Sets the value of the 'reqId' field.
      * @param value The value of 'reqId'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setReqId(java.lang.CharSequence value) {
      validate(fields()[19], value);
      this.reqId = value;
      fieldSetFlags()[19] = true;
      return this;
    }

    /**
      * Checks whether the 'reqId' field has been set.
      * @return True if the 'reqId' field has been set, false otherwise.
      */
    public boolean hasReqId() {
      return fieldSetFlags()[19];
    }


    /**
      * Clears the value of the 'reqId' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearReqId() {
      reqId = null;
      fieldSetFlags()[19] = false;
      return this;
    }

    /**
      * Gets the value of the 'industryId' field.
      * @return The value.
      */
    public java.lang.CharSequence getIndustryId() {
      return industryId;
    }


    /**
      * Sets the value of the 'industryId' field.
      * @param value The value of 'industryId'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setIndustryId(java.lang.CharSequence value) {
      validate(fields()[20], value);
      this.industryId = value;
      fieldSetFlags()[20] = true;
      return this;
    }

    /**
      * Checks whether the 'industryId' field has been set.
      * @return True if the 'industryId' field has been set, false otherwise.
      */
    public boolean hasIndustryId() {
      return fieldSetFlags()[20];
    }


    /**
      * Clears the value of the 'industryId' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearIndustryId() {
      industryId = null;
      fieldSetFlags()[20] = false;
      return this;
    }

    /**
      * Gets the value of the 'slotId' field.
      * @return The value.
      */
    public java.lang.CharSequence getSlotId() {
      return slotId;
    }


    /**
      * Sets the value of the 'slotId' field.
      * @param value The value of 'slotId'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setSlotId(java.lang.CharSequence value) {
      validate(fields()[21], value);
      this.slotId = value;
      fieldSetFlags()[21] = true;
      return this;
    }

    /**
      * Checks whether the 'slotId' field has been set.
      * @return True if the 'slotId' field has been set, false otherwise.
      */
    public boolean hasSlotId() {
      return fieldSetFlags()[21];
    }


    /**
      * Clears the value of the 'slotId' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearSlotId() {
      slotId = null;
      fieldSetFlags()[21] = false;
      return this;
    }

    /**
      * Gets the value of the 'advertiser_type' field.
      * @return The value.
      */
    public java.lang.CharSequence getAdvertiserType() {
      return advertiser_type;
    }


    /**
      * Sets the value of the 'advertiser_type' field.
      * @param value The value of 'advertiser_type'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setAdvertiserType(java.lang.CharSequence value) {
      validate(fields()[22], value);
      this.advertiser_type = value;
      fieldSetFlags()[22] = true;
      return this;
    }

    /**
      * Checks whether the 'advertiser_type' field has been set.
      * @return True if the 'advertiser_type' field has been set, false otherwise.
      */
    public boolean hasAdvertiserType() {
      return fieldSetFlags()[22];
    }


    /**
      * Clears the value of the 'advertiser_type' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearAdvertiserType() {
      advertiser_type = null;
      fieldSetFlags()[22] = false;
      return this;
    }

    /**
      * Gets the value of the 'price' field.
      * @return The value.
      */
    public java.lang.Double getPrice() {
      return price;
    }


    /**
      * Sets the value of the 'price' field.
      * @param value The value of 'price'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setPrice(java.lang.Double value) {
      validate(fields()[23], value);
      this.price = value;
      fieldSetFlags()[23] = true;
      return this;
    }

    /**
      * Checks whether the 'price' field has been set.
      * @return True if the 'price' field has been set, false otherwise.
      */
    public boolean hasPrice() {
      return fieldSetFlags()[23];
    }


    /**
      * Clears the value of the 'price' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearPrice() {
      price = null;
      fieldSetFlags()[23] = false;
      return this;
    }

    /**
      * Gets the value of the 'blogId' field.
      * @return The value.
      */
    public java.lang.Long getBlogId() {
      return blogId;
    }


    /**
      * Sets the value of the 'blogId' field.
      * @param value The value of 'blogId'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setBlogId(java.lang.Long value) {
      validate(fields()[24], value);
      this.blogId = value;
      fieldSetFlags()[24] = true;
      return this;
    }

    /**
      * Checks whether the 'blogId' field has been set.
      * @return True if the 'blogId' field has been set, false otherwise.
      */
    public boolean hasBlogId() {
      return fieldSetFlags()[24];
    }


    /**
      * Clears the value of the 'blogId' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearBlogId() {
      blogId = null;
      fieldSetFlags()[24] = false;
      return this;
    }

    /**
      * Gets the value of the 'bidFactor' field.
      * @return The value.
      */
    public java.lang.Double getBidFactor() {
      return bidFactor;
    }


    /**
      * Sets the value of the 'bidFactor' field.
      * @param value The value of 'bidFactor'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setBidFactor(java.lang.Double value) {
      validate(fields()[25], value);
      this.bidFactor = value;
      fieldSetFlags()[25] = true;
      return this;
    }

    /**
      * Checks whether the 'bidFactor' field has been set.
      * @return True if the 'bidFactor' field has been set, false otherwise.
      */
    public boolean hasBidFactor() {
      return fieldSetFlags()[25];
    }


    /**
      * Clears the value of the 'bidFactor' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearBidFactor() {
      bidFactor = null;
      fieldSetFlags()[25] = false;
      return this;
    }

    /**
      * Gets the value of the 'ext' field.
      * @return The value.
      */
    public java.util.Map<java.lang.CharSequence,java.lang.CharSequence> getExt() {
      return ext;
    }


    /**
      * Sets the value of the 'ext' field.
      * @param value The value of 'ext'.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder setExt(java.util.Map<java.lang.CharSequence,java.lang.CharSequence> value) {
      validate(fields()[26], value);
      this.ext = value;
      fieldSetFlags()[26] = true;
      return this;
    }

    /**
      * Checks whether the 'ext' field has been set.
      * @return True if the 'ext' field has been set, false otherwise.
      */
    public boolean hasExt() {
      return fieldSetFlags()[26];
    }


    /**
      * Clears the value of the 'ext' field.
      * @return This builder.
      */
    public com.netease.wm.hubble.avro.AdxDspEvent.Builder clearExt() {
      ext = null;
      fieldSetFlags()[26] = false;
      return this;
    }

    @Override
    @SuppressWarnings("unchecked")
    public AdxDspEvent build() {
      try {
        AdxDspEvent record = new AdxDspEvent();
        record.adId = fieldSetFlags()[0] ? this.adId : (java.lang.CharSequence) defaultValue(fields()[0]);
        record.appId = fieldSetFlags()[1] ? this.appId : (java.lang.CharSequence) defaultValue(fields()[1]);
        record.dspId = fieldSetFlags()[2] ? this.dspId : (java.lang.CharSequence) defaultValue(fields()[2]);
        record.os = fieldSetFlags()[3] ? this.os : (java.lang.CharSequence) defaultValue(fields()[3]);
        record.positionId = fieldSetFlags()[4] ? this.positionId : (java.lang.CharSequence) defaultValue(fields()[4]);
        record.positionName = fieldSetFlags()[5] ? this.positionName : (java.lang.CharSequence) defaultValue(fields()[5]);
        record.success = fieldSetFlags()[6] ? this.success : (java.lang.Integer) defaultValue(fields()[6]);
        record.requestTime = fieldSetFlags()[7] ? this.requestTime : (java.lang.Long) defaultValue(fields()[7]);
        record.responseTime = fieldSetFlags()[8] ? this.responseTime : (java.lang.Long) defaultValue(fields()[8]);
        record.msg = fieldSetFlags()[9] ? this.msg : (java.lang.CharSequence) defaultValue(fields()[9]);
        record.externalAdId = fieldSetFlags()[10] ? this.externalAdId : (java.lang.CharSequence) defaultValue(fields()[10]);
        record.ip = fieldSetFlags()[11] ? this.ip : (java.lang.CharSequence) defaultValue(fields()[11]);
        record.wakeupBoot = fieldSetFlags()[12] ? this.wakeupBoot : (java.lang.Integer) defaultValue(fields()[12]);
        record.winFlag = fieldSetFlags()[13] ? this.winFlag : (java.lang.Integer) defaultValue(fields()[13]);
        record.la = fieldSetFlags()[14] ? this.la : (java.lang.CharSequence) defaultValue(fields()[14]);
        record.lo = fieldSetFlags()[15] ? this.lo : (java.lang.CharSequence) defaultValue(fields()[15]);
        record.version = fieldSetFlags()[16] ? this.version : (java.lang.CharSequence) defaultValue(fields()[16]);
        record.uuid = fieldSetFlags()[17] ? this.uuid : (java.lang.CharSequence) defaultValue(fields()[17]);
        record.banwords = fieldSetFlags()[18] ? this.banwords : (java.lang.CharSequence) defaultValue(fields()[18]);
        record.reqId = fieldSetFlags()[19] ? this.reqId : (java.lang.CharSequence) defaultValue(fields()[19]);
        record.industryId = fieldSetFlags()[20] ? this.industryId : (java.lang.CharSequence) defaultValue(fields()[20]);
        record.slotId = fieldSetFlags()[21] ? this.slotId : (java.lang.CharSequence) defaultValue(fields()[21]);
        record.advertiser_type = fieldSetFlags()[22] ? this.advertiser_type : (java.lang.CharSequence) defaultValue(fields()[22]);
        record.price = fieldSetFlags()[23] ? this.price : (java.lang.Double) defaultValue(fields()[23]);
        record.blogId = fieldSetFlags()[24] ? this.blogId : (java.lang.Long) defaultValue(fields()[24]);
        record.bidFactor = fieldSetFlags()[25] ? this.bidFactor : (java.lang.Double) defaultValue(fields()[25]);
        record.ext = fieldSetFlags()[26] ? this.ext : (java.util.Map<java.lang.CharSequence,java.lang.CharSequence>) defaultValue(fields()[26]);
        return record;
      } catch (org.apache.avro.AvroMissingFieldException e) {
        throw e;
      } catch (java.lang.Exception e) {
        throw new org.apache.avro.AvroRuntimeException(e);
      }
    }
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumWriter<AdxDspEvent>
    WRITER$ = (org.apache.avro.io.DatumWriter<AdxDspEvent>)MODEL$.createDatumWriter(SCHEMA$);

  @Override public void writeExternal(java.io.ObjectOutput out)
    throws java.io.IOException {
    WRITER$.write(this, SpecificData.getEncoder(out));
  }

  @SuppressWarnings("unchecked")
  private static final org.apache.avro.io.DatumReader<AdxDspEvent>
    READER$ = (org.apache.avro.io.DatumReader<AdxDspEvent>)MODEL$.createDatumReader(SCHEMA$);

  @Override public void readExternal(java.io.ObjectInput in)
    throws java.io.IOException {
    READER$.read(this, SpecificData.getDecoder(in));
  }

  @Override protected boolean hasCustomCoders() { return true; }

  @Override public void customEncode(org.apache.avro.io.Encoder out)
    throws java.io.IOException
  {
    out.writeString(this.adId);

    out.writeString(this.appId);

    out.writeString(this.dspId);

    out.writeString(this.os);

    out.writeString(this.positionId);

    out.writeString(this.positionName);

    out.writeInt(this.success);

    if (this.requestTime == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.requestTime);
    }

    if (this.responseTime == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.responseTime);
    }

    out.writeString(this.msg);

    if (this.externalAdId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.externalAdId);
    }

    if (this.ip == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.ip);
    }

    out.writeInt(this.wakeupBoot);

    if (this.winFlag == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeInt(this.winFlag);
    }

    if (this.la == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.la);
    }

    if (this.lo == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.lo);
    }

    if (this.version == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.version);
    }

    if (this.uuid == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.uuid);
    }

    if (this.banwords == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.banwords);
    }

    if (this.reqId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.reqId);
    }

    if (this.industryId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.industryId);
    }

    if (this.slotId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.slotId);
    }

    if (this.advertiser_type == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeString(this.advertiser_type);
    }

    if (this.price == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.price);
    }

    if (this.blogId == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeLong(this.blogId);
    }

    if (this.bidFactor == null) {
      out.writeIndex(0);
      out.writeNull();
    } else {
      out.writeIndex(1);
      out.writeDouble(this.bidFactor);
    }

    long size0 = this.ext.size();
    out.writeMapStart();
    out.setItemCount(size0);
    long actualSize0 = 0;
    for (java.util.Map.Entry<java.lang.CharSequence, java.lang.CharSequence> e0: this.ext.entrySet()) {
      actualSize0++;
      out.startItem();
      out.writeString(e0.getKey());
      java.lang.CharSequence v0 = e0.getValue();
      out.writeString(v0);
    }
    out.writeMapEnd();
    if (actualSize0 != size0)
      throw new java.util.ConcurrentModificationException("Map-size written was " + size0 + ", but element count was " + actualSize0 + ".");

  }

  @Override public void customDecode(org.apache.avro.io.ResolvingDecoder in)
    throws java.io.IOException
  {
    org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
    if (fieldOrder == null) {
      this.adId = in.readString(this.adId instanceof Utf8 ? (Utf8)this.adId : null);

      this.appId = in.readString(this.appId instanceof Utf8 ? (Utf8)this.appId : null);

      this.dspId = in.readString(this.dspId instanceof Utf8 ? (Utf8)this.dspId : null);

      this.os = in.readString(this.os instanceof Utf8 ? (Utf8)this.os : null);

      this.positionId = in.readString(this.positionId instanceof Utf8 ? (Utf8)this.positionId : null);

      this.positionName = in.readString(this.positionName instanceof Utf8 ? (Utf8)this.positionName : null);

      this.success = in.readInt();

      if (in.readIndex() != 1) {
        in.readNull();
        this.requestTime = null;
      } else {
        this.requestTime = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.responseTime = null;
      } else {
        this.responseTime = in.readLong();
      }

      this.msg = in.readString(this.msg instanceof Utf8 ? (Utf8)this.msg : null);

      if (in.readIndex() != 1) {
        in.readNull();
        this.externalAdId = null;
      } else {
        this.externalAdId = in.readString(this.externalAdId instanceof Utf8 ? (Utf8)this.externalAdId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.ip = null;
      } else {
        this.ip = in.readString(this.ip instanceof Utf8 ? (Utf8)this.ip : null);
      }

      this.wakeupBoot = in.readInt();

      if (in.readIndex() != 1) {
        in.readNull();
        this.winFlag = null;
      } else {
        this.winFlag = in.readInt();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.la = null;
      } else {
        this.la = in.readString(this.la instanceof Utf8 ? (Utf8)this.la : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.lo = null;
      } else {
        this.lo = in.readString(this.lo instanceof Utf8 ? (Utf8)this.lo : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.version = null;
      } else {
        this.version = in.readString(this.version instanceof Utf8 ? (Utf8)this.version : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.uuid = null;
      } else {
        this.uuid = in.readString(this.uuid instanceof Utf8 ? (Utf8)this.uuid : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.banwords = null;
      } else {
        this.banwords = in.readString(this.banwords instanceof Utf8 ? (Utf8)this.banwords : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.reqId = null;
      } else {
        this.reqId = in.readString(this.reqId instanceof Utf8 ? (Utf8)this.reqId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.industryId = null;
      } else {
        this.industryId = in.readString(this.industryId instanceof Utf8 ? (Utf8)this.industryId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.slotId = null;
      } else {
        this.slotId = in.readString(this.slotId instanceof Utf8 ? (Utf8)this.slotId : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.advertiser_type = null;
      } else {
        this.advertiser_type = in.readString(this.advertiser_type instanceof Utf8 ? (Utf8)this.advertiser_type : null);
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.price = null;
      } else {
        this.price = in.readDouble();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.blogId = null;
      } else {
        this.blogId = in.readLong();
      }

      if (in.readIndex() != 1) {
        in.readNull();
        this.bidFactor = null;
      } else {
        this.bidFactor = in.readDouble();
      }

      long size0 = in.readMapStart();
      java.util.Map<java.lang.CharSequence,java.lang.CharSequence> m0 = this.ext; // Need fresh name due to limitation of macro system
      if (m0 == null) {
        m0 = new java.util.HashMap<java.lang.CharSequence,java.lang.CharSequence>((int)size0);
        this.ext = m0;
      } else m0.clear();
      for ( ; 0 < size0; size0 = in.mapNext()) {
        for ( ; size0 != 0; size0--) {
          java.lang.CharSequence k0 = null;
          k0 = in.readString(k0 instanceof Utf8 ? (Utf8)k0 : null);
          java.lang.CharSequence v0 = null;
          v0 = in.readString(v0 instanceof Utf8 ? (Utf8)v0 : null);
          m0.put(k0, v0);
        }
      }

    } else {
      for (int i = 0; i < 27; i++) {
        switch (fieldOrder[i].pos()) {
        case 0:
          this.adId = in.readString(this.adId instanceof Utf8 ? (Utf8)this.adId : null);
          break;

        case 1:
          this.appId = in.readString(this.appId instanceof Utf8 ? (Utf8)this.appId : null);
          break;

        case 2:
          this.dspId = in.readString(this.dspId instanceof Utf8 ? (Utf8)this.dspId : null);
          break;

        case 3:
          this.os = in.readString(this.os instanceof Utf8 ? (Utf8)this.os : null);
          break;

        case 4:
          this.positionId = in.readString(this.positionId instanceof Utf8 ? (Utf8)this.positionId : null);
          break;

        case 5:
          this.positionName = in.readString(this.positionName instanceof Utf8 ? (Utf8)this.positionName : null);
          break;

        case 6:
          this.success = in.readInt();
          break;

        case 7:
          if (in.readIndex() != 1) {
            in.readNull();
            this.requestTime = null;
          } else {
            this.requestTime = in.readLong();
          }
          break;

        case 8:
          if (in.readIndex() != 1) {
            in.readNull();
            this.responseTime = null;
          } else {
            this.responseTime = in.readLong();
          }
          break;

        case 9:
          this.msg = in.readString(this.msg instanceof Utf8 ? (Utf8)this.msg : null);
          break;

        case 10:
          if (in.readIndex() != 1) {
            in.readNull();
            this.externalAdId = null;
          } else {
            this.externalAdId = in.readString(this.externalAdId instanceof Utf8 ? (Utf8)this.externalAdId : null);
          }
          break;

        case 11:
          if (in.readIndex() != 1) {
            in.readNull();
            this.ip = null;
          } else {
            this.ip = in.readString(this.ip instanceof Utf8 ? (Utf8)this.ip : null);
          }
          break;

        case 12:
          this.wakeupBoot = in.readInt();
          break;

        case 13:
          if (in.readIndex() != 1) {
            in.readNull();
            this.winFlag = null;
          } else {
            this.winFlag = in.readInt();
          }
          break;

        case 14:
          if (in.readIndex() != 1) {
            in.readNull();
            this.la = null;
          } else {
            this.la = in.readString(this.la instanceof Utf8 ? (Utf8)this.la : null);
          }
          break;

        case 15:
          if (in.readIndex() != 1) {
            in.readNull();
            this.lo = null;
          } else {
            this.lo = in.readString(this.lo instanceof Utf8 ? (Utf8)this.lo : null);
          }
          break;

        case 16:
          if (in.readIndex() != 1) {
            in.readNull();
            this.version = null;
          } else {
            this.version = in.readString(this.version instanceof Utf8 ? (Utf8)this.version : null);
          }
          break;

        case 17:
          if (in.readIndex() != 1) {
            in.readNull();
            this.uuid = null;
          } else {
            this.uuid = in.readString(this.uuid instanceof Utf8 ? (Utf8)this.uuid : null);
          }
          break;

        case 18:
          if (in.readIndex() != 1) {
            in.readNull();
            this.banwords = null;
          } else {
            this.banwords = in.readString(this.banwords instanceof Utf8 ? (Utf8)this.banwords : null);
          }
          break;

        case 19:
          if (in.readIndex() != 1) {
            in.readNull();
            this.reqId = null;
          } else {
            this.reqId = in.readString(this.reqId instanceof Utf8 ? (Utf8)this.reqId : null);
          }
          break;

        case 20:
          if (in.readIndex() != 1) {
            in.readNull();
            this.industryId = null;
          } else {
            this.industryId = in.readString(this.industryId instanceof Utf8 ? (Utf8)this.industryId : null);
          }
          break;

        case 21:
          if (in.readIndex() != 1) {
            in.readNull();
            this.slotId = null;
          } else {
            this.slotId = in.readString(this.slotId instanceof Utf8 ? (Utf8)this.slotId : null);
          }
          break;

        case 22:
          if (in.readIndex() != 1) {
            in.readNull();
            this.advertiser_type = null;
          } else {
            this.advertiser_type = in.readString(this.advertiser_type instanceof Utf8 ? (Utf8)this.advertiser_type : null);
          }
          break;

        case 23:
          if (in.readIndex() != 1) {
            in.readNull();
            this.price = null;
          } else {
            this.price = in.readDouble();
          }
          break;

        case 24:
          if (in.readIndex() != 1) {
            in.readNull();
            this.blogId = null;
          } else {
            this.blogId = in.readLong();
          }
          break;

        case 25:
          if (in.readIndex() != 1) {
            in.readNull();
            this.bidFactor = null;
          } else {
            this.bidFactor = in.readDouble();
          }
          break;

        case 26:
          long size0 = in.readMapStart();
          java.util.Map<java.lang.CharSequence,java.lang.CharSequence> m0 = this.ext; // Need fresh name due to limitation of macro system
          if (m0 == null) {
            m0 = new java.util.HashMap<java.lang.CharSequence,java.lang.CharSequence>((int)size0);
            this.ext = m0;
          } else m0.clear();
          for ( ; 0 < size0; size0 = in.mapNext()) {
            for ( ; size0 != 0; size0--) {
              java.lang.CharSequence k0 = null;
              k0 = in.readString(k0 instanceof Utf8 ? (Utf8)k0 : null);
              java.lang.CharSequence v0 = null;
              v0 = in.readString(v0 instanceof Utf8 ? (Utf8)v0 : null);
              m0.put(k0, v0);
            }
          }
          break;

        default:
          throw new java.io.IOException("Corrupt ResolvingDecoder.");
        }
      }
    }
  }
}










