/**
 * Autogenerated by Avro
 *
 * <p>DO NOT EDIT DIRECTLY
 */
package com.netease.wm.hubble.avro;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;
import org.apache.avro.util.Utf8;

@org.apache.avro.specific.AvroGenerated
public class AdxMonitorEvent extends org.apache.avro.specific.SpecificRecordBase
        implements org.apache.avro.specific.SpecificRecord {
    private static final long serialVersionUID = -8766444965530271798L;

    public static final org.apache.avro.Schema SCHEMA$ =
            new org.apache.avro.Schema.Parser()
                    .parse(
                            "{\"type\":\"record\",\"name\":\"AdxMonitorEvent\",\"namespace\":\"com.netease.wm.hubble.avro\",\"fields\":[{\"name\":\"app\",\"type\":\"string\"},{\"name\":\"deviceUdid\",\"type\":\"string\"},{\"name\":\"deviceOs\",\"type\":\"string\"},{\"name\":\"adId\",\"type\":\"string\"},{\"name\":\"adSource\",\"type\":\"string\"},{\"name\":\"requestUuid\",\"type\":\"string\"},{\"name\":\"adPosition\",\"type\":\"long\"},{\"name\":\"time\",\"type\":\"long\"},{\"name\":\"click\",\"type\":\"long\"},{\"name\":\"expose\",\"type\":\"long\"},{\"name\":\"appVersion\",\"type\":\"string\"},{\"name\":\"adCallTime\",\"type\":\"long\"},{\"name\":\"pos\",\"type\":[\"null\",\"int\"]},{\"name\":\"adTrace\",\"type\":[\"null\",\"string\"]},{\"name\":\"adTraceName\",\"type\":[\"null\",\"string\"]},{\"name\":\"reqId\",\"type\":[\"null\",\"string\"]}]}");

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    private static final SpecificData MODEL$ = new SpecificData();

    private static final BinaryMessageEncoder<AdxMonitorEvent> ENCODER =
            new BinaryMessageEncoder<>(MODEL$, SCHEMA$);

    private static final BinaryMessageDecoder<AdxMonitorEvent> DECODER =
            new BinaryMessageDecoder<>(MODEL$, SCHEMA$);

    /**
     * Return the BinaryMessageEncoder instance used by this class.
     *
     * @return the message encoder used by this class
     */
    public static BinaryMessageEncoder<AdxMonitorEvent> getEncoder() {
        return ENCODER;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     *
     * @return the message decoder used by this class
     */
    public static BinaryMessageDecoder<AdxMonitorEvent> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link
     * SchemaStore}.
     *
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
     */
    public static BinaryMessageDecoder<AdxMonitorEvent> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
    }

    /**
     * Serializes this AdxMonitorEvent to a ByteBuffer.
     *
     * @return a buffer holding the serialized data for this instance
     * @throws java.io.IOException if this instance could not be serialized
     */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    /**
     * Deserializes a AdxMonitorEvent from a ByteBuffer.
     *
     * @param b a byte buffer holding serialized data for an instance of this class
     * @return a AdxMonitorEvent instance decoded from the given buffer
     * @throws java.io.IOException if the given bytes could not be deserialized into an instance of
     *     this class
     */
    public static AdxMonitorEvent fromByteBuffer(java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    private CharSequence app;
    private CharSequence deviceUdid;
    private CharSequence deviceOs;
    private CharSequence adId;
    private CharSequence adSource;
    private CharSequence requestUuid;
    private long adPosition;
    private long time;
    private long click;
    private long expose;
    private CharSequence appVersion;
    private long adCallTime;
    private Integer pos;
    private CharSequence adTrace;
    private CharSequence adTraceName;
    private CharSequence reqId;

    /**
     * Default constructor. Note that this does not initialize fields to their default values from
     * the schema. If that is desired then one should use <code>newBuilder()</code>.
     */
    public AdxMonitorEvent() {}

    /**
     * All-args constructor.
     *
     * @param app The new value for app
     * @param deviceUdid The new value for deviceUdid
     * @param deviceOs The new value for deviceOs
     * @param adId The new value for adId
     * @param adSource The new value for adSource
     * @param requestUuid The new value for requestUuid
     * @param adPosition The new value for adPosition
     * @param time The new value for time
     * @param click The new value for click
     * @param expose The new value for expose
     * @param appVersion The new value for appVersion
     * @param adCallTime The new value for adCallTime
     * @param pos The new value for pos
     * @param adTrace The new value for adTrace
     * @param adTraceName The new value for adTraceName
     * @param reqId The new value for reqId
     */
    public AdxMonitorEvent(
            CharSequence app,
            CharSequence deviceUdid,
            CharSequence deviceOs,
            CharSequence adId,
            CharSequence adSource,
            CharSequence requestUuid,
            Long adPosition,
            Long time,
            Long click,
            Long expose,
            CharSequence appVersion,
            Long adCallTime,
            Integer pos,
            CharSequence adTrace,
            CharSequence adTraceName,
            CharSequence reqId) {
        this.app = app;
        this.deviceUdid = deviceUdid;
        this.deviceOs = deviceOs;
        this.adId = adId;
        this.adSource = adSource;
        this.requestUuid = requestUuid;
        this.adPosition = adPosition;
        this.time = time;
        this.click = click;
        this.expose = expose;
        this.appVersion = appVersion;
        this.adCallTime = adCallTime;
        this.pos = pos;
        this.adTrace = adTrace;
        this.adTraceName = adTraceName;
        this.reqId = reqId;
    }

    @Override
    public SpecificData getSpecificData() {
        return MODEL$;
    }

    @Override
    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    @Override
    public Object get(int field$) {
        switch (field$) {
            case 0:
                return app;
            case 1:
                return deviceUdid;
            case 2:
                return deviceOs;
            case 3:
                return adId;
            case 4:
                return adSource;
            case 5:
                return requestUuid;
            case 6:
                return adPosition;
            case 7:
                return time;
            case 8:
                return click;
            case 9:
                return expose;
            case 10:
                return appVersion;
            case 11:
                return adCallTime;
            case 12:
                return pos;
            case 13:
                return adTrace;
            case 14:
                return adTraceName;
            case 15:
                return reqId;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    // Used by DatumReader.  Applications should not call.
    @Override
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, Object value$) {
        switch (field$) {
            case 0:
                app = (CharSequence) value$;
                break;
            case 1:
                deviceUdid = (CharSequence) value$;
                break;
            case 2:
                deviceOs = (CharSequence) value$;
                break;
            case 3:
                adId = (CharSequence) value$;
                break;
            case 4:
                adSource = (CharSequence) value$;
                break;
            case 5:
                requestUuid = (CharSequence) value$;
                break;
            case 6:
                adPosition = (Long) value$;
                break;
            case 7:
                time = (Long) value$;
                break;
            case 8:
                click = (Long) value$;
                break;
            case 9:
                expose = (Long) value$;
                break;
            case 10:
                appVersion = (CharSequence) value$;
                break;
            case 11:
                adCallTime = (Long) value$;
                break;
            case 12:
                pos = (Integer) value$;
                break;
            case 13:
                adTrace = (CharSequence) value$;
                break;
            case 14:
                adTraceName = (CharSequence) value$;
                break;
            case 15:
                reqId = (CharSequence) value$;
                break;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    /**
     * Gets the value of the 'app' field.
     *
     * @return The value of the 'app' field.
     */
    public CharSequence getApp() {
        return app;
    }

    /**
     * Sets the value of the 'app' field.
     *
     * @param value the value to set.
     */
    public void setApp(CharSequence value) {
        this.app = value;
    }

    /**
     * Gets the value of the 'deviceUdid' field.
     *
     * @return The value of the 'deviceUdid' field.
     */
    public CharSequence getDeviceUdid() {
        return deviceUdid;
    }

    /**
     * Sets the value of the 'deviceUdid' field.
     *
     * @param value the value to set.
     */
    public void setDeviceUdid(CharSequence value) {
        this.deviceUdid = value;
    }

    /**
     * Gets the value of the 'deviceOs' field.
     *
     * @return The value of the 'deviceOs' field.
     */
    public CharSequence getDeviceOs() {
        return deviceOs;
    }

    /**
     * Sets the value of the 'deviceOs' field.
     *
     * @param value the value to set.
     */
    public void setDeviceOs(CharSequence value) {
        this.deviceOs = value;
    }

    /**
     * Gets the value of the 'adId' field.
     *
     * @return The value of the 'adId' field.
     */
    public CharSequence getAdId() {
        return adId;
    }

    /**
     * Sets the value of the 'adId' field.
     *
     * @param value the value to set.
     */
    public void setAdId(CharSequence value) {
        this.adId = value;
    }

    /**
     * Gets the value of the 'adSource' field.
     *
     * @return The value of the 'adSource' field.
     */
    public CharSequence getAdSource() {
        return adSource;
    }

    /**
     * Sets the value of the 'adSource' field.
     *
     * @param value the value to set.
     */
    public void setAdSource(CharSequence value) {
        this.adSource = value;
    }

    /**
     * Gets the value of the 'requestUuid' field.
     *
     * @return The value of the 'requestUuid' field.
     */
    public CharSequence getRequestUuid() {
        return requestUuid;
    }

    /**
     * Sets the value of the 'requestUuid' field.
     *
     * @param value the value to set.
     */
    public void setRequestUuid(CharSequence value) {
        this.requestUuid = value;
    }

    /**
     * Gets the value of the 'adPosition' field.
     *
     * @return The value of the 'adPosition' field.
     */
    public long getAdPosition() {
        return adPosition;
    }

    /**
     * Sets the value of the 'adPosition' field.
     *
     * @param value the value to set.
     */
    public void setAdPosition(long value) {
        this.adPosition = value;
    }

    /**
     * Gets the value of the 'time' field.
     *
     * @return The value of the 'time' field.
     */
    public long getTime() {
        return time;
    }

    /**
     * Sets the value of the 'time' field.
     *
     * @param value the value to set.
     */
    public void setTime(long value) {
        this.time = value;
    }

    /**
     * Gets the value of the 'click' field.
     *
     * @return The value of the 'click' field.
     */
    public long getClick() {
        return click;
    }

    /**
     * Sets the value of the 'click' field.
     *
     * @param value the value to set.
     */
    public void setClick(long value) {
        this.click = value;
    }

    /**
     * Gets the value of the 'expose' field.
     *
     * @return The value of the 'expose' field.
     */
    public long getExpose() {
        return expose;
    }

    /**
     * Sets the value of the 'expose' field.
     *
     * @param value the value to set.
     */
    public void setExpose(long value) {
        this.expose = value;
    }

    /**
     * Gets the value of the 'appVersion' field.
     *
     * @return The value of the 'appVersion' field.
     */
    public CharSequence getAppVersion() {
        return appVersion;
    }

    /**
     * Sets the value of the 'appVersion' field.
     *
     * @param value the value to set.
     */
    public void setAppVersion(CharSequence value) {
        this.appVersion = value;
    }

    /**
     * Gets the value of the 'adCallTime' field.
     *
     * @return The value of the 'adCallTime' field.
     */
    public long getAdCallTime() {
        return adCallTime;
    }

    /**
     * Sets the value of the 'adCallTime' field.
     *
     * @param value the value to set.
     */
    public void setAdCallTime(long value) {
        this.adCallTime = value;
    }

    /**
     * Gets the value of the 'pos' field.
     *
     * @return The value of the 'pos' field.
     */
    public Integer getPos() {
        return pos;
    }

    /**
     * Sets the value of the 'pos' field.
     *
     * @param value the value to set.
     */
    public void setPos(Integer value) {
        this.pos = value;
    }

    /**
     * Gets the value of the 'adTrace' field.
     *
     * @return The value of the 'adTrace' field.
     */
    public CharSequence getAdTrace() {
        return adTrace;
    }

    /**
     * Sets the value of the 'adTrace' field.
     *
     * @param value the value to set.
     */
    public void setAdTrace(CharSequence value) {
        this.adTrace = value;
    }

    /**
     * Gets the value of the 'adTraceName' field.
     *
     * @return The value of the 'adTraceName' field.
     */
    public CharSequence getAdTraceName() {
        return adTraceName;
    }

    /**
     * Sets the value of the 'adTraceName' field.
     *
     * @param value the value to set.
     */
    public void setAdTraceName(CharSequence value) {
        this.adTraceName = value;
    }

    /**
     * Gets the value of the 'reqId' field.
     *
     * @return The value of the 'reqId' field.
     */
    public CharSequence getReqId() {
        return reqId;
    }

    /**
     * Sets the value of the 'reqId' field.
     *
     * @param value the value to set.
     */
    public void setReqId(CharSequence value) {
        this.reqId = value;
    }

    /**
     * Creates a new AdxMonitorEvent RecordBuilder.
     *
     * @return A new AdxMonitorEvent RecordBuilder
     */
    public static Builder newBuilder() {
        return new Builder();
    }

    /**
     * Creates a new AdxMonitorEvent RecordBuilder by copying an existing Builder.
     *
     * @param other The existing builder to copy.
     * @return A new AdxMonitorEvent RecordBuilder
     */
    public static Builder newBuilder(Builder other) {
        if (other == null) {
            return new Builder();
        } else {
            return new Builder(other);
        }
    }

    /**
     * Creates a new AdxMonitorEvent RecordBuilder by copying an existing AdxMonitorEvent instance.
     *
     * @param other The existing instance to copy.
     * @return A new AdxMonitorEvent RecordBuilder
     */
    public static Builder newBuilder(AdxMonitorEvent other) {
        if (other == null) {
            return new Builder();
        } else {
            return new Builder(other);
        }
    }

    /** RecordBuilder for AdxMonitorEvent instances. */
    @org.apache.avro.specific.AvroGenerated
    public static class Builder
            extends org.apache.avro.specific.SpecificRecordBuilderBase<AdxMonitorEvent>
            implements org.apache.avro.data.RecordBuilder<AdxMonitorEvent> {

        private CharSequence app;
        private CharSequence deviceUdid;
        private CharSequence deviceOs;
        private CharSequence adId;
        private CharSequence adSource;
        private CharSequence requestUuid;
        private long adPosition;
        private long time;
        private long click;
        private long expose;
        private CharSequence appVersion;
        private long adCallTime;
        private Integer pos;
        private CharSequence adTrace;
        private CharSequence adTraceName;
        private CharSequence reqId;

        /** Creates a new Builder */
        private Builder() {
            super(SCHEMA$, MODEL$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         *
         * @param other The existing Builder to copy.
         */
        private Builder(Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.app)) {
                this.app = data().deepCopy(fields()[0].schema(), other.app);
                fieldSetFlags()[0] = other.fieldSetFlags()[0];
            }
            if (isValidValue(fields()[1], other.deviceUdid)) {
                this.deviceUdid = data().deepCopy(fields()[1].schema(), other.deviceUdid);
                fieldSetFlags()[1] = other.fieldSetFlags()[1];
            }
            if (isValidValue(fields()[2], other.deviceOs)) {
                this.deviceOs = data().deepCopy(fields()[2].schema(), other.deviceOs);
                fieldSetFlags()[2] = other.fieldSetFlags()[2];
            }
            if (isValidValue(fields()[3], other.adId)) {
                this.adId = data().deepCopy(fields()[3].schema(), other.adId);
                fieldSetFlags()[3] = other.fieldSetFlags()[3];
            }
            if (isValidValue(fields()[4], other.adSource)) {
                this.adSource = data().deepCopy(fields()[4].schema(), other.adSource);
                fieldSetFlags()[4] = other.fieldSetFlags()[4];
            }
            if (isValidValue(fields()[5], other.requestUuid)) {
                this.requestUuid = data().deepCopy(fields()[5].schema(), other.requestUuid);
                fieldSetFlags()[5] = other.fieldSetFlags()[5];
            }
            if (isValidValue(fields()[6], other.adPosition)) {
                this.adPosition = data().deepCopy(fields()[6].schema(), other.adPosition);
                fieldSetFlags()[6] = other.fieldSetFlags()[6];
            }
            if (isValidValue(fields()[7], other.time)) {
                this.time = data().deepCopy(fields()[7].schema(), other.time);
                fieldSetFlags()[7] = other.fieldSetFlags()[7];
            }
            if (isValidValue(fields()[8], other.click)) {
                this.click = data().deepCopy(fields()[8].schema(), other.click);
                fieldSetFlags()[8] = other.fieldSetFlags()[8];
            }
            if (isValidValue(fields()[9], other.expose)) {
                this.expose = data().deepCopy(fields()[9].schema(), other.expose);
                fieldSetFlags()[9] = other.fieldSetFlags()[9];
            }
            if (isValidValue(fields()[10], other.appVersion)) {
                this.appVersion = data().deepCopy(fields()[10].schema(), other.appVersion);
                fieldSetFlags()[10] = other.fieldSetFlags()[10];
            }
            if (isValidValue(fields()[11], other.adCallTime)) {
                this.adCallTime = data().deepCopy(fields()[11].schema(), other.adCallTime);
                fieldSetFlags()[11] = other.fieldSetFlags()[11];
            }
            if (isValidValue(fields()[12], other.pos)) {
                this.pos = data().deepCopy(fields()[12].schema(), other.pos);
                fieldSetFlags()[12] = other.fieldSetFlags()[12];
            }
            if (isValidValue(fields()[13], other.adTrace)) {
                this.adTrace = data().deepCopy(fields()[13].schema(), other.adTrace);
                fieldSetFlags()[13] = other.fieldSetFlags()[13];
            }
            if (isValidValue(fields()[14], other.adTraceName)) {
                this.adTraceName = data().deepCopy(fields()[14].schema(), other.adTraceName);
                fieldSetFlags()[14] = other.fieldSetFlags()[14];
            }
            if (isValidValue(fields()[15], other.reqId)) {
                this.reqId = data().deepCopy(fields()[15].schema(), other.reqId);
                fieldSetFlags()[15] = other.fieldSetFlags()[15];
            }
        }

        /**
         * Creates a Builder by copying an existing AdxMonitorEvent instance
         *
         * @param other The existing instance to copy.
         */
        private Builder(AdxMonitorEvent other) {
            super(SCHEMA$, MODEL$);
            if (isValidValue(fields()[0], other.app)) {
                this.app = data().deepCopy(fields()[0].schema(), other.app);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.deviceUdid)) {
                this.deviceUdid = data().deepCopy(fields()[1].schema(), other.deviceUdid);
                fieldSetFlags()[1] = true;
            }
            if (isValidValue(fields()[2], other.deviceOs)) {
                this.deviceOs = data().deepCopy(fields()[2].schema(), other.deviceOs);
                fieldSetFlags()[2] = true;
            }
            if (isValidValue(fields()[3], other.adId)) {
                this.adId = data().deepCopy(fields()[3].schema(), other.adId);
                fieldSetFlags()[3] = true;
            }
            if (isValidValue(fields()[4], other.adSource)) {
                this.adSource = data().deepCopy(fields()[4].schema(), other.adSource);
                fieldSetFlags()[4] = true;
            }
            if (isValidValue(fields()[5], other.requestUuid)) {
                this.requestUuid = data().deepCopy(fields()[5].schema(), other.requestUuid);
                fieldSetFlags()[5] = true;
            }
            if (isValidValue(fields()[6], other.adPosition)) {
                this.adPosition = data().deepCopy(fields()[6].schema(), other.adPosition);
                fieldSetFlags()[6] = true;
            }
            if (isValidValue(fields()[7], other.time)) {
                this.time = data().deepCopy(fields()[7].schema(), other.time);
                fieldSetFlags()[7] = true;
            }
            if (isValidValue(fields()[8], other.click)) {
                this.click = data().deepCopy(fields()[8].schema(), other.click);
                fieldSetFlags()[8] = true;
            }
            if (isValidValue(fields()[9], other.expose)) {
                this.expose = data().deepCopy(fields()[9].schema(), other.expose);
                fieldSetFlags()[9] = true;
            }
            if (isValidValue(fields()[10], other.appVersion)) {
                this.appVersion = data().deepCopy(fields()[10].schema(), other.appVersion);
                fieldSetFlags()[10] = true;
            }
            if (isValidValue(fields()[11], other.adCallTime)) {
                this.adCallTime = data().deepCopy(fields()[11].schema(), other.adCallTime);
                fieldSetFlags()[11] = true;
            }
            if (isValidValue(fields()[12], other.pos)) {
                this.pos = data().deepCopy(fields()[12].schema(), other.pos);
                fieldSetFlags()[12] = true;
            }
            if (isValidValue(fields()[13], other.adTrace)) {
                this.adTrace = data().deepCopy(fields()[13].schema(), other.adTrace);
                fieldSetFlags()[13] = true;
            }
            if (isValidValue(fields()[14], other.adTraceName)) {
                this.adTraceName = data().deepCopy(fields()[14].schema(), other.adTraceName);
                fieldSetFlags()[14] = true;
            }
            if (isValidValue(fields()[15], other.reqId)) {
                this.reqId = data().deepCopy(fields()[15].schema(), other.reqId);
                fieldSetFlags()[15] = true;
            }
        }

        /**
         * Gets the value of the 'app' field.
         *
         * @return The value.
         */
        public CharSequence getApp() {
            return app;
        }

        /**
         * Sets the value of the 'app' field.
         *
         * @param value The value of 'app'.
         * @return This builder.
         */
        public Builder setApp(CharSequence value) {
            validate(fields()[0], value);
            this.app = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'app' field has been set.
         *
         * @return True if the 'app' field has been set, false otherwise.
         */
        public boolean hasApp() {
            return fieldSetFlags()[0];
        }

        /**
         * Clears the value of the 'app' field.
         *
         * @return This builder.
         */
        public Builder clearApp() {
            app = null;
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'deviceUdid' field.
         *
         * @return The value.
         */
        public CharSequence getDeviceUdid() {
            return deviceUdid;
        }

        /**
         * Sets the value of the 'deviceUdid' field.
         *
         * @param value The value of 'deviceUdid'.
         * @return This builder.
         */
        public Builder setDeviceUdid(CharSequence value) {
            validate(fields()[1], value);
            this.deviceUdid = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'deviceUdid' field has been set.
         *
         * @return True if the 'deviceUdid' field has been set, false otherwise.
         */
        public boolean hasDeviceUdid() {
            return fieldSetFlags()[1];
        }

        /**
         * Clears the value of the 'deviceUdid' field.
         *
         * @return This builder.
         */
        public Builder clearDeviceUdid() {
            deviceUdid = null;
            fieldSetFlags()[1] = false;
            return this;
        }

        /**
         * Gets the value of the 'deviceOs' field.
         *
         * @return The value.
         */
        public CharSequence getDeviceOs() {
            return deviceOs;
        }

        /**
         * Sets the value of the 'deviceOs' field.
         *
         * @param value The value of 'deviceOs'.
         * @return This builder.
         */
        public Builder setDeviceOs(CharSequence value) {
            validate(fields()[2], value);
            this.deviceOs = value;
            fieldSetFlags()[2] = true;
            return this;
        }

        /**
         * Checks whether the 'deviceOs' field has been set.
         *
         * @return True if the 'deviceOs' field has been set, false otherwise.
         */
        public boolean hasDeviceOs() {
            return fieldSetFlags()[2];
        }

        /**
         * Clears the value of the 'deviceOs' field.
         *
         * @return This builder.
         */
        public Builder clearDeviceOs() {
            deviceOs = null;
            fieldSetFlags()[2] = false;
            return this;
        }

        /**
         * Gets the value of the 'adId' field.
         *
         * @return The value.
         */
        public CharSequence getAdId() {
            return adId;
        }

        /**
         * Sets the value of the 'adId' field.
         *
         * @param value The value of 'adId'.
         * @return This builder.
         */
        public Builder setAdId(CharSequence value) {
            validate(fields()[3], value);
            this.adId = value;
            fieldSetFlags()[3] = true;
            return this;
        }

        /**
         * Checks whether the 'adId' field has been set.
         *
         * @return True if the 'adId' field has been set, false otherwise.
         */
        public boolean hasAdId() {
            return fieldSetFlags()[3];
        }

        /**
         * Clears the value of the 'adId' field.
         *
         * @return This builder.
         */
        public Builder clearAdId() {
            adId = null;
            fieldSetFlags()[3] = false;
            return this;
        }

        /**
         * Gets the value of the 'adSource' field.
         *
         * @return The value.
         */
        public CharSequence getAdSource() {
            return adSource;
        }

        /**
         * Sets the value of the 'adSource' field.
         *
         * @param value The value of 'adSource'.
         * @return This builder.
         */
        public Builder setAdSource(CharSequence value) {
            validate(fields()[4], value);
            this.adSource = value;
            fieldSetFlags()[4] = true;
            return this;
        }

        /**
         * Checks whether the 'adSource' field has been set.
         *
         * @return True if the 'adSource' field has been set, false otherwise.
         */
        public boolean hasAdSource() {
            return fieldSetFlags()[4];
        }

        /**
         * Clears the value of the 'adSource' field.
         *
         * @return This builder.
         */
        public Builder clearAdSource() {
            adSource = null;
            fieldSetFlags()[4] = false;
            return this;
        }

        /**
         * Gets the value of the 'requestUuid' field.
         *
         * @return The value.
         */
        public CharSequence getRequestUuid() {
            return requestUuid;
        }

        /**
         * Sets the value of the 'requestUuid' field.
         *
         * @param value The value of 'requestUuid'.
         * @return This builder.
         */
        public Builder setRequestUuid(CharSequence value) {
            validate(fields()[5], value);
            this.requestUuid = value;
            fieldSetFlags()[5] = true;
            return this;
        }

        /**
         * Checks whether the 'requestUuid' field has been set.
         *
         * @return True if the 'requestUuid' field has been set, false otherwise.
         */
        public boolean hasRequestUuid() {
            return fieldSetFlags()[5];
        }

        /**
         * Clears the value of the 'requestUuid' field.
         *
         * @return This builder.
         */
        public Builder clearRequestUuid() {
            requestUuid = null;
            fieldSetFlags()[5] = false;
            return this;
        }

        /**
         * Gets the value of the 'adPosition' field.
         *
         * @return The value.
         */
        public long getAdPosition() {
            return adPosition;
        }

        /**
         * Sets the value of the 'adPosition' field.
         *
         * @param value The value of 'adPosition'.
         * @return This builder.
         */
        public Builder setAdPosition(long value) {
            validate(fields()[6], value);
            this.adPosition = value;
            fieldSetFlags()[6] = true;
            return this;
        }

        /**
         * Checks whether the 'adPosition' field has been set.
         *
         * @return True if the 'adPosition' field has been set, false otherwise.
         */
        public boolean hasAdPosition() {
            return fieldSetFlags()[6];
        }

        /**
         * Clears the value of the 'adPosition' field.
         *
         * @return This builder.
         */
        public Builder clearAdPosition() {
            fieldSetFlags()[6] = false;
            return this;
        }

        /**
         * Gets the value of the 'time' field.
         *
         * @return The value.
         */
        public long getTime() {
            return time;
        }

        /**
         * Sets the value of the 'time' field.
         *
         * @param value The value of 'time'.
         * @return This builder.
         */
        public Builder setTime(long value) {
            validate(fields()[7], value);
            this.time = value;
            fieldSetFlags()[7] = true;
            return this;
        }

        /**
         * Checks whether the 'time' field has been set.
         *
         * @return True if the 'time' field has been set, false otherwise.
         */
        public boolean hasTime() {
            return fieldSetFlags()[7];
        }

        /**
         * Clears the value of the 'time' field.
         *
         * @return This builder.
         */
        public Builder clearTime() {
            fieldSetFlags()[7] = false;
            return this;
        }

        /**
         * Gets the value of the 'click' field.
         *
         * @return The value.
         */
        public long getClick() {
            return click;
        }

        /**
         * Sets the value of the 'click' field.
         *
         * @param value The value of 'click'.
         * @return This builder.
         */
        public Builder setClick(long value) {
            validate(fields()[8], value);
            this.click = value;
            fieldSetFlags()[8] = true;
            return this;
        }

        /**
         * Checks whether the 'click' field has been set.
         *
         * @return True if the 'click' field has been set, false otherwise.
         */
        public boolean hasClick() {
            return fieldSetFlags()[8];
        }

        /**
         * Clears the value of the 'click' field.
         *
         * @return This builder.
         */
        public Builder clearClick() {
            fieldSetFlags()[8] = false;
            return this;
        }

        /**
         * Gets the value of the 'expose' field.
         *
         * @return The value.
         */
        public long getExpose() {
            return expose;
        }

        /**
         * Sets the value of the 'expose' field.
         *
         * @param value The value of 'expose'.
         * @return This builder.
         */
        public Builder setExpose(long value) {
            validate(fields()[9], value);
            this.expose = value;
            fieldSetFlags()[9] = true;
            return this;
        }

        /**
         * Checks whether the 'expose' field has been set.
         *
         * @return True if the 'expose' field has been set, false otherwise.
         */
        public boolean hasExpose() {
            return fieldSetFlags()[9];
        }

        /**
         * Clears the value of the 'expose' field.
         *
         * @return This builder.
         */
        public Builder clearExpose() {
            fieldSetFlags()[9] = false;
            return this;
        }

        /**
         * Gets the value of the 'appVersion' field.
         *
         * @return The value.
         */
        public CharSequence getAppVersion() {
            return appVersion;
        }

        /**
         * Sets the value of the 'appVersion' field.
         *
         * @param value The value of 'appVersion'.
         * @return This builder.
         */
        public Builder setAppVersion(CharSequence value) {
            validate(fields()[10], value);
            this.appVersion = value;
            fieldSetFlags()[10] = true;
            return this;
        }

        /**
         * Checks whether the 'appVersion' field has been set.
         *
         * @return True if the 'appVersion' field has been set, false otherwise.
         */
        public boolean hasAppVersion() {
            return fieldSetFlags()[10];
        }

        /**
         * Clears the value of the 'appVersion' field.
         *
         * @return This builder.
         */
        public Builder clearAppVersion() {
            appVersion = null;
            fieldSetFlags()[10] = false;
            return this;
        }

        /**
         * Gets the value of the 'adCallTime' field.
         *
         * @return The value.
         */
        public long getAdCallTime() {
            return adCallTime;
        }

        /**
         * Sets the value of the 'adCallTime' field.
         *
         * @param value The value of 'adCallTime'.
         * @return This builder.
         */
        public Builder setAdCallTime(long value) {
            validate(fields()[11], value);
            this.adCallTime = value;
            fieldSetFlags()[11] = true;
            return this;
        }

        /**
         * Checks whether the 'adCallTime' field has been set.
         *
         * @return True if the 'adCallTime' field has been set, false otherwise.
         */
        public boolean hasAdCallTime() {
            return fieldSetFlags()[11];
        }

        /**
         * Clears the value of the 'adCallTime' field.
         *
         * @return This builder.
         */
        public Builder clearAdCallTime() {
            fieldSetFlags()[11] = false;
            return this;
        }

        /**
         * Gets the value of the 'pos' field.
         *
         * @return The value.
         */
        public Integer getPos() {
            return pos;
        }

        /**
         * Sets the value of the 'pos' field.
         *
         * @param value The value of 'pos'.
         * @return This builder.
         */
        public Builder setPos(Integer value) {
            validate(fields()[12], value);
            this.pos = value;
            fieldSetFlags()[12] = true;
            return this;
        }

        /**
         * Checks whether the 'pos' field has been set.
         *
         * @return True if the 'pos' field has been set, false otherwise.
         */
        public boolean hasPos() {
            return fieldSetFlags()[12];
        }

        /**
         * Clears the value of the 'pos' field.
         *
         * @return This builder.
         */
        public Builder clearPos() {
            pos = null;
            fieldSetFlags()[12] = false;
            return this;
        }

        /**
         * Gets the value of the 'adTrace' field.
         *
         * @return The value.
         */
        public CharSequence getAdTrace() {
            return adTrace;
        }

        /**
         * Sets the value of the 'adTrace' field.
         *
         * @param value The value of 'adTrace'.
         * @return This builder.
         */
        public Builder setAdTrace(CharSequence value) {
            validate(fields()[13], value);
            this.adTrace = value;
            fieldSetFlags()[13] = true;
            return this;
        }

        /**
         * Checks whether the 'adTrace' field has been set.
         *
         * @return True if the 'adTrace' field has been set, false otherwise.
         */
        public boolean hasAdTrace() {
            return fieldSetFlags()[13];
        }

        /**
         * Clears the value of the 'adTrace' field.
         *
         * @return This builder.
         */
        public Builder clearAdTrace() {
            adTrace = null;
            fieldSetFlags()[13] = false;
            return this;
        }

        /**
         * Gets the value of the 'adTraceName' field.
         *
         * @return The value.
         */
        public CharSequence getAdTraceName() {
            return adTraceName;
        }

        /**
         * Sets the value of the 'adTraceName' field.
         *
         * @param value The value of 'adTraceName'.
         * @return This builder.
         */
        public Builder setAdTraceName(CharSequence value) {
            validate(fields()[14], value);
            this.adTraceName = value;
            fieldSetFlags()[14] = true;
            return this;
        }

        /**
         * Checks whether the 'adTraceName' field has been set.
         *
         * @return True if the 'adTraceName' field has been set, false otherwise.
         */
        public boolean hasAdTraceName() {
            return fieldSetFlags()[14];
        }

        /**
         * Clears the value of the 'adTraceName' field.
         *
         * @return This builder.
         */
        public Builder clearAdTraceName() {
            adTraceName = null;
            fieldSetFlags()[14] = false;
            return this;
        }

        /**
         * Gets the value of the 'reqId' field.
         *
         * @return The value.
         */
        public CharSequence getReqId() {
            return reqId;
        }

        /**
         * Sets the value of the 'reqId' field.
         *
         * @param value The value of 'reqId'.
         * @return This builder.
         */
        public Builder setReqId(CharSequence value) {
            validate(fields()[15], value);
            this.reqId = value;
            fieldSetFlags()[15] = true;
            return this;
        }

        /**
         * Checks whether the 'reqId' field has been set.
         *
         * @return True if the 'reqId' field has been set, false otherwise.
         */
        public boolean hasReqId() {
            return fieldSetFlags()[15];
        }

        /**
         * Clears the value of the 'reqId' field.
         *
         * @return This builder.
         */
        public Builder clearReqId() {
            reqId = null;
            fieldSetFlags()[15] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public AdxMonitorEvent build() {
            try {
                AdxMonitorEvent record = new AdxMonitorEvent();
                record.app =
                        fieldSetFlags()[0] ? this.app : (CharSequence) defaultValue(fields()[0]);
                record.deviceUdid =
                        fieldSetFlags()[1]
                                ? this.deviceUdid
                                : (CharSequence) defaultValue(fields()[1]);
                record.deviceOs =
                        fieldSetFlags()[2]
                                ? this.deviceOs
                                : (CharSequence) defaultValue(fields()[2]);
                record.adId =
                        fieldSetFlags()[3] ? this.adId : (CharSequence) defaultValue(fields()[3]);
                record.adSource =
                        fieldSetFlags()[4]
                                ? this.adSource
                                : (CharSequence) defaultValue(fields()[4]);
                record.requestUuid =
                        fieldSetFlags()[5]
                                ? this.requestUuid
                                : (CharSequence) defaultValue(fields()[5]);
                record.adPosition =
                        fieldSetFlags()[6] ? this.adPosition : (Long) defaultValue(fields()[6]);
                record.time = fieldSetFlags()[7] ? this.time : (Long) defaultValue(fields()[7]);
                record.click = fieldSetFlags()[8] ? this.click : (Long) defaultValue(fields()[8]);
                record.expose = fieldSetFlags()[9] ? this.expose : (Long) defaultValue(fields()[9]);
                record.appVersion =
                        fieldSetFlags()[10]
                                ? this.appVersion
                                : (CharSequence) defaultValue(fields()[10]);
                record.adCallTime =
                        fieldSetFlags()[11] ? this.adCallTime : (Long) defaultValue(fields()[11]);
                record.pos = fieldSetFlags()[12] ? this.pos : (Integer) defaultValue(fields()[12]);
                record.adTrace =
                        fieldSetFlags()[13]
                                ? this.adTrace
                                : (CharSequence) defaultValue(fields()[13]);
                record.adTraceName =
                        fieldSetFlags()[14]
                                ? this.adTraceName
                                : (CharSequence) defaultValue(fields()[14]);
                record.reqId =
                        fieldSetFlags()[15]
                                ? this.reqId
                                : (CharSequence) defaultValue(fields()[15]);
                return record;
            } catch (org.apache.avro.AvroMissingFieldException e) {
                throw e;
            } catch (Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<AdxMonitorEvent> WRITER$ =
            (org.apache.avro.io.DatumWriter<AdxMonitorEvent>) MODEL$.createDatumWriter(SCHEMA$);

    @Override
    public void writeExternal(java.io.ObjectOutput out) throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<AdxMonitorEvent> READER$ =
            (org.apache.avro.io.DatumReader<AdxMonitorEvent>) MODEL$.createDatumReader(SCHEMA$);

    @Override
    public void readExternal(java.io.ObjectInput in) throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

    @Override
    protected boolean hasCustomCoders() {
        return true;
    }

    @Override
    public void customEncode(org.apache.avro.io.Encoder out) throws java.io.IOException {
        out.writeString(this.app);

        out.writeString(this.deviceUdid);

        out.writeString(this.deviceOs);

        out.writeString(this.adId);

        out.writeString(this.adSource);

        out.writeString(this.requestUuid);

        out.writeLong(this.adPosition);

        out.writeLong(this.time);

        out.writeLong(this.click);

        out.writeLong(this.expose);

        out.writeString(this.appVersion);

        out.writeLong(this.adCallTime);

        if (this.pos == null) {
            out.writeIndex(0);
            out.writeNull();
        } else {
            out.writeIndex(1);
            out.writeInt(this.pos);
        }

        if (this.adTrace == null) {
            out.writeIndex(0);
            out.writeNull();
        } else {
            out.writeIndex(1);
            out.writeString(this.adTrace);
        }

        if (this.adTraceName == null) {
            out.writeIndex(0);
            out.writeNull();
        } else {
            out.writeIndex(1);
            out.writeString(this.adTraceName);
        }

        if (this.reqId == null) {
            out.writeIndex(0);
            out.writeNull();
        } else {
            out.writeIndex(1);
            out.writeString(this.reqId);
        }
    }

    @Override
    public void customDecode(org.apache.avro.io.ResolvingDecoder in) throws java.io.IOException {
        org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
        if (fieldOrder == null) {
            this.app = in.readString(this.app instanceof Utf8 ? (Utf8) this.app : null);

            this.deviceUdid =
                    in.readString(this.deviceUdid instanceof Utf8 ? (Utf8) this.deviceUdid : null);

            this.deviceOs =
                    in.readString(this.deviceOs instanceof Utf8 ? (Utf8) this.deviceOs : null);

            this.adId = in.readString(this.adId instanceof Utf8 ? (Utf8) this.adId : null);

            this.adSource =
                    in.readString(this.adSource instanceof Utf8 ? (Utf8) this.adSource : null);

            this.requestUuid =
                    in.readString(
                            this.requestUuid instanceof Utf8 ? (Utf8) this.requestUuid : null);

            this.adPosition = in.readLong();

            this.time = in.readLong();

            this.click = in.readLong();

            this.expose = in.readLong();

            this.appVersion =
                    in.readString(this.appVersion instanceof Utf8 ? (Utf8) this.appVersion : null);

            this.adCallTime = in.readLong();

            if (in.readIndex() != 1) {
                in.readNull();
                this.pos = null;
            } else {
                this.pos = in.readInt();
            }

            if (in.readIndex() != 1) {
                in.readNull();
                this.adTrace = null;
            } else {
                this.adTrace =
                        in.readString(this.adTrace instanceof Utf8 ? (Utf8) this.adTrace : null);
            }

            if (in.readIndex() != 1) {
                in.readNull();
                this.adTraceName = null;
            } else {
                this.adTraceName =
                        in.readString(
                                this.adTraceName instanceof Utf8 ? (Utf8) this.adTraceName : null);
            }

            if (in.readIndex() != 1) {
                in.readNull();
                this.reqId = null;
            } else {
                this.reqId = in.readString(this.reqId instanceof Utf8 ? (Utf8) this.reqId : null);
            }

        } else {
            for (int i = 0; i < 16; i++) {
                switch (fieldOrder[i].pos()) {
                    case 0:
                        this.app = in.readString(this.app instanceof Utf8 ? (Utf8) this.app : null);
                        break;

                    case 1:
                        this.deviceUdid =
                                in.readString(
                                        this.deviceUdid instanceof Utf8
                                                ? (Utf8) this.deviceUdid
                                                : null);
                        break;

                    case 2:
                        this.deviceOs =
                                in.readString(
                                        this.deviceOs instanceof Utf8
                                                ? (Utf8) this.deviceOs
                                                : null);
                        break;

                    case 3:
                        this.adId =
                                in.readString(this.adId instanceof Utf8 ? (Utf8) this.adId : null);
                        break;

                    case 4:
                        this.adSource =
                                in.readString(
                                        this.adSource instanceof Utf8
                                                ? (Utf8) this.adSource
                                                : null);
                        break;

                    case 5:
                        this.requestUuid =
                                in.readString(
                                        this.requestUuid instanceof Utf8
                                                ? (Utf8) this.requestUuid
                                                : null);
                        break;

                    case 6:
                        this.adPosition = in.readLong();
                        break;

                    case 7:
                        this.time = in.readLong();
                        break;

                    case 8:
                        this.click = in.readLong();
                        break;

                    case 9:
                        this.expose = in.readLong();
                        break;

                    case 10:
                        this.appVersion =
                                in.readString(
                                        this.appVersion instanceof Utf8
                                                ? (Utf8) this.appVersion
                                                : null);
                        break;

                    case 11:
                        this.adCallTime = in.readLong();
                        break;

                    case 12:
                        if (in.readIndex() != 1) {
                            in.readNull();
                            this.pos = null;
                        } else {
                            this.pos = in.readInt();
                        }
                        break;

                    case 13:
                        if (in.readIndex() != 1) {
                            in.readNull();
                            this.adTrace = null;
                        } else {
                            this.adTrace =
                                    in.readString(
                                            this.adTrace instanceof Utf8
                                                    ? (Utf8) this.adTrace
                                                    : null);
                        }
                        break;

                    case 14:
                        if (in.readIndex() != 1) {
                            in.readNull();
                            this.adTraceName = null;
                        } else {
                            this.adTraceName =
                                    in.readString(
                                            this.adTraceName instanceof Utf8
                                                    ? (Utf8) this.adTraceName
                                                    : null);
                        }
                        break;

                    case 15:
                        if (in.readIndex() != 1) {
                            in.readNull();
                            this.reqId = null;
                        } else {
                            this.reqId =
                                    in.readString(
                                            this.reqId instanceof Utf8 ? (Utf8) this.reqId : null);
                        }
                        break;

                    default:
                        throw new java.io.IOException("Corrupt ResolvingDecoder.");
                }
            }
        }
    }
}
