execution-jar=${classpath}
class=com.netease.lofter.etl.common.TagFetchClickhouseLoad
conf.spark.source.query="select dt, daren_bitmap, premium_bitmap, level_s_bitmap, level_a_bitmap, level_b_bitmap, level_c_bitmap, level_d_bitmap, level_d_star_bitmap from lofter.dws_index_user_status_dd where dt = '${azkaban.flow.1.days.ago}' "
params=--dest lofter.tag_fetch_user_status_dd --partition '${azkaban.flow.1.days.ago}'
retries=0
dependencies=dws_index_user_status_dd