execution-jar=${classpath}
class=com.netease.lofter.etl.common.TagFetchClickhouseLoad
conf.spark.source.query="select dt, new_creator_bitmap, return_creator_bitmap, first_publish_creator_bitmap, new_user_bitmap, return_user_bitmap, login_user_bitmap from lofter.dws_index_user_status_di where dt = '${azkaban.flow.1.days.ago}' "
params=--dest lofter.tag_fetch_user_status_di --partition '${azkaban.flow.1.days.ago}'
retries=0
dependencies=dws_index_user_status_di