appName=lofter-service-tango
#instance=default
#isJavaMethodCollectorEnable=false
#isLog4jExceptionEnable=false
# 3 type value, bytecode,filter,none
#urlInterceptorMethod=none
# the url request encoding, utf-8,gbk,gb2312
encoding=utf-8
# maxJavaMethodCount=100
# maxUrlCount=100
# maxExceptionCount=50
# maxStatsToolCount =100
# javaagentRegisterInterval = 300   #javaagent register interval
# javaagentRegisterFailInterval=60
#masterAddressList= 127.0.0.1
#forceMonitorList=127.0.0.1
