type=sparksql
hive.query.01=insert overwrite table lofter_dm.ads_push_task_pool_di partition(dt = '${azkaban.flow.current.date}', executionId= 'return_user_tag_rec') \
select userId, \
       'lofter.push.reback.user' as push_topic, \
       to_json(struct(*)) as push_params, \
       'return_user_tag_rec' as policy, \
       5 as priority, \
       unix_timestamp()*1000L as create_time \
from ( \
    select userId, blogId, postId, tag, hot \
    from lofter_dm.ads_push_return_user_tag_push_di \
    where dt='${azkaban.flow.current.date}' \
) t \

dependencies=ads_push_return_user_tag_push_di
