#easyml.jars.dir=hdfs://hz-cluster8/user/idc/hive_db/hzlinjn.db/data/easyml-0.6.0/jars
easyml.jars.dir=hdfs://gy-cluster8/user/rec/easyml/easyml-1.0.3/jars
easyml.jars.sys.exclude=easyml-common;easyml-launcher;reflections
easyml.jars.exclude=
easyml.dist.jars=

# xgb
easyml.xgb.version=1.5.1

# hanlp
easyml.hanlp.portable=false

# bigdl
easyml.bigdl.enable=false

# angel
easyml.angel.enable=false
#easyml.angel.version=3.1.0
#easyml.angel.home=hdfs://hz-cluster8/user/idc/hive_db/hzlinjn.db/data/angel-${version}/lib
#easyml.angel.jars=scala-library-2.11.8.jar,fastutil-7.1.0.jar,htrace-core-2.05.jar,sizeof-0.3.0.jar,kryo-shaded-4.0.0.jar,minlog-1.3.0.jar,memory-0.8.1.jar,commons-pool-1.6.jar,netty-all-4.1.18.Final.jar,hll-1.6.0.jar,stream-2.7.0.jar,angel-ps-graph-${version}.jar,angel-ps-core-${version}.jar,angel-ps-psf-${version}.jar,angel-ps-mllib-${version}.jar,spark-on-angel-mllib-${version}-ps.jar,spark-on-angel-graph-${version}-ps.jar,spark-on-angel-core-${version}.jar,spark-on-angel-mllib-${version}.jar,spark-on-angel-graph-${version}.jar
easyml.angel.version=3.2.0
easyml.angel.home=hdfs://gy-cluster8/user/rec/easyml/angel-${version}/lib
easyml.angel.jars=easyml-angel-0.6.0-SNAPSHOT.jar,scala-library-2.11.8.jar,fastutil-7.1.0.jar,htrace-core-2.05.jar,sizeof-0.3.0.jar,kryo-shaded-4.0.0.jar,minlog-1.3.0.jar,memory-0.8.1.jar,commons-pool-1.6.jar,netty-all-4.1.42.Final.jar,hll-1.6.0.jar,stream-2.7.0.jar,angel-ps-graph-${version}.jar,angel-ps-core-${version}.jar,angel-ps-psf-${version}.jar,angel-ps-mllib-${version}.jar,spark-on-angel-mllib-${version}-ps.jar,spark-on-angel-graph-${version}-ps.jar,spark-on-angel-core-${version}.jar,spark-on-angel-mllib-${version}.jar,spark-on-angel-graph-${version}.jar

# spark
#fs.defaultFS=hdfs://hz-cluster8
fs.defaultFS=hdfs://gy-cluster8
spark.yarn.maxAppAttempts=1