type=sparksql
hive.query.01=insert overwrite table lofter.dws_par_user_home_visit_di partition(dt = '${azkaban.flow.1.days.ago}') \
select a.userId, b.id as blogId, a.blogName, a.visitCount \
from ( \
    select userId, params['blogname'] blogName, count(1) visitCount \
    from lofter.ods_mda_app_partition_di \
    where dt = '${azkaban.flow.1.days.ago}' and actionType = 'page_view' and eventId ='e2-41'  and \
           length(params['blogname']) > 0 \
    group by userId,blogName \
) a join lofter.dim_blog b on a.blogName = b.blogName \
distribute by 1

dependencies=