type=sparksql
hive.query.01=insert overwrite table lofter.dwd_tag_browse_di partition(dt='${azkaban.flow.1.days.ago}') \
select a.*, b.createDate as user_create_date \
from ( \
    select labelName as tag, cast(accountId as bigint) as userId, \
           cast(time as bigint) as time, clientType as platform, IP as ip, tab \
    from lofter.ods_log_labeldetailpage_di \
    where dt = '${azkaban.flow.1.days.ago}' and length(labelName) > 0 \
) a \
left join lofter.dim_user b on a.userId = b.id \