execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2KafkaPayload
conf.spark.source.query="select blogId, comment_count_std as replyNum, post_count_std as workNum, cast(current_timestamp() as bigint) * 1000 as snapShootTime from lofter_dm.ads_risk_gr_blog_ia_di where dt = '${azkaban.flow.1.days.ago}' "
params= --messageType 10000 --topic GR_BLOG_IA --servers lofter-kafka-bi-risk1.gy.ntes:9092,lofter-kafka-bi-risk2.gy.ntes:9092,lofter-kafka-bi-risk3.gy.ntes:9092,lofter-kafka-bi-risk4.gy.ntes:9092,lofter-kafka-bi-risk5.gy.ntes:9092,lofter-kafka-bi-risk6.gy.ntes:9092,lofter-kafka-bi-risk7.gy.ntes:9092,lofter-kafka-bi-risk8.gy.ntes:9092
