execution-jar=${classpath}
class=com.netease.lofter.data.common.Clickhouse8NodeLoad
conf.spark.default.parallelism=400
conf.spark.sql.shuffle.partitions=400
conf.spark.dynamicAllocation.maxExecutors=10
conf.spark.executor.cores=4
conf.spark.source.query="\
select dt, \
       itemId, \
       userId, \
       recId, \
       itemType, \
       articleType, \
       scene, \
       costTime, \
       clickCount, \
       negActionCount, \
       commentCount, \
       likeCount, \
       shareCount, \
       recommendCount, \
       flowName, \
       pos, \
       day, \
       payCount, \
       module, \
       recStartTime, \
       query, \
       flag, \
       algWeight \
from lofter_dm.ads_alg_data_user_query_recent_dd \
where dt = '${azkaban.flow.1.days.ago}' "
params=--dest lofter.ads_alg_data_user_query_recent_dd --partition '${azkaban.flow.1.days.ago}'
retries=0
dependencies=ads_alg_data_user_query_recent_dd