execution-jar=${classpath}
class=com.netease.vc.data.common.Hive2Kafka
conf.spark.source.query="select named_struct('packId',packid,'rk',rk,'version',version,'characters',characters,'batchId',packid) as data, \
                            msgtype as msgType,ts,_count,packid as batchId \
                         from vc.dws_vc_feed_boutique_rank_a_d where dt='${azkaban.flow.current.date}' and h='${azkaban.flow.start.hour}'"
params= --topic vc_data_push_msg --key batchId --servers vcharacter-kafka-prod3.gy.ntes:9092,vcharacter-kafka-prod1.gy.ntes:9092,vcharacter-kafka-prod2.gy.ntes:9092

dependencies=dws_vc_feed_boutique_rank_a_d