type=sparksql
hive.query.01=insert overwrite table lofter_dm.ads_creator_newback_traffic_support_di partition(dt = '${azkaban.flow.1.days.ago}') \
select postId, type, t1.blogId  \
from ( \
    select postId, userId as blogId from lofter.dwd_post_publish_di where dt = '${azkaban.flow.1.days.ago}' \
) t1 \
join ( \
    select blogId, type from lofter_dm.ads_ecology_new_return_creator_di where dt <= '${azkaban.flow.1.days.ago}' \
) t2 \
on t1.blogId = t2.blogId \

