type=sparksql
hive.query.01=insert overwrite table lofter_dm.ads_search_word_top_di partition(dt='${azkaban.flow.1.days.ago}') \
    select row_number() over (order by pv desc) as id, words, pv \
    from ( \
        select words,sum(1) as pv \
        from lofter.ods_log_searchmob_di \
        where  dt='${azkaban.flow.1.days.ago}' and tab='label' group by words order by pv desc limit 2000 \
    ) a distribute by 1
