type=sparksql
hive.query.01=insert overwrite table lofter_dm.ads_mbo_ip_di partition(dt = '${azkaban.flow.1.days.ago}') \
select a.ip, nvl(a.sum_realuv,0), nvl(a.expose_pv,0), nvl(a.pay_expose_pv,0), \
    nvl(b.post_cnt_1d,0), nvl(b.premium_post_cnt,0), nvl(b.pay_post_cnt_1d,0), nvl(b.pay_premium_post_cnt,0), \
    nvl(c.new_device_count,0), nvl(d.retain_ratio,0.0), \
    nvl(e.total_expose_pv,0), nvl(f.total_premium_post_cnt,0), \
    nvl(e.total_pay_expose_pv,0), nvl(f.total_pay_premium_post_cnt,0), \
    nvl(b.post_cnt_30d,0), \
    row_number() over (order by sum_realuv desc) as real_uv_rank \
from ( \
    select dt, ip, sum_realuv, expose_pv, pay_expose_pv \
    from lofter.dws_ip_consume_di \
    where dt = '${azkaban.flow.1.days.ago}' \
) a \
left join ( \
    select ip, post_cnt_1d, premium_post_cnt, pay_post_cnt_1d, pay_premium_post_cnt, post_cnt_30d \
    from lofter.dws_ip_supply_di \
    where dt = '${azkaban.flow.1.days.ago}' \
) b on a.ip = b.ip \
left join ( \
    select ip, count(distinct deviceUdid) as new_device_count \
    from lofter.dwd_device_growth_content_di \
        lateral view explode(split(ips, ',')) as ip \
    where dt = '${azkaban.flow.1.days.ago}' and device_type = 'new' \
    group by 1 \
) c on a.ip = c.ip \
left join ( \
    select x.ip, count(distinct y.deviceUdid) / count(distinct x.deviceUdid) as retain_ratio \
    from ( \
        select ip, deviceUdid \
        from lofter.dwd_device_growth_content_di \
            lateral view explode(split(ips, ',')) as ip \
        where dt = '${azkaban.flow.2.days.ago}' and device_type = 'new' \
    ) x \
    left join (select deviceUdid from lofter.device_active where dt = '${azkaban.flow.1.days.ago}') y on x.deviceUdid = y.deviceUdid \
    group by 1 \
) d on a.ip = d.ip \
left join ( \
    select a.dt, \
           sum(a.expose_pv) as total_expose_pv, \
           sum(if(b.postId is not null, a.expose_pv, 0)) as total_pay_expose_pv \
    from ( \
        select dt, postId, expose_pv \
        from lofter.dws_post_traffic_di \
        where dt = '${azkaban.flow.1.days.ago}' \
    ) a \
    left join ( \
        select postId \
        from lofter.dim_gift_post_return_dd \
        where dt = '${azkaban.flow.1.days.ago}' and ispay_returngift in (0, 1) \
        group by 1 \
    ) b on a.postId = b.postId \
    group by 1 \
) e on a.dt = e.dt \
left join ( \
    select a.dt, \
        count(distinct a.postId) total_premium_post_cnt, \
        count(distinct b.postId) as total_pay_premium_post_cnt \
    from ( \
        select dt, postId \
        from lofter.dws_post_premium_di \
        where dt='${azkaban.flow.1.days.ago}' and \
            publish_date between '${azkaban.flow.30.days.ago}' and '${azkaban.flow.1.days.ago}' \
    ) a \
    left join ( \
        select postId \
        from lofter.dim_gift_post_return_dd \
        where dt = '${azkaban.flow.1.days.ago}' and ispay_returngift in (0, 1) \
        group by 1 \
    ) b on a.postId = b.postId \
    group by 1 \
) f on a.dt = f.dt \
