execution-jar=${classpath}
class=com.netease.lofter.etl.common.ClickhouseLoad
conf.spark.source.query="select act_password,new_user_count,return_user_count,new_whiteboard_user_count,search_user_count,search_user_bitmap,actpwd_type,channel,url,itemid,title,content_type,dt from lofter_dm.ads_growth_act_password_di where dt = '${azkaban.flow.1.days.ago}' "
params=--dest hive.ads_growth_act_password_di --partition '${azkaban.flow.1.days.ago}'
retries=0
dependencies=ads_growth_act_password_di