type=sparksql
hive.query.01=insert overwrite table vc.dwd_device_new_di partition(dt = '${azkaban.flow.1.days.ago}') \
select deviceudid,devicemodel,deviceos,firstaccesstime,userid, \
       appchannel,appversion,customudid,imei,idfa,oaid,androidid,finaluserid \
from vc.dwd_device_all_dd \
where dt = '${azkaban.flow.1.days.ago}' and new_date = '${azkaban.flow.1.days.ago}' \

dependencies=dwd_device_all_dd