execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="select base_date as dt, act_password,new_retain_user_count,return_retain_user_count from lofter_dm.ads_growth_act_password_retain_di where dt='${azkaban.flow.1.days.ago}' and base_date ='${azkaban.flow.2.days.ago}' "
params= --partition ${azkaban.flow.1.days.ago} --id act_password --dest lofter_growth_act_password_retain --atom
