execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="select dt, actpwd as act_password, search_devices as search_user_count, new_devices as new_user_count, return_devices as return_user_count, order_cnt as order_count, order_amount, new_whiteboard_user_count, activate_silent_user_count from lofter_dm.ads_kol_actpwd_cvr_di where dt='${azkaban.flow.1.days.ago}'"
params= --partition ${azkaban.flow.1.days.ago} --id act_password --dest lofter_growth_act_password_cvr --atom
dependencies=lofter_growth_act_password,lofter_growth_act_password_retain,lofter_growth_new_attribution,paid_subscribe_kol_attribute_percent_low,ads_kol_actpwd_cvr_di,lofter_growth_act_password_retain_week
