execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="select base_date as dt, act_password, new_retain_7d_user_count as retain_7day_new_user_count, new_retain_3d_6d_user_count as retain_3day_6day_new_user_count from lofter_dm.ads_growth_act_password_retain_di where dt='${azkaban.flow.1.days.ago}' and base_date ='${azkaban.flow.7.days.ago}' "
params= --partition ${azkaban.flow.1.days.ago} --id act_password --dest lofter_growth_act_password_retain_week --atom
