execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="select act_password,new_user_count,return_user_count,new_whiteboard_user_count,search_user_count,activate_silent_user_count,dt from lofter_dm.ads_growth_act_password_di where dt='${azkaban.flow.1.days.ago}'"
params= --partition ${azkaban.flow.1.days.ago} --id act_password --dest lofter_growth_act_password --atom
