execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="select blogId, hot_7d as recent7hot from lofter_dm.ads_blog_hot_dd where dt='${azkaban.flow.1.days.ago}' and hot_7d_diff != 0"
params= --id blogId --dest blog_account_v4 --update --url lofter-online-es1.gy.ntes:7000,lofter-online-es2.gy.ntes:7000,lofter-online-es3.gy.ntes:7000,lofter-online-es4.gy.ntes:7000 --username lofter_online --password Yi3DLCppSI
