execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="select concat_ws('-',relatedId,dataType) as id, relatedId, dataType, dt from lofter_dm.ads_gift_return_negative_di where dt='${azkaban.flow.1.days.ago}' "
params= --partition ${azkaban.flow.1.days.ago} --dest positive_gift_feedback --full --atom --url lofter-online-es1.gy.ntes:7000,lofter-online-es2.gy.ntes:7000,lofter-online-es3.gy.ntes:7000,lofter-online-es4.gy.ntes:7000 --username lofter_online --password Yi3DLCppSI
