execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="select concat_ws('-',stat_type,rk) id, dt,stat_type,blogId,postId,value,rk as rank from lofter_dm.ads_bookstore_hot_list_di where dt='${azkaban.flow.1.days.ago}' and rk<=40"
params= --partition ${azkaban.flow.1.days.ago} --dest lofter_book_store_list --postfixsep --full --atom --url lofter-online-es1.gy.ntes:7000,lofter-online-es2.gy.ntes:7000,lofter-online-es3.gy.ntes:7000,lofter-online-es4.gy.ntes:7000 --username lofter_online --password Yi3DLCppSI