execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="select concat(miniId, '_', postId) as id2, miniId as poolId, postId as id, pay_orders as payCount, pay_orders_7d as recent7DaysPayCount from lofter.dws_miniprogram_post_order_dd where dt = '${azkaban.flow.1.days.ago}' "
params= --dest lofter_post_pool --update --id id2 --url lofter-online-es1.gy.ntes:7000,lofter-online-es2.gy.ntes:7000,lofter-online-es3.gy.ntes:7000,lofter-online-es4.gy.ntes:7000 --username lofter_online --password Yi3DLCppSI --parallel 4
