execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="select concat_ws('-',tag,period,grainIdRank) as id,tag,period,grainId,grainIdRank,grainIdUser,dt  from lofter_dm.ads_grain_square_top_dd where dt='${azkaban.flow.1.days.ago}' "
params= --partition ${azkaban.flow.1.days.ago} --parallel 5 --url lofter-online-es1.gy.ntes:7000,lofter-online-es2.gy.ntes:7000,lofter-online-es3.gy.ntes:7000,lofter-online-es4.gy.ntes:7000 --username lofter_online --password Yi3DLCppSI --dest lofter_grain_square_hot_list --postfixsep --full --atom