execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="select concat_ws('_',distinctId,rk) as id, statType, period, tag, postId, contentType, blogId, hot, rk, distinctId, dt from lofter_dm.ads_grain_batch_hot_list_di where dt='${azkaban.flow.1.days.ago}' and (dayofmonth(dt)=27 or dayofmonth(dt)=1 or substring(dt,6)='01-31' or dayofweek(dt)=6)"
params= --partition ${azkaban.flow.1.days.ago} --dest lofter_batch_grain_hot_list --postfixsep  --atom
