execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="\
select postId, blogId, ip, join_time as publishTime \
from lofter.dim_membership_post_dd \
    lateral view explode(ips) as ip \
where dt = '${azkaban.flow.1.days.ago}' and length(ip) > 0 and \
      join_date <= '${azkaban.flow.1.days.ago}' and  join_date >= '${azkaban.flow.7.days.ago}' \
"
params= --partition ${azkaban.flow.1.days.ago} --id postId --dest lofter_membership_ip_new_post --full --atom --url lofter-online-es1.gy.ntes:7000,lofter-online-es2.gy.ntes:7000,lofter-online-es3.gy.ntes:7000,lofter-online-es4.gy.ntes:7000 --username lofter_online --password Yi3DLCppSI
