
execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="select postId as id, viewCount from lofter_dm.ads_post_backend_view_count_change_di where dt='${azkaban.flow.1.days.ago}' and viewCount != prevViewCount"
params= --dest lofter_post --update --url lofter-online-es1.gy.ntes:7000,lofter-online-es2.gy.ntes:7000,lofter-online-es3.gy.ntes:7000,lofter-online-es4.gy.ntes:7000 --username lofter_online --password Yi3DLCppSI --parallel 2
dependencies=lofter_post_hot
