execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="select concat(tag, '_', postId) as id, tag, type, postId, userId, golden, postHot, publishTime from lofter_dm.ads_wgt_tag_post_dd where dt = '${azkaban.flow.1.days.ago}'"
params= --partition ${azkaban.flow.1.days.ago} --id id --dest lofter_wgt_tag_post --postfixsep --full --atom --url lofter-online-es1.gy.ntes:7000,lofter-online-es2.gy.ntes:7000,lofter-online-es3.gy.ntes:7000,lofter-online-es4.gy.ntes:7000 --username lofter_online --password Yi3DLCppSI --parallel 1