execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="select blogid as id, blogid as blogId,response_count,favorite_count,reblog_count,share_count,subscribe_count,fans_count,ask_answer_favorite_count,dt from lofter_dm.ads_user_hot_behavior_dd where dt='${azkaban.flow.1.days.ago}' "
params= --partition ${azkaban.flow.1.days.ago} --parallel 5 --url lofter-online-es1.gy.ntes:7000,lofter-online-es2.gy.ntes:7000,lofter-online-es3.gy.ntes:7000,lofter-online-es4.gy.ntes:7000 --username lofter_online --password Yi3DLCppSI --dest lofter_user_hot_behavior_dd --postfixsep --atom
