execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="select userId, tagScores from lofter_dm.ads_par_user_subscribed_tags_score_di where dt='${azkaban.flow.1.days.ago}' "
params= --id userId --partition ${azkaban.flow.1.days.ago} --dest lofter_tag_subscribe_score --postfixsep --full --atom --url lofter-online-es1.gy.ntes:7000,lofter-online-es2.gy.ntes:7000,lofter-online-es3.gy.ntes:7000,lofter-online-es4.gy.ntes:7000 --username lofter_online --password Yi3DLCppSI --parallel 2
