execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="\
select userId, postType, postId, blogId, rk, concat(userId, '-', postType, '-', rk) as id \
from lofter_dm.ads_gift_commentator_task_post_pool_di \
where dt = '${azkaban.flow.1.days.ago}' \
"
params= --partition ${azkaban.flow.1.days.ago} --dest lofter_commentator_post --url lofter-online-es1.gy.ntes:7000,lofter-online-es2.gy.ntes:7000,lofter-online-es3.gy.ntes:7000,lofter-online-es4.gy.ntes:7000 --username lofter_online --password Yi3DLCppSI --full --atom
