execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="select queryname as words, sum(searchdevicenum) as pv, sum(if(usertype='新注册', searchdevicenum, 0)) as new_pv from lofter_dm.ads_search_click_result_stats_di where dt > date_sub('${azkaban.flow.1.days.ago}', 15) and dt <= '${azkaban.flow.1.days.ago}' and  octet_length(queryname) < 512  group by queryname having pv > 0"
params= --partition ${azkaban.flow.1.days.ago} --id words --dest lofter_growth_act_password_candidate --atom --full
