execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="\
    select concat_ws('_', userId, roleId) as id,userId,roleId \
    from lofter.dws_pve_user_role_chats_di \
    where dt >= date_sub('${azkaban.flow.1.days.ago}', 13) and dt <= '${azkaban.flow.1.days.ago}' and roleDef = 'ogc' \
    group by userId,roleId \
    having sum(total_chats) >= 30 \
"
params= --partition ${azkaban.flow.1.days.ago} --id id --dest pve_role_user_chat_alias --postfixsep --full --atom --url lofter-online-es1.gy.ntes:7000,lofter-online-es2.gy.ntes:7000,lofter-online-es3.gy.ntes:7000,lofter-online-es4.gy.ntes:7000 --username lofter_online --password Yi3DLCppSI --parallel 1