execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="select postId, publishTime, blogId, title, tags, hot, rank from lofter_dm.ads_pve_user_cp_content_pool_dd where dt = '${azkaban.flow.1.days.ago}'"
params= --partition ${azkaban.flow.1.days.ago} --id postId --dest pve_cpcircle_index --postfixsep --full --atom --url lofter-online-es1.gy.ntes:7000,lofter-online-es2.gy.ntes:7000,lofter-online-es3.gy.ntes:7000,lofter-online-es4.gy.ntes:7000 --username lofter_online --password Yi3DLCppSI --parallel 1