execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="select concat_ws('_',tag,type,honor_name) as id ,tag, type, honor_name as honor from lofter.dws_act_tag_honor_name_di where dt = '${azkaban.flow.1.days.ago}'"
params= --dest tag_honor_new_index --id id --update --url lofter-online-es1.gy.ntes:7000,lofter-online-es2.gy.ntes:7000,lofter-online-es3.gy.ntes:7000,lofter-online-es4.gy.ntes:7000 --username lofter_online --password Yi3DLCppSI --parallel 1