execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="select concat(item_id, '_', if(item_type = '装扮', 0, 1)) as id, item_id as itemId, if(item_type = '装扮', 0, 1) as itemType, tags, order_count as totalOrderCount,order_coins as totalOrderSales,order_count_7d as recent7DaysOrderCount,order_coins_7d as recent7DaysOrderSales from lofter_dm.ads_ec_gift_order_index_di where dt='${azkaban.flow.1.days.ago}' and item_type in ('表情包', '装扮') and length(tags) > 0 "
params= --partition ${azkaban.flow.1.days.ago} --dest trade_prop_return_gift_stat --full --atom --url lofter-online-es1.gy.ntes:7000,lofter-online-es2.gy.ntes:7000,lofter-online-es3.gy.ntes:7000,lofter-online-es4.gy.ntes:7000 --username lofter_online --password Yi3DLCppSI --parallel 4
dependencies=