execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2ES
conf.spark.source.query="select tag, order_count as totalOrderCount,order_coins as totalOrderSales,order_count_7d as recent7DaysOrderCount,order_coins_7d as recent7DaysOrderSales from lofter_dm.ads_ec_gift_tag_order_index_di where dt='${azkaban.flow.1.days.ago}'"
params= --partition ${azkaban.flow.1.days.ago} --dest trade_prop_tag_stat --id tag --full --atom --url lofter-online-es1.gy.ntes:7000,lofter-online-es2.gy.ntes:7000,lofter-online-es3.gy.ntes:7000,lofter-online-es4.gy.ntes:7000 --username lofter_online --password Yi3DLCppSI --parallel 4
dependencies=
