jdbc.driverClass=com.mysql.jdbc.Driver
jdbc.url=jdbc:mysql://10.194.225.210:13331/lofter_activity?user=lofter_activity&password=yFtVAuPAP
jdbc.user=lofter_activity
jdbc.password=yFtVAuPAP


tableName=Luck_PrizeProbabilityStrategy
domainObjectName=LuckPrizeProbabilityStrategy
domain.base.definition=PO,VO,Query
dataSourceName=com.netease.lofter.tango.impl.config.DbConfig.YAOLU_ACTIVITY_DATASOURCE
subPackage=.trade

client.targetProject=lofter-service-tango-api
service.targetProject=lofter-service-tango-impl
useActualColumnNames=true


domain.model.dto.targetProject=${client.targetProject}/src/main/java
domain.model.dto.targetPackage=com.netease.lofter.tango.api.dto${subPackage}

domain.model.po.targetProject=${service.targetProject}/src/main/java
domain.model.po.targetPackage=com.netease.lofter.tango.impl.entity${subPackage}

domain.model.vo.targetProject=${service.targetProject}/src/main/java
domain.model.vo.targetPackage=com.netease.lofter.tango.impl.web.vo${subPackage}

domain.model.query.targetProject=${service.targetProject}/src/main/java
domain.model.query.targetPackage=com.netease.lofter.tango.impl.web.query${subPackage}
domain.model.query.superClass=com.netease.lofter.tango.impl.web.ro.BaseQuery


domain.client.mapper.targetProject=${service.targetProject}/src/main/java
domain.client.mapper.targetPackage=com.netease.lofter.tango.impl.mapper${subPackage}

domain.client.delegate.targetProject=${service.targetProject}/src/main/java
domain.client.delegate.targetPackage=com.netease.lofter.tango.impl.delegate${subPackage}

domain.client.service.targetProject=${service.targetProject}/src/main/java
domain.client.service.targetPackage=com.netease.lofter.tango.impl.service${subPackage}

domain.client.controller.targetProject=${service.targetProject}/src/main/java
domain.client.controller.targetPackage=com.netease.lofter.tango.impl.web.controller${subPackage}

domain.base.PageDO=com.netease.lofter.tango.impl.entity.PageDO
domain.base.PageVO=com.netease.lofter.tango.impl.web.vo.PageVO
domain.base.BageQuery=com.netease.lofter.tango.impl.web.ro.BaseQuery
domain.base.mappers=com.netease.yaolu.commons.spring.mybatis.mapper.CommonMapper,com.netease.yaolu.commons.spring.mybatis.mapper.DeleteCommonMapper
domain.base.CommonDeleteDelegate=com.netease.lofter.tango.impl.delegate.common.CommonDeleteDelegate
domain.base.PageResult=com.netease.lofter.tango.impl.web.vo.PageResult
domain.base.Result=com.netease.lofter.tango.impl.web.vo.Result
domain.base.PrimaryKey=com.netease.lofter.tango.impl.web.vo.PrimiaryKey
domain.base.AssertUtils=com.netease.lofter.tango.impl.util.AssertUtils
domain.base.BeanUtils=com.netease.lofter.tango.impl.util.BeanUtils

