execution-jar=${classpath}
class=com.netease.lofter.data.common.ClickhouseLoad
conf.spark.source.query="select dt,postid,blogid,contenttype,ispay_returngift,tags,blog_channel from lofter_dm.ads_post_easy_fetch_tag_dd where dt = '${azkaban.flow.1.days.ago}' "
params=--dest hive.ads_post_easy_fetch_tag_dd --partition '${azkaban.flow.1.days.ago}' --batch 10000
retries=0
dependencies=ads_post_easy_fetch_tag_dd