execution-jar=${classpath}
class=com.netease.lofter.data.common.ClickhouseLoad
conf.spark.source.query="select dt,userid,tradeid,couponid,unlock_post_id,usetime,usetype,usecount,coin,money,return_post_id,return_gift_id,content_type,return_gift_plantype from lofter_dm.ads_coupon_easy_fetch_use_di where dt = '${azkaban.flow.1.days.ago}' "
params=--dest hive.ads_coupon_easy_fetch_use_di --partition '${azkaban.flow.1.days.ago}' --batch 40960
retries=0
dependencies=ads_coupon_easy_fetch_use_di