execution-jar=${classpath}
class=com.netease.lofter.data.common.ClickhouseLoad
conf.spark.source.query="select dt,userid,couponid,tradeid,type,couponcount,buytime,amount,platform,paytype from lofter_dm.ads_coupon_easy_fetch_type_count_di where dt = '${azkaban.flow.1.days.ago}' "
params=--dest hive.ads_coupon_easy_fetch_type_count_di --partition '${azkaban.flow.1.days.ago}'
retries=0
dependencies=ads_coupon_easy_fetch_type_count_di