type=sparksql
hive.query.01=\
insert overwrite table lofter_dm.ads_easy_fetch_tag_di partition(dt='${azkaban.flow.1.days.ago}') \
select tag,concat_ws(',', ips) as ips,post_count,post_uv,free_post_count,free_photo_post_count,free_text_post_count,free_video_post_count,photo_post_count,text_post_count,video_post_count,photo_post_uv,text_post_uv,video_post_uv,level_s_post_count,level_a_post_count,level_b_post_count,level_c_post_count,level_d_post_count,level_d_star_post_count,level_none_post_count,level_s_post_uv,level_a_post_uv,level_b_post_uv,level_c_post_uv,level_d_post_uv,level_d_star_post_uv,level_none_post_uv,hot,recommend_count,photo_hot,text_hot,video_hot,photo_recommend_count,text_recommend_count,video_recommend_count,expose_pv,real_browse_pv,premium_post_count,photo_premium_post_count,text_premium_post_count,video_premium_post_count \
from lofter.dws_tag_fetch_di \
where dt = '${azkaban.flow.1.days.ago}'