type = sparksql
hive.query.01=insert overwrite table lofter_dm.ads_theater_main_data_report_di partition(dt ='${azkaban.flow.1.days.ago}')   \
select  \
a.dau, \
a.new_user_cnt, \
chat_user , \
cnt_user_10, \
cnt_user_30, \
cnt_user_100, \
avg_cnt_huihe , \
cnt_user_order , \
amount, \
avg_cnt_juchang  \
 \
from( \
select a.dt,count(distinct a.userid) dau , \
count(distinct case when  b.userid is not null then b.userid end ) new_user_cnt \
from  lofter.ods_mda_app_partition_di a  \
left join  \
( \
select userid,min(dt) first_active_date \
from lofter_dm.ads_theater_active_user_report_di \
group by 1 \
)b on a.userid=b.userid and a.dt=b.first_active_date  \
where a.dt='${azkaban.flow.1.days.ago}' \
and a.eventid like '%theater_%' \
group by  a.dt \
) a  \
left join  \
( \
select dt, \
count(user_id)chat_user, \
avg(cnt_juchang) avg_cnt_juchang, \
avg(cnt_huihe) avg_cnt_huihe, \
count(distinct case when cnt_huihe>=10 then user_id end) cnt_user_10, \
count(distinct case when cnt_huihe>=30 then user_id end) cnt_user_30, \
count(distinct case when cnt_huihe>=100 then user_id end) cnt_user_100 \
from( \
select  a.dt,a.user_id,count(distinct c.name)cnt_juchang,count(distinct a.req_id) cnt_huihe \
from  \
( \
select dt,user_id,req_id,biz_id \
from(     \
select  a.dt, a.user_id ,req_id,biz_id,ROW_NUMBER() OVER (PARTITION BY id ORDER BY _bin_op_seqno DESC, _bin_op_time DESC) AS rk       \
from vc.ods_binlog_vc_user_dungeon_chat_record_di a  \
where a.dt='${azkaban.flow.1.days.ago}' \
and a.scene ='PLOT_SIMULATOR_CHAT' \
and a.sender = 2   \
) aa \
where rk=1 \
group by 1,2,3,4 \
) a  \
left join (select id, simulator_id from  vc.ods_db_vc_user_simulator_init_info_nd group by 1,2    )b on a.biz_id=b.id \
left join (select  simulator_id ,name from vc.ods_db_vc_simulator_info_nd where channel = 3 and type = 3  group by 1,2) c on b.simulator_id=c.simulator_id \
group by 1,2  \
) a  \
group by 1  \
) b on a.dt=b.dt  \
left join  \
( \
select  \
from_unixtime(createtime/1000, 'yyyy-MM-dd') dt, \
count(distinct userid)cnt_user_order, \
sum(amount)	amount \
from lofter_db_dump.ods_db_trade_pve_stamina_order_nd \
where from_unixtime(createtime/1000, 'yyyy-MM-dd')='${azkaban.flow.1.days.ago}' \
and producttype in (12,13) \
and status in (1) \
group by 1 \
) c on a.dt=c.dt
dependencies=ads_theater_active_user_report_di