type=sparksql
hive.query.01=insert overwrite table lofter_dm.ads_gift_return_type_di partition(dt='${azkaban.flow.1.days.ago}') \
              select a.ispay_returngift as return_gift_type,contenttype as content_type,  \
              	    case when a.day>=c.day and c.day is not null then c.`type` else '未开通礼物功能' end as `type`,  \
              	    nvl(sourceType,'ugc') as platform_type,  \
              	    count(distinct b.blogid) as uv,  \
                    count(distinct a.postid) as post_num  \
              from   \
              (select distinct day, postid,  \
              	case when num1>0 and num2>0 and num3>0 then 7  \
              		 when num1>0 and num2>0 and num3=0 then 6  \
              		 when num1>0 and num2=0 and num3>0 then 5  \
              		 when num1>0 and num2=0 and num3=0 then 4  \
              		 when num1=0 and num2>0 and num3>0 then 3  \
              		 when num1=0 and num2>0 and num3=0 then 2  \
              		 when num1=0 and num2=0 and num3>0 then 1  \
              		 end as ispay_returngift  \
              from   \
              (select day,postid,  \
              	count(case when ispay_returngift='付费免费' then id else null end) as num1,  \
              	count(case when ispay_returngift='仅付费' then id else null end ) as num2,  \
              	count(case when ispay_returngift='仅免费' then id else null end ) as num3  \
              from   \
              (select distinct a.day,a.postid ,a.id,  \
              	case when a.ispaynum>0 and a.nopaynum>0 then '付费免费'  \
              		 when a.ispaynum>0 and a.nopaynum=0 then '仅付费'  \
              		 when a.ispaynum=0 and a.nopaynum>0 then '仅免费'  \
              		 end as ispay_returngift  \
              from  \
              	(  \
              	select a.day,a.postid,a.id,  \
              		count(case when b.ispay=1 then b.giftid else null end) as ispaynum,  \
              		count(case when b.ispay=0 then b.giftid else null end ) as nopaynum  \
              	from   \
              		(select id, postid,regexp_replace(giftId,'\\\\[|\\\\]', '') as giftid,from_unixtime(cast(createtime / 1000 AS BIGINT), 'yyyy-MM-dd') as day  \
              		from   \
              		lofter_db_dump.ods_db_trade_return_gift_plan_nd   \
              		LATERAL VIEW explode(split(get_json_object(giftjson ,'$.giftIds') ,',')) t2 AS giftId  \
              		where status=1 and auditstatus=1  and from_unixtime(cast(createtime / 1000 AS BIGINT), 'yyyy-MM-dd') ='${azkaban.flow.1.days.ago}'  \
              		group by id, postid,giftId ,from_unixtime(cast(createtime / 1000 AS BIGINT), 'yyyy-MM-dd')   \
              		) a  \
              		join  \
              		(select id as giftid, is_pay as ispay from lofter.dim_gift) b  \
              		on a.giftid=b.giftid  \
              	group by a.day,a.postid,a.id  \
              	) a   \
              ) a  \
              group by day,postid) a  \
              ) a  \
              join  \
              (select id,blogid,contenttype from lofter.dim_post) b  \
              on a.postid=b.id  \
              left join  \
              (select userid,day, case when `type`=1 then '收费权限' else '激励计划' end as `type`  \
              from  \
              (select userid,day,`type`,rank()over(partition by userid order by `type` desc) as rk  \
              from   \
              	(select   userid,from_unixtime(cast(agreetime / 1000 AS BIGINT), 'yyyy-MM-dd') as day,2 as `type`  \
              	from lofter_db_dump.ods_db_trade_gift_account_nd  \
              	where  status=2  \
              	  \
              	union  \
              	select   userid,from_unixtime(cast(agreetime / 1000 AS BIGINT), 'yyyy-MM-dd') as day,1 as `type`  \
              	from   \
              	lofter_db_dump.ods_db_trade_gift_pay_account_nd  \
              	where  status=2) a  \
              ) a  \
              where a.rk=1  \
              group by 1,2,3) c  \
              on b.blogid=c.userid  \
              left join   \
              (select id as blogid, sourceType from lofter.dim_user) d  \
              on b.blogid=d.blogid  \
              group by a.ispay_returngift,contenttype,  \
                       case when a.day>=c.day and c.day is not null then c.`type` else '未开通礼物功能' end,     \
                       nvl(sourceType,'ugc')  \
              with cube   \
              distribute by 1
