type=sparksql
hive.query.01=insert overwrite table lofter_dm.ads_gift_return_type_pv_di partition (dt='${azkaban.flow.1.days.ago}') \
select source_scene, \
    module, \
    return_gift_plantype, \
    count(distinct a.postId) as post_num, \
    sum(realbrowsePv) as real_browse_pv, \
    sum(browsePv) as browse_pv \
from ( \
    select dt as day, \
        postId, \
        source1_scene as source_scene, \
        source_module as module, \
        sum(is_real) as realbrowsePv, \
        count(1) browsePv \
    from lofter.dwd_post_browse_di \
    where dt = '${azkaban.flow.1.days.ago}' and action_type = 'page_duration' \
    group by 1,2,3,4 \
) a \
join ( \
    select  createDate, postid, return_gift_plantype, min(agreeDay) as agreeDay \
    from lofter.dim_gift_post_return \
    where blog_channel=0 and status=1 and auditStatus=1 \
    group by 1,2,3 \
) b on a.postId = b.postid \
where b.agreeDay is not null and a.day>=b.agreeDay and a.day>=b.createDate \
group by source_scene, module, return_gift_plantype \
with cube \
