execution-jar=${classpath}
class=com.netease.vc.data.common.Hive2Kafka
conf.spark.source.query="select userId, asset, props, benefit from vc.ads_vc_user_expire_assets_push_di where dt = '${azkaban.flow.current.date}'"
params=--topic user_asset_expiration_remind_topic --servers vcharacter-kafka-prod3.gy.ntes:9092,vcharacter-kafka-prod1.gy.ntes:9092,vcharacter-kafka-prod2.gy.ntes:9092
dependencies=ads_vc_user_expire_assets_push_di
