type=spark
language=java
master=yarn
spark-version=3.3.0
deploy-mode=cluster
executor-memory=14g
driver-memory=4g
conf.spark.executor.memoryOverhead=1g
conf.spark.driver.memoryOverhead=512m
conf.spark.dynamicAllocation.maxExecutors=25
conf.spark.dynamicAllocation.minExecutors=4
conf.spark.executor.cores=4
conf.spark.sql.shuffle.partitions=250
conf.spark.locality.wait=1s
conf.spark.yarn.maxAppAttempts=2
conf.spark.yarn.am.cores=1
conf.spark.port.maxRetries=64
conf.spark.executor.extraJavaOptions=-verbose:gc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps
conf.spark.sql.catalogImplementation=hive
conf.spark.sql.storeAssignmentPolicy=LEGACY
conf.spark.sql.mapKeyDedupPolicy=LAST_WIN
conf.spark.hadoop.hive.exec.dynamic.partition=true
conf.spark.hadoop.hive.exec.dynamic.partition.mode=nonstrict
conf.spark.speculation=false
conf.spark.sql.hive.convertInsertingPartitionedTable=false
flow.num.job.threads=10
retries=2
retry.backoff=10000
conf.spark.yarn.dist.jars=hdfs://gy-cluster8/user/virtual_character/lib/wm-udx-assembly-0.3.9.jar
dependencies=

