execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2Kafka
conf.spark.source.query="select tag, categoryInfoList from lofter_dm.ads_rec_tag_filter_category_dd where dt = '${azkaban.flow.1.days.ago}'"
params= --topic lofter.tag.filter.category --servers lofter-kafka-dc1.gy.ntes:9092,lofter-kafka-dc2.gy.ntes:9092,lofter-kafka-dc3.gy.ntes:9092
dependencies=ads_rec_tag_filter_category_dd