execution-jar=${classpath}
class=com.netease.vc.data.common.Hive2Kafka
conf.spark.source.query="select user_id as userId,data,dt,hour,'OM3827_2H_NOT_CALLBACK_METRIC' as metricId from vc.ads_vc_om_3827_2h_v2_i_h where dt = '${azkaban.flow.current.date}' and hour = '${azkaban.flow.start.hour}'"
params= --topic vc_user_callback_topic --servers vcharacter-kafka-prod3.gy.ntes:9092,vcharacter-kafka-prod1.gy.ntes:9092,vcharacter-kafka-prod2.gy.ntes:9092

dependencies=ads_vc_om_3827_2h_v2_i_h
