# 统一认证服务配置
# 应用系统首页uri（浏览器使用，需要办公网）
aac.appIndexUri = http://dt.bdms.netease.com
# 应用系统清理token的uri（服务间使用，需要机房网）
aac.appClearUri = http://ndi.service.163.org
aac.serverUri = http://aac.bdms.netease.com
aac.path.login = /aac/api/auth/v1/login
aac.path.logout = /aac/api/auth/v1/logout
aac.path.getUser = /aac/api/auth/v1/user/get
aac.path.clearToken = /aac/api/auth/v1/token/clear
