type=sparksql
hive.query.01=create temporary function version_compare as 'com.netease.wm.udf.VersionCompare';
hive.query.02=insert overwrite table lofter_dm.ads_sdk_hybrid_white_screen_di partition(dt = '${azkaban.flow.1.days.ago}') \
SELECT deviceos, \
       eventid, \
       appversion, \
       case when get_json_object(params['ext'], '$.presetDataReadyTime')='0' then 0 else 1 end as flg, \
       get_json_object(params['ext'], '$.noteScene') as noteScene, \
       scene, \
       count(distinct deviceudid) as uv,count( deviceudid) as pv \
FROM lofter.ods_mda_app_partition_di  \
WHERE dt= '${azkaban.flow.1.days.ago}' \
      and actionType in ('system', 'page_view') \
      and eventid in ('g1-8','t1-1') \
      and version_compare(appversion, '7.5.6' ) > 0 \
group by 1,2,3,4,5,6

