// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import path from "path";
import { defineConfig } from "prisma/config";

// 按优先级加载环境变量：.env.local > .env.test > .env
const envFiles = [".env.local", ".env.test", ".env"];
for (const file of envFiles) {
  config({ path: path.resolve(process.cwd(), file) });
}

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: process.env["DATABASE_URL"]!,
  },
});