sklearn.feature_extraction.text.TfidfTransformer=com.netease.easyml.ml.sklearn.feature_extraction.TfidfTransformerModel
sklearn.feature_extraction.text.CountVectorizer=com.netease.easyml.ml.sklearn.feature_extraction.CountVectorizerModel
sklearn.feature_extraction.text.TfidfVectorizer=com.netease.easyml.ml.sklearn.feature_extraction.TfidfVectorizerModel
sklearn.feature_extraction.text.HashingVectorizer=com.netease.easyml.ml.sklearn.feature_extraction.HashingVectorizer
sklearn.preprocessing._label.LabelEncoder=com.netease.easyml.ml.sklearn.preprocessing.LabelEncoderModel
sklearn.preprocessing._label.LabelBinarizer=com.netease.easyml.ml.sklearn.preprocessing.LabelBinarizerModel
sklearn.preprocessing._label.MultiLabelBinarizer=com.netease.easyml.ml.sklearn.preprocessing.MultiLabelBinarizerModel
sklearn.preprocessing._data.MaxAbsScaler=com.netease.easyml.ml.sklearn.preprocessing.MaxAbsScalerModel
sklearn.preprocessing._data.MinMaxScaler=com.netease.easyml.ml.sklearn.preprocessing.MinMaxScalerModel
sklearn.preprocessing._data.Normalizer=com.netease.easyml.ml.sklearn.preprocessing.Normalizer
sklearn.preprocessing._data.StandardScaler=com.netease.easyml.ml.sklearn.preprocessing.StandardScalerModel
sklearn.preprocessing._data.Binarizer=com.netease.easyml.ml.sklearn.preprocessing.Binarizer
sklearn.preprocessing._data.RobustScaler=com.netease.easyml.ml.sklearn.preprocessing.RobustScaler
sklearn.preprocessing._encoders.OrdinalEncoder=com.netease.easyml.ml.sklearn.preprocessing.OrdinalEncoderModel
sklearn.preprocessing._encoders.OneHotEncoder=com.netease.easyml.ml.sklearn.preprocessing.OneHotEncoderModel
sklearn.preprocessing._discretization.KBinsDiscretizer=com.netease.easyml.ml.sklearn.preprocessing.KBinsDiscretizerModel
sklearn.preprocessing._data.KernelCenterer=com.netease.easyml.ml.sklearn.preprocessing.KernalCentererModel
sklearn.decomposition._pca.PCA=com.netease.easyml.ml.sklearn.decomposition.PCAModel
sklearn.decomposition._pca.TruncatedSVD=com.netease.easyml.ml.sklearn.decomposition.PCAModel
sklearn.cluster._kmeans.KMeans=com.netease.easyml.ml.sklearn.cluster.KMeansModel
sklearn.cluster._kmeans.MiniBatchKMeans=com.netease.easyml.ml.sklearn.cluster.KMeansModel
sklearn.mixture._gaussian_mixture.GaussianMixture=com.netease.easyml.ml.sklearn.cluster.GaussianMixture
sklearn.pipeline.Pipeline=com.netease.easyml.ml.sklearn.pipeline.PipelineModel
sklearn.linear_model._logistic.LogisticRegression=com.netease.easyml.ml.sklearn.linear_model.LogisticRegressionModel
sklearn.svm._classes.LinearSVC=com.netease.easyml.ml.sklearn.linear_model.LinearSVCModel
sklearn.naive_bayes.MultinomialNB=com.netease.easyml.ml.sklearn.naive_bayes.NaiveBayesModel