type=spark
language=java
master=yarn
spark-version=3.3.0
deploy-mode=cluster
executor-memory=10g
driver-memory=3g
conf.spark.dynamicAllocation.maxExecutors=25
conf.spark.sql.catalogImplementation=hive
conf.spark.sql.storeAssignmentPolicy=LEGACY
conf.spark.sql.mapKeyDedupPolicy=LAST_WIN
conf.spark.executor.cores=4
conf.spark.executor.extraJavaOptions=-verbose:gc -XX:+PrintGCDetails -XX:+PrintGCTimeStamps
conf.spark.sql.shuffle.partitions=100
conf.spark.driver.memory=2g
conf.spark.executor.memoryOverhead=4g
conf.spark.driver.memoryOverhead=1g
conf.spark.locality.wait=0
conf.spark.yarn.maxAppAttempts=1
conf.spark.yarn.am.cores=1
conf.spark.port.maxRetries=64
conf.spark.hadoop.hive.exec.dynamic.partition=true
conf.spark.hadoop.hive.exec.dynamic.partition.mode=nonstrict
conf.spark.speculation=false
conf.spark.yarn.dist.jars=hdfs://gy-cluster8/user/da_lofter/udf/wm-udx-assembly-0.3.9.jar
conf.spark.sql.hive.convertInsertingPartitionedTable=false
flow.num.job.threads=10
retries=2
retry.backoff=10000
dependencies=
