[libdefaults]
  default_realm=HADOOP.HZ.NETEASE.COM
  allow_weak_crypto=true
  dns_lookup_realm=false
  dns_lookup_kdc=false
  ticket_lifetime=24h
  renew_lifetime=7d
  forwardable=true
  udp_preference_limit=0
  kdc_timeout=10000
  max_retries=3

[domain_realm]
  gy.ntes=HADOOP.GY.NETEASE.COM
  .gy.ntes=HADOOP.GY.NETEASE.COM
  .hz.163.org=HADOOP.HZ.NETEASE.COM
  .jd.163.org=HADOOP2.HZ.NETEASE.COM
  .lt.163.org=HADOOP.HZ.NETEASE.COM
  .photo.163.org=HADOOP.HZ.NETEASE.COM
  music-bigdata-kdc-1.gy.ntes = HADOOP2.HZ.NETEASE.COM
  music-bigdata-kdc-2.gy.ntes = HADOOP2.HZ.NETEASE.COM
  music-bigdata-kdc-3.gy.ntes = HADOOP.HZ.NETEASE.COM
  music-bigdata-kdc-4.gy.ntes = HADOOP.HZ.NETEASE.COM

[realms]
  HADOOP.GY.NETEASE.COM={
    admin_server=music-hadoop-1.gy.ntes:1749
    kdc=music-hadoop-1.gy.ntes:1088
    kdc=music-hadoop-2.gy.ntes:1088
  }
  HADOOP.HZ.NETEASE.COM={
   kdc = music-bigdata-kdc-3.gy.ntes
   kdc = music-bigdata-kdc-4.gy.ntes
  }
  HADOOP2.HZ.NETEASE.COM={
    admin_server=hadoop2246.jd.163.org
    kdc = music-bigdata-kdc-1.gy.ntes
    kdc = music-bigdata-kdc-2.gy.ntes
    kdc=hadoop2246.jd.163.org
  }

[capaths]
  HADOOP.GY.NETEASE.COM={
    HADOOP.HZ.NETEASE.COM=.
    HADOOP2.HZ.NETEASE.COM=.
  }
  HADOOP.HZ.NETEASE.COM={
    HADOOP.GY.NETEASE.COM=.
    HADOOP2.HZ.NETEASE.COM=.
  }
  HADOOP2.HZ.NETEASE.COM={
    HADOOP.GY.NETEASE.COM=.
    HADOOP.HZ.NETEASE.COM=.
  }