# MySQL properties
spring.datasource.driver-class-name=com.mysql.jdbc.Driver
spring.datasource.url=jdbc:mysql://hadoop2496.jd.163.org:10080/ndi?useSSL=false&characterEncoding=utf-8
spring.datasource.username=ndi
spring.datasource.password=WtVUcwrnv

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.type-handlers-package=com.netease.bdms.ndi.service.web.config.mybatis
#pagehelper
pagehelper.helperDialect=mysql
pagehelper.reasonable=false
pagehelper.supportMethodsArguments=true
pagehelper.params=count=countSql
server.port=8089

# 统一认证服务配置
# 应用系统首页uri（浏览器使用，需要办公网）
aac.appIndexUri = http://ds-dev.bdms.netease.com
# 应用系统清理token的uri（服务间使用，需要机房网）
aac.appClearUri = http://datastream36.lt.163.org:8089
aac.serverUri = http://aac-test.bdms.netease.com
aac.path.login = /aac/api/auth/v1/login
aac.path.logout = /aac/api/auth/v1/logout
aac.path.getUser = /aac/api/auth/v1/user/get
aac.path.clearToken = /aac/api/auth/v1/token/clear

