#Redis
redis.ip=10.201.168.154
redis.port=6379
redis.password=bdmstest
redis.max.total=20
redis.max.idle=10
redis.min.idle=2
#mammut
mammut.service.address=http://bdmsmeta-qa.service.163.org
mammut.api.key=14b4e567-0695-44d1-aada-f81e36f0e92b
mammut.master.key=2265159e-5ac5-4a97-84e3-ef0c80ef8b7c
# metahub
meta.server.address=http://hzabj-metacenter101.server.163.org:8061
metahub.appid=root
metahub.secret=root
# white list
ip.white.list=10.160.128.31,10.160.128.32,172.17.0.31,10.165.139.76
api.white.list=/api/v1/auth,/api/login,/api/logon,/api/check/login,/api/v1/task/client/task,/api/v1/task/taskName,/api/v1/check
