execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2Kafka
conf.spark.source.query="select cardActivityCode as activity_code, browse_uv_30d from lofter_dm.ads_act_card_browse_dd where dt='${azkaban.flow.1.days.ago}'"
params= --topic backend.data.sync --meta _payload_type=card_browse,_payload_date=${azkaban.flow.1.days.ago} --servers lofter-kafka-bi-risk1.gy.ntes:9092,lofter-kafka-bi-risk2.gy.ntes:9092,lofter-kafka-bi-risk3.gy.ntes:9092
