execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2Kafka
conf.spark.source.query="select idea_id as id, rePresentPostId, rePresentPostBlogId, highestSinglePostIncome, income, rePresentPostIncome, weeklyGiftAmount,averageIncome,yesterdayHighestIncome,weeklyHighestIncome from lofter_dm.ads_creator_idea_di where dt = '${azkaban.flow.1.days.ago}' "
params= --topic LOFTER.COMMON.PayCreatorIdea.Stat --servers lofter-kafka-dc1.gy.ntes:9092,lofter-kafka-dc2.gy.ntes:9092,lofter-kafka-dc3.gy.ntes:9092
