execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2KafkaPayload
conf.spark.source.query="select blogId, questionUserId, questionId, 1dScoreCount as nominatedCount from lofter_dm.ads_act_renjianbaitai_blog_statistics_di where dt = '${azkaban.flow.1.days.ago}'"
params= --messageType 10 --topic lofter.common.businessData --servers lofter-kafka-dc1.gy.ntes:9092,lofter-kafka-dc2.gy.ntes:9092,lofter-kafka-dc3.gy.ntes:9092