execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2Kafka
conf.spark.source.query=" \
SELECT userId, \
       creatorNewStatus, \
       creatorOldStatus, \
       growingSign \
FROM lofter_dm.ads_creator_ecology_identity_change_dd \
WHERE dt = '${azkaban.flow.1.days.ago}' \
"
params= --topic LOFTER.COMMON.CREATOR.STATUS --servers lofter-kafka-dc1.gy.ntes:9092,lofter-kafka-dc2.gy.ntes:9092,lofter-kafka-dc3.gy.ntes:9092