execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2KafkaPayload
conf.spark.source.query="select questionId as itemId, 1 as itemType, blogId, recReason, priority, -1 as tagLottieType, weight from lofter_dm.ads_rec_question_rec_reason_di where dt = '${azkaban.flow.1.days.ago}'"
params=  --messageType 6 --topic rec_bdms_question_reason --servers lofter-kafka-recommend1.gy.ntes:9092,lofter-kafka-recommend2.gy.ntes:9092,lofter-kafka-recommend3.gy.ntes:9092
