execution-jar=${classpath}
class=com.netease.lofter.data.common.Hive2Kafka
conf.spark.source.query="select ip, userTypes, newUserRank, returnUserRank, tags from rec.ads_ecology_new_return_user_guide_di_all where day = '${azkaban.flow.1.days.ago}'"
params= --topic rec_bdms_guide_ip_tags --servers lofter-kafka-recommend1.gy.ntes:9092,lofter-kafka-recommend2.gy.ntes:9092,lofter-kafka-recommend3.gy.ntes:9092
